export const TRIP = {
  route: 'Paris → Bordeaux → Lyon → Provence → Nice → Alsace (Strasbourg)',
}

export const CITIES = [
  {
    id: 'paris',
    name: 'Paris',
    emoji: '🗼',
    hotel: 'Le Marais or Saint-Germain-des-Prés',
    desc: 'The City of Light — Haussmann boulevards, world-class museums, legendary patisseries and effortless style.',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80',
    color: '#6c3483',
    highlights: [
      'Eiffel Tower — climb to level 2 at dusk for the city panorama',
      'The Louvre — arrive early, head straight to Denon Wing for the Mona Lisa',
      'Musée d\'Orsay — Impressionist collection in a converted railway station',
      'Notre-Dame Cathedral — reconstruction ongoing, exterior is extraordinary',
      'Sainte-Chapelle — 13th-century Gothic chapel with stained glass ceiling',
      'Le Marais — medieval streets, falafel at L\'As du Fallafel, galleries',
      'Montmartre & Sacré-Cœur — artists\' hill, vineyard, best views of the city',
      'Canal Saint-Martin — iron footbridges, hip cafés, Sunday market atmosphere',
    ],
    tips: [
      'Paris Museum Pass (2/4/6 days) skips entry queues at 60+ museums — buy online',
      'Metro is cheap and extensive — buy a carnet of 10 tickets or use contactless',
      'Lunch is the best deal — plat du jour at a bistro is often €12–16 including wine',
      'Avoid tourist restaurants near major sights — walk two streets away for real Parisian food',
    ],
  },
  {
    id: 'nice',
    name: 'Nice',
    emoji: '🌊',
    hotel: 'Vieux-Nice or Promenade des Anglais',
    desc: 'Capital of the Côte d\'Azur — pastel Belle Époque facades, the azure Mediterranean, and the best socca in the world.',
    image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80',
    color: '#2874a6',
    highlights: [
      'Promenade des Anglais — the legendary 7km seafront promenade',
      'Vieux-Nice — ochre and terracotta alleyways, Baroque chapels, flower market',
      'Colline du Château — free hilltop park with panoramic bay views',
      'Cours Saleya Market — one of the best outdoor markets in France (daily except Monday)',
      'MAMAC — Museum of Modern and Contemporary Art, rooftop terrace',
      'Day trip to Monaco — 25 minutes by train, Casino de Monte-Carlo, Prince\'s Palace',
      'Day trip to Èze — perched village 400m above the sea, medieval ruins',
      'Matisse Museum — the artist lived and worked in Nice for 37 years',
    ],
    tips: [
      'Socca (chickpea pancake) at Chez Pipo or the Cours Saleya stalls — Nice\'s signature street food',
      'Train along the coast is far faster and cheaper than driving — avoid Côte d\'Azur traffic',
      'Markets start winding down by noon — arrive before 10:00 for the best produce',
      'Pebble beach — pack water shoes for swimming comfort',
    ],
  },
  {
    id: 'bordeaux',
    name: 'Bordeaux',
    emoji: '🍷',
    hotel: 'Triangle d\'Or or Saint-Pierre quarter',
    desc: 'World wine capital with stunning neoclassical architecture, a 12th-century wine trade heritage, and a buzzing food scene.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#6e2c00',
    highlights: [
      'La Cité du Vin — extraordinary wine museum with global tastings included (€22)',
      'Place de la Bourse and the Miroir d\'Eau — largest reflecting pool in the world',
      'Saint-Émilion day trip — medieval wine village, UNESCO heritage, underground church',
      'Marché des Capucins — covered market, oysters with Sauternes at 9am is tradition',
      'Rue Sainte-Catherine — longest pedestrian shopping street in France (1.2km)',
      'Grosse Cloche — 15th-century bell tower and city gate',
      'Darwin Ecosystem — repurposed military barracks with street art, skate park, organic market',
      'Médoc châteaux drive — Château Pichon Baron, Lynch-Bages, many open for tastings',
    ],
    tips: [
      'Wine tastings: always ask for Pomerol and Saint-Émilion alongside Médoc classics',
      'Canelés (small caramelised rum pastries) are a Bordeaux speciality — buy from Baillardran',
      'Tram network is excellent and covers the city centre and La Cité du Vin',
      'Book Saint-Émilion caves and wine tours ahead in peak season',
    ],
  },
  {
    id: 'lyon',
    name: 'Lyon',
    emoji: '🍽️',
    hotel: 'Presqu\'île or Vieux Lyon',
    desc: 'France\'s gastronomic capital — ancient bouchons, two UNESCO-listed districts, and where modern French cuisine was born.',
    image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&q=80',
    color: '#c0392b',
    highlights: [
      'Vieux Lyon — largest Renaissance old town in France (UNESCO)',
      'Les Traboules — secret Renaissance passageways through apartment blocks',
      'Paul Bocuse market (Halles de Lyon) — legendary covered food market',
      'Basilique Notre-Dame de Fourvière — hilltop basilica with city panorama',
      'Théâtres Romains — 2,000-year-old Roman amphitheatres still used for concerts',
      'Croix-Rousse district — silk weavers\' quarter, street art, Saturday market',
      'Musée des Confluences — stunning science and natural history museum at the river confluence',
      'Fête des Lumières (December) — city-wide light installation festival',
    ],
    tips: [
      'Eat in a traditional bouchon — ask for quenelles de brochet, andouillette, or tête de veau',
      'Lyon City Card (1/2/3 days) covers all museums and public transport',
      'Funicular from Vieux Lyon to Fourvière is included on the city transport pass',
      'Book bouchon dinners in advance — the best ones fill up by noon',
    ],
  },
  {
    id: 'provence',
    name: 'Provence',
    emoji: '🌻',
    hotel: 'Aix-en-Provence or a village mas near Luberon',
    desc: 'Lavender fields, sun-bleached limestone villages perchés, olive groves, rosé wine, and the timeless light that captivated Cézanne.',
    image: 'https://images.unsplash.com/photo-1535700669388-81fcc040c400?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'Luberon villages — Gordes, Les Baux-de-Provence, Roussillon ochre cliffs',
      'Abbaye de Sénanque — 12th-century abbey surrounded by lavender (June–July peak)',
      'Pont du Gard — 2,000-year-old Roman aqueduct, best at sunrise (free before 8am)',
      'Aix-en-Provence — Cézanne\'s town, Cours Mirabeau boulevard, daily market',
      'Palais des Papes, Avignon — largest Gothic palace in the world (UNESCO)',
      'Les Alpilles — white limestone ridges, olive groves, Van Gogh country',
      'Cassis and Les Calanques — dramatic white limestone fjords, boat trips or hiking',
      'Fontaine-de-Vaucluse — mysterious river emerging from cliffs in a spectacular gorge',
    ],
    tips: [
      'Car is essential in Provence — villages are beautiful but rural and barely served by public transport',
      'Rosé wine from Bandol and Côtes de Provence — drink local, drink pink',
      'Markets: Apt on Saturday, L\'Isle-sur-la-Sorgue on Sunday, Aix daily on Cours Mirabeau',
      'Lavender blooms late June to early August — Valensole Plateau is the best display',
    ],
  },
  {
    id: 'alsace',
    name: 'Alsace (Strasbourg)',
    emoji: '🏘️',
    hotel: 'La Petite France quarter or city centre',
    desc: 'Half-timbered houses, Germanic-French fusion cuisine, the Rhine frontier, and Europe\'s finest Christmas market.',
    image: 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80',
    color: '#e74c3c',
    highlights: [
      'La Petite France — medieval tanner and miller quarter with canals and lock gates',
      'Strasbourg Cathedral — Gothic masterpiece, 142m spire, 14th-century astronomical clock',
      'Grande Île — UNESCO-listed historic centre, one of first European sites to receive the honour',
      'Alsace Wine Route — 170km driving route through 68 wine villages from Marlenheim to Thann',
      'Colmar day trip — possibly France\'s most beautiful small town, Venice of Alsace',
      'Haut-Kœnigsbourg Castle — restored medieval fortress with panoramic Rhine plain views',
      'Riquewihr and Ribeauvillé — perfectly preserved medieval wine villages on the Route du Vin',
      'European Parliament visit — book tours of the Parliament building in advance',
    ],
    tips: [
      'Tarte flambée (Flammkuchen) is the regional speciality — thin crispy base, crème fraîche, lardons, onion',
      'Alsace wines: Riesling, Gewurztraminer, Pinot Gris — very different from the rest of France',
      'Germany is 5 minutes across the Rhine bridge — Kehl makes a nice half-day side trip',
      'Christmas Market (late Nov–Dec) is extraordinary but extremely crowded — book hotels months ahead',
    ],
  },
]

export const RESTAURANTS = {
  paris: [
    { name: 'Septime', type: 'Modern French / Bistronomie', price: '€60–90', rating: '4.8', area: 'Bastille', notes: 'One of Paris\'s most acclaimed neo-bistros. Book 4+ weeks ahead via website.' },
    { name: 'Le Comptoir du Relais', type: 'Classic Brasserie / Bistro', price: '€25–45', rating: '4.6', area: 'Saint-Germain', notes: 'Legendary Saint-Germain bistro. Walk-in lunch only — dinner is set menu and must be booked.' },
    { name: 'L\'As du Fallafel', type: 'Falafel / Street Food', price: '€8–12', rating: '4.5', area: 'Le Marais', notes: 'Best falafel in Paris. Always a queue but it moves fast. Cash only.' },
    { name: 'Frenchie', type: 'Modern French', price: '€55–75', rating: '4.7', area: 'Sentier', notes: 'Anglo-French neo-bistro. Very hard to book — try the wine bar next door for walk-ins.' },
    { name: 'Berthillon', type: 'Ice Cream / Glacier', price: '€5–8', rating: '4.6', area: 'Île Saint-Louis', notes: 'Paris\'s most celebrated glacier since 1954. Salted caramel and nougat are classics.' },
  ],
  nice: [
    { name: 'Chez Pipo', type: 'Socca / Niçoise', price: '€10–20', rating: '4.4', area: 'Vieux-Nice', notes: 'The definitive socca spot. Also serves pissaladière and daube. Cash only at the socca counter.' },
    { name: 'La Merenda', type: 'Traditional Niçoise', price: '€30–45', rating: '4.7', area: 'Vieux-Nice', notes: 'Tiny, legendary. No phone — book in person. Former Michelin chef gone back to basics.' },
    { name: 'Le Safari', type: 'Brasserie / Niçoise', price: '€25–40', rating: '4.3', area: 'Cours Saleya', notes: 'Great terrace on the flower market. Reliable salade niçoise and bouillabaisse.' },
    { name: 'Acchiardo', type: 'Old-school Bistro', price: '€18–30', rating: '4.5', area: 'Vieux-Nice', notes: 'Family-run since 1927. Handwritten menu changes daily. Very local crowd.' },
    { name: 'Le Chantecler (Negresco)', type: 'Grand Gastronomy', price: '€120+', rating: '4.8', area: 'Promenade des Anglais', notes: 'Palatial belle époque dining room. Special occasion only. Book well ahead.' },
  ],
  bordeaux: [
    { name: 'Le Pressoir d\'Argent (Gordon Ramsay)', type: 'Grand Gastronomy', price: '€150+', rating: '4.7', area: 'Grand Hôtel', notes: 'Best restaurant in Bordeaux. Lobster press is the signature. Book months ahead.' },
    { name: 'La Tupina', type: 'Traditional Gascon', price: '€35–60', rating: '4.5', area: 'Saint-Pierre', notes: 'Fireplace cooking, foie gras, duck confit, cassoulet. The soul of south-west French cooking.' },
    { name: 'Marché des Capucins', type: 'Market / Oysters', price: '€15–25', rating: '4.6', area: 'Capucins', notes: 'Oysters with Sauternes at the market stalls. Saturday morning is the classic visit.' },
    { name: 'Le Petit Commerce', type: 'Seafood Bistro', price: '€30–50', rating: '4.5', area: 'Saint-Pierre', notes: 'Outstanding seafood. The grilled sole and plateau de fruits de mer are unmissable.' },
  ],
  lyon: [
    { name: 'Daniel & Denise (Saint-Jean)', type: 'Traditional Bouchon', price: '€30–50', rating: '4.6', area: 'Vieux Lyon', notes: 'Best traditional bouchon in the city. Quenelles, andouillette, and Lyon-style sausage.' },
    { name: 'Les Halles de Lyon Paul Bocuse', type: 'Food Market', price: '€15–40', rating: '4.7', area: 'Part-Dieu', notes: 'The temple of Lyon food. Trolliet for charcuterie, Mère Richard for cheese, Pupier for quenelles.' },
    { name: 'Tetedoie', type: 'Gastronomic / View', price: '€80–120', rating: '4.7', area: 'Fourvière', notes: 'Michelin-starred with panoramic terrace. Best city view while dining in Lyon.' },
    { name: 'Café des Fédérations', type: 'Classic Bouchon', price: '€25–40', rating: '4.4', area: 'Presqu\'île', notes: 'Quintessential bouchon atmosphere. Checked tablecloths, communal tables, house Beaujolais.' },
    { name: 'Takao Takano', type: 'Modern French', price: '€90–130', rating: '4.8', area: 'Brotteaux', notes: 'Japanese-French chef, two Michelin stars. Remarkably precise and beautiful food.' },
  ],
  provence: [
    { name: 'Oustau de Baumanière', type: 'Grand Gastronomy', price: '€180+', rating: '4.8', area: 'Les Baux-de-Provence', notes: 'Three Michelin stars in a 14th-century farmhouse. The crown jewel of Provence dining.' },
    { name: 'Le Bercail', type: 'Provençal Bistro', price: '€25–40', rating: '4.4', area: 'Avignon', notes: 'Lovely terrace on the Île de la Barthelasse. Reach by free ferry. Traditional Provençal cuisine.' },
    { name: 'Le Vieux Four', type: 'Village Bistro', price: '€18–30', rating: '4.3', area: 'Gordes', notes: 'Reliable local cooking in the heart of one of France\'s most beautiful villages.' },
    { name: 'Le Garage', type: 'Modern Provençal', price: '€35–55', rating: '4.5', area: 'Aix-en-Provence', notes: 'Creative cuisine using Provençal ingredients. Excellent wine list. Book ahead.' },
  ],
  alsace: [
    { name: 'Winstub Zum Strissel', type: 'Traditional Alsatian Winstub', price: '€20–35', rating: '4.5', area: 'Strasbourg centre', notes: 'Definitive winstub experience. Tarte flambée, choucroute garnie, baeckeoffe. Since 1310.' },
    { name: 'Au Crocodile', type: 'Grand Gastronomy', price: '€100–160', rating: '4.7', area: 'Strasbourg centre', notes: 'The finest restaurant in Alsace. Two Michelin stars. Classic Alsatian techniques elevated.' },
    { name: 'Maison Kammerzell', type: 'Historic Brasserie', price: '€25–45', rating: '4.4', area: 'Cathedral square', notes: 'Stunning 15th-century building opposite the cathedral. Tourist-facing but food is genuinely good.' },
    { name: 'JY\'s (Jean-Yves Schillinger)', type: 'Modern French', price: '€70–100', rating: '4.6', area: 'Colmar', notes: 'Best restaurant in Colmar. Innovative, elegant. One Michelin star.' },
    { name: 'Friterie Valentin', type: 'Street Food / Kebab Alsacien', price: '€5–10', rating: '4.3', area: 'Strasbourg', notes: 'Late-night Alsatian kebab tradition. Munster cheese and lardons inside. A local institution.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'Paris Museum Pass', cost: '€55 (4 days)', notes: 'Covers 60+ museums including Louvre, Orsay, Versailles — skips ticket queues' },
    { name: 'Navigo Easy (Paris Metro)', cost: 'Load as needed', notes: 'Works on all Paris metro, RER, and bus lines. Use contactless bank card alternatively.' },
    { name: 'Lyon City Card', cost: '€27 (2 days)', notes: 'All Lyon museums, funicular, and public transport included' },
    { name: 'SNCF Rail Pass', cost: 'Varies', notes: 'France by Train. TGV connects Paris–Lyon (2h), Paris–Bordeaux (2h10), Paris–Strasbourg (1h47)' },
  ],
  apps: ['Google Maps (offline)', 'SNCF Connect (train tickets)', 'Citymapper (Paris)', 'The Fork / LaFourchette (restaurant bookings)', 'Google Translate', 'XE Currency'],
  phrases: [],
  phrasesByCategory: [
    {
      category: 'Greetings & Basics',
      emoji: '👋',
      phrases: [
        { en: 'Hello', jp: 'Bonjour', romaji: 'Bonjour' },
        { en: 'Good evening', jp: 'Bonsoir', romaji: 'Bonsoir' },
        { en: 'Goodbye', jp: 'Au revoir', romaji: 'Oh reh-vwar' },
        { en: 'Please', jp: 'S\'il vous plaît', romaji: 'Seel voo pleh' },
        { en: 'Thank you', jp: 'Merci', romaji: 'Mehr-see' },
        { en: 'Thank you very much', jp: 'Merci beaucoup', romaji: 'Mehr-see boh-koo' },
        { en: 'Yes', jp: 'Oui', romaji: 'Wee' },
        { en: 'No', jp: 'Non', romaji: 'Noh' },
        { en: 'Excuse me / Sorry', jp: 'Excusez-moi', romaji: 'Ex-kyu-zay mwah' },
        { en: 'I don\'t understand', jp: 'Je ne comprends pas', romaji: 'Zhuh nuh kom-prahn pah' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚉',
      phrases: [
        { en: 'Where is...?', jp: 'Où est...?', romaji: 'Oo eh...?' },
        { en: 'The station, please', jp: 'La gare, s\'il vous plaît', romaji: 'La gar, seel voo pleh' },
        { en: 'A ticket to...', jp: 'Un billet pour...', romaji: 'Un bee-yeh poor...' },
        { en: 'How much is it?', jp: 'Combien ça coûte?', romaji: 'Kom-byahn sa koot?' },
        { en: 'To the left', jp: 'À gauche', romaji: 'Ah gosh' },
        { en: 'To the right', jp: 'À droite', romaji: 'Ah drwat' },
        { en: 'Straight ahead', jp: 'Tout droit', romaji: 'Too drwah' },
        { en: 'I am lost', jp: 'Je suis perdu(e)', romaji: 'Zhuh swee pehr-dew' },
      ],
    },
    {
      category: 'Food & Dining',
      emoji: '🥐',
      phrases: [
        { en: 'A table for two please', jp: 'Une table pour deux, s\'il vous plaît', romaji: 'Ewn tah-bluh poor duh, seel voo pleh' },
        { en: 'The menu please', jp: 'La carte, s\'il vous plaît', romaji: 'La kart, seel voo pleh' },
        { en: 'The bill please', jp: 'L\'addition, s\'il vous plaît', romaji: 'La-dee-syoh, seel voo pleh' },
        { en: 'Delicious!', jp: 'C\'est délicieux!', romaji: 'Say day-lee-syuh!' },
        { en: 'Do you have vegetarian options?', jp: 'Vous avez des plats végétariens?', romaji: 'Voo za-vay day plah vay-zhay-tar-yahn?' },
        { en: 'Water please', jp: 'De l\'eau, s\'il vous plaît', romaji: 'Duh loh, seel voo pleh' },
        { en: 'A glass of red wine', jp: 'Un verre de vin rouge', romaji: 'Un vehr duh van roozh' },
        { en: 'A carafe of house wine', jp: 'Une carafe de vin de la maison', romaji: 'Ewn ka-raf duh van duh la may-zohn' },
      ],
    },
    {
      category: 'Shopping',
      emoji: '🛍️',
      phrases: [
        { en: 'How much is this?', jp: 'C\'est combien?', romaji: 'Say kom-byahn?' },
        { en: 'Do you have this in another size?', jp: 'Vous avez ça dans une autre taille?', romaji: 'Voo za-vay sa dahn zewn oh-truh tie?' },
        { en: 'Can I try this on?', jp: 'Je peux l\'essayer?', romaji: 'Zhuh puh leh-say-yay?' },
        { en: 'I\'ll take it', jp: 'Je le prends', romaji: 'Zhuh luh prahn' },
        { en: 'Do you accept cards?', jp: 'Vous acceptez les cartes?', romaji: 'Voo zak-sep-tay lay kart?' },
        { en: 'Just looking, thank you', jp: 'Je regarde seulement, merci', romaji: 'Zhuh ruh-gard suhl-mahn, mehr-see' },
        { en: 'Do you have a bag?', jp: 'Vous avez un sac?', romaji: 'Voo za-vay un sak?' },
        { en: 'Tax refund please', jp: 'Détaxe, s\'il vous plaît', romaji: 'Day-taks, seel voo pleh' },
      ],
    },
    {
      category: 'Emergency',
      emoji: '🆘',
      phrases: [
        { en: 'Help!', jp: 'Au secours!', romaji: 'Oh suh-koor!' },
        { en: 'Call the police', jp: 'Appelez la police', romaji: 'A-play la po-lees' },
        { en: 'Call an ambulance', jp: 'Appelez une ambulance', romaji: 'A-play zewn ahm-bew-lahns' },
        { en: 'I need a doctor', jp: 'J\'ai besoin d\'un médecin', romaji: 'Zhay buh-zwahn dun may-duh-san' },
        { en: 'I\'ve lost my passport', jp: 'J\'ai perdu mon passeport', romaji: 'Zhay pehr-dew mohn pas-por' },
        { en: 'Where is the hospital?', jp: 'Où est l\'hôpital?', romaji: 'Oo eh lo-pee-tal?' },
        { en: 'I feel sick', jp: 'Je me sens mal', romaji: 'Zhuh muh sahn mal' },
      ],
    },
  ],
}
