export const TRIP = {
  route: 'Rome → Amalfi → Sicily → Florence → Venice → Milan',
}

export const CITIES = [
  {
    id: 'rome',
    name: 'Rome',
    emoji: '🏛️',
    hotel: 'Hotel de Russie / Prati neighbourhood near Vatican',
    desc: 'The Eternal City — three millennia of history, extraordinary food and a pace that is entirely its own.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    color: '#c0773a',
    highlights: [
      'Colosseum & Roman Forum — 80,000-seat arena and the ancient city centre (€18 combo, book ahead)',
      'Vatican Museums & Sistine Chapel — Michelangelo\'s ceiling, Rafael\'s rooms (€20, book weeks ahead)',
      'St. Peter\'s Basilica & Dome — climb the dome for panoramic views (free entry, €8 dome)',
      'Pantheon — perfectly preserved 2,000-year-old temple, still the finest ancient building on earth (€5)',
      'Borghese Gallery — Bernini sculptures, Caravaggio paintings in a Baroque villa (€15, timed entry)',
      'Trastevere neighbourhood — medieval cobblestones, ivy-covered trattorias, aperitivo bars',
      'Campo de\' Fiori morning market — Rome\'s most atmospheric food and flower market',
      'Piazza Navona & Trevi Fountain — baroque grandeur (toss a coin for good luck)',
    ],
    tips: [
      'Vatican Museums sell out weeks ahead — book online or join a 3-hour early-entry guided tour',
      'Book the Colosseum too — queues without reservation are 2+ hours in peak season',
      'Borghese Gallery has STRICT 2-hour timed slots — arrive on time or lose your booking',
      'Never eat at a restaurant with photos on the menu near major sights. Walk 3 streets away.',
    ],
  },
  {
    id: 'florence',
    name: 'Florence',
    emoji: '🎨',
    hotel: 'Hotel Davanzati / Oltrarno neighbourhood',
    desc: 'The Renaissance cradle — Michelangelo\'s David, Botticelli, extraordinary food and Chianti wine country.',
    image: 'https://images.unsplash.com/photo-1543429257-3eb0b7f5f542?w=800&q=80',
    color: '#c0392b',
    highlights: [
      'Galleria dell\'Accademia — Michelangelo\'s David, 5.17m of perfection (€16, book ahead)',
      'Uffizi Gallery — Botticelli\'s Birth of Venus, da Vinci, Caravaggio. Italy\'s finest art museum (€20, book ahead)',
      'Cathedral Santa Maria del Fiore — Brunelleschi\'s dome, a 15th century engineering miracle (€20 dome)',
      'Ponte Vecchio — medieval bridge of gold and silver shops at sunset',
      'Piazzale Michelangelo — panoramic viewpoint over the entire city, magical at golden hour',
      'Oltrarno neighbourhood — artisan workshops, wine bars, Boboli Gardens, less touristy side of the river',
      'Mercato Centrale — two-floor market with produce below and gourmet restaurants above',
      'Chianti day trip — vineyards, hilltop villages, wine tastings in Tuscany\'s most famous wine region',
    ],
    tips: [
      'Book Accademia and Uffizi weeks in advance — they sell out, especially June–August',
      'Florence is compact — almost everything is walkable from the Duomo',
      'Bistecca alla Fiorentina (T-bone) is the local obsession — order at Buca Mario or Trattoria Sostanza',
      'Avoid May–August crowds by visiting for sunrise at Piazzale Michelangelo',
    ],
  },
  {
    id: 'venice',
    name: 'Venice',
    emoji: '🚤',
    hotel: 'Palazzo Abadessa / Dorsoduro sestiere',
    desc: 'The impossible city — 118 islands, no cars, extraordinary art and food beyond the clichés.',
    image: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800&q=80',
    color: '#4a90d9',
    highlights: [
      'St. Mark\'s Basilica — Byzantine golden mosaics covering every surface (€3, book timeslot)',
      'Doge\'s Palace — the centre of Venetian power for 1,000 years (€25, combo with Basilica)',
      'Rialto Market — Venice\'s fish and produce market, most atmospheric at 7–9am (free)',
      'Grand Canal by vaporetto (Line 1) — the slowest but most spectacular public bus in the world',
      'Peggy Guggenheim Collection — 20th century art in a palazzo on the Grand Canal (€18)',
      'Burano — rainbow-coloured island, 45min by boat, almost no tourists after 3pm',
      'Murano — glass-blowing island, watch free demonstrations at studios',
      'San Giorgio Maggiore bell tower — better views than San Marco, no queue (€8)',
    ],
    tips: [
      'Water taxi from airport is €80; the Alilaguna boat is €15 and runs every 30min',
      'Get a 48hr or 72hr vaporetto pass (€35/€45) — you\'ll use the boats constantly',
      'Cicchetti bars in Dorsoduro and Cannaregio are where Venetians actually eat',
      'Venice floods (acqua alta) October–January — download the Città di Venezia app for alerts',
    ],
  },
  {
    id: 'amalfi',
    name: 'Amalfi Coast',
    emoji: '🌊',
    hotel: 'Villa Treville / Positano, or NH Collection Grand Hotel Convento Amalfi',
    desc: 'Vertiginous cliff villages, turquoise water, fresh seafood and the world\'s most dramatic coastal road.',
    image: 'https://images.unsplash.com/photo-1555989831-9ea1aef88fb3?w=800&q=80',
    color: '#27ae60',
    highlights: [
      'Positano — the iconic pastel cliff town. Most beautiful from the sea (take the boat)',
      'Ravello — hilltop village above the coast, Villa Cimbrone gardens and classical music festival',
      'Path of the Gods hiking trail — 6km clifftop trail with views over Positano (moderate difficulty)',
      'Boat trip to Grotta dello Smeraldo — emerald sea cave, accessible by lift down the cliff',
      'Amalfi town Cathedral — dramatic black-and-white striped 9th century duomo (€3)',
      'Cetara — tiny fishing village, famous for colatura di alici (anchovy sauce), less touristy',
      'Pompeii day trip — the remarkably preserved Roman city buried by Vesuvius in 79AD (€16)',
      'Naples for pizza — take the train (€4) and eat at Pizzeria Di Matteo or Gino Sorbillo',
    ],
    tips: [
      'The SITA bus (€2.50) connects all coast towns but gets extremely crowded in summer',
      'Hire a private boat for a day — splits well between a few couples, worth every cent',
      'Book restaurants with a sea view in advance — the best spots fill up fast',
      'Visit in May, June or September-October. July-August is 45°C and overcrowded.',
    ],
  },
  {
    id: 'milan',
    name: 'Milan',
    emoji: '🛵',
    hotel: 'Hotel Viu Milan / Brera neighbourhood',
    desc: 'Italy\'s most international city — fashion capital, Renaissance art and the best aperitivo culture in the country.',
    image: 'https://images.unsplash.com/photo-1527030280862-64139fba04ca?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'The Last Supper (Cenacolo Vinciano) — Leonardo da Vinci\'s masterpiece, only 25 visitors allowed at once (€15, book months ahead)',
      'Milan Cathedral (Duomo) — 135 spires, 3,400 statues, rooftop terrace with Lombard plain views (€7 rooftop)',
      'Galleria Vittorio Emanuele II — world\'s oldest shopping mall (1877), gold mosaic floors',
      'Brera neighbourhood — art gallery, antique dealers, aperitivo bars, the city\'s most charming area',
      'Navigli canal district — aperitivo at sunset along the canals, Milan\'s most atmospheric evening',
      'Pinacoteca di Brera — Mantegna\'s Dead Christ, Raphael and Caravaggio (€15)',
      'Quadrilatero della Moda — the fashion quadrant: Via Montenapoleone, Via della Spiga, Armani, Prada, Versace flagships',
      'Mercato dell\'Artigianato di Milano — Sunday artisan market in Brera (Sundays)',
    ],
    tips: [
      'The Last Supper MUST be booked months ahead — it sells out for entire seasons',
      'Aperitivo hour is 6–9pm — a drink (€8–12) comes with a free buffet at decent bars',
      'Navigli is lively Tuesday–Saturday evenings, quieter Sundays',
      'Milan fashion week (February, September/October) — book everything far ahead if visiting then',
    ],
  },
  {
    id: 'sicily',
    name: 'Sicily',
    emoji: '🌋',
    hotel: 'Palazzo Brunaccini Palermo / Casa Talia Modica',
    desc: 'Italy\'s wildest island — Greek temples, Arab-Norman architecture, street food and Mount Etna.',
    image: 'https://images.unsplash.com/photo-1604841807718-19c8ea6e1ca1?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Valley of the Temples, Agrigento — seven Greek temples from 500 BC, UNESCO (€12)',
      'Mount Etna — Europe\'s largest active volcano. Cable car to 2,500m then guided hike to summit craters (€30+)',
      'Palermo street food tour — mercato Ballaro, arancini, panelle, pane ca\'meusa. The best street food in Italy.',
      'Taormina — clifftop Greek theatre with Etna backdrop. Most dramatic view in Sicily (€10)',
      'Noto — the finest Baroque town in the world. Walk one street, be overwhelmed. Free.',
      'Cefalù — Norman cathedral with Byzantine mosaics and one of Sicily\'s best beaches',
      'Marsala wine tasting in Marsala town — the fortified wine invented here by accident in 1796',
      'Modica chocolate — pre-Aztec method, no refined sugar, extraordinary flavour. Buy at Antica Dolceria Bonajuto.',
    ],
    tips: [
      'Sicily requires a car — public transport is limited outside Palermo and Catania',
      'The best arancino in the world is at Bar Touring, Palermo — eat standing up at 8am',
      'Book Etna guided hikes in advance — and check the eruption schedule (it\'s often active)',
      'Caponata, pasta alla Norma, cannoli, granita — don\'t leave without eating all four',
    ],
  },
]

export const RESTAURANTS = {
  rome: [
    { name: 'Trattoria Da Enzo al 29', type: 'Roman Trattoria', price: '€20–35', rating: '4.6', area: 'Trastevere', notes: 'Cacio e pepe and carbonara that define the genre. Queue from 12:30pm. Worth every minute.' },
    { name: 'Flavio al Velavevodetto', type: 'Roman Trattoria', price: '€20–35', rating: '4.5', area: 'Testaccio', notes: 'In a cave beneath ancient terracotta mountain. Offal for the brave, rigatoni cacio e pepe for everyone.' },
    { name: 'Roscioli Salumeria', type: 'Deli & Wine Bar', price: '€25–45', rating: '4.7', area: 'Campo de\' Fiori', notes: 'Best carbonara in Rome, best cheese counter in Rome, extraordinary wine list. Book a week ahead.' },
    { name: 'Supplì Roma', type: 'Street Food', price: '€3–8', rating: '4.6', area: 'Trastevere', notes: 'The gold standard Roman supplì (rice ball). Also great pizza al taglio. Eat standing outside.' },
    { name: 'Pizzarium Bonci', type: 'Pizza al Taglio', price: '€5–15', rating: '4.7', area: 'Prati', notes: 'Gabriele Bonci\'s legendary pizza by the slice. Creative toppings, extraordinary dough. Near Vatican.' },
  ],
  florence: [
    { name: 'Trattoria Sostanza', type: 'Florentine Trattoria', price: '€30–50', rating: '4.5', area: 'Santa Maria Novella', notes: 'Since 1869. Famous butter pasta and bistecca Fiorentina. Communal tables, no-nonsense. Book ahead.' },
    { name: 'Buca Mario', type: 'Bistecca Fiorentina', price: '€40–70', rating: '4.4', area: 'Piazza della Repubblica', notes: 'Florence\'s oldest restaurant (1886). The T-bone here is a religious experience. Minimum 1kg.' },
    { name: 'All\'Antico Vinaio', type: 'Schiacciata Sandwiches', price: '€8–12', rating: '4.8', area: 'Via dei Neri', notes: 'World\'s most famous sandwich shop. Queue stretches down the street. Worth it. €7 schiacciata.' },
    { name: 'Osteria dell\'Enoteca', type: 'Modern Tuscan', price: '€50–90', rating: '4.7', area: 'Oltrarno', notes: '1 Michelin star. Elegant but not stuffy. Best wine list in the city. Book 2+ weeks ahead.' },
    { name: 'Mercato Centrale upstairs', type: 'Food Hall', price: '€10–20', rating: '4.4', area: 'San Lorenzo', notes: 'Open-plan food hall above the market. Lampredotto, pasta, pizza, gelato. Great for solo lunch.' },
  ],
  venice: [
    { name: 'Osteria alle Testiere', type: 'Venetian Seafood', price: '€50–80', rating: '4.8', area: 'Castello', notes: 'Only 22 seats. The best seafood restaurant in Venice. Book a month ahead. Menu changes daily.' },
    { name: 'Bacaro Do Mori', type: 'Cicchetti Bar', price: '€2–5/cicchetto', rating: '4.5', area: 'Rialto', notes: 'Venice\'s oldest bacaro (1462). Tiny, standing only, ombre of house wine and cicchetti. This is real Venice.' },
    { name: 'Osteria da Rioba', type: 'Venetian Trattoria', price: '€25–40', rating: '4.6', area: 'Cannaregio', notes: 'Canal-side tables, local crowd, excellent bigoli in salsa and sarde in saor. Book ahead.' },
    { name: 'Cantina Do Spade', type: 'Cicchetti & Wine', price: '€3–8/cicchetto', rating: '4.4', area: 'San Polo', notes: 'Rialto market cicchetti bar since 1488. Baccalà mantecato, polpette, and Soave wine. Go at noon.' },
    { name: 'Trattoria alla Madonna', type: 'Traditional Venetian', price: '€30–50', rating: '4.3', area: 'San Polo', notes: 'The no-nonsense Venetian institution. Fegato alla veneziana, fritto misto, simple and magnificent.' },
  ],
  amalfi: [
    { name: 'La Tagliata', type: 'Hillside Terrace', price: '€30–50', rating: '4.8', area: 'Montepertuso (above Positano)', notes: 'Family-run on a clifftop above Positano. €35 set menu, all homemade. One of the best meals in Italy.' },
    { name: 'Ristorante Il Pirata', type: 'Seafood', price: '€35–60', rating: '4.5', area: 'Praiano', notes: 'Accessed only by boat or 300 steps down a cliff. Worth the descent. Grilled whole fish, views.' },
    { name: 'Lo Guarracino', type: 'Seafood Terrace', price: '€30–50', rating: '4.6', area: 'Positano', notes: 'Lemon trees overhead, sea below. Classic Amalfi seafood. Linguine alle vongole is the dish.' },
    { name: 'Pizzeria Attilio', type: 'Naples-style Pizza', price: '€10–18', rating: '4.7', area: 'Naples (day trip)', notes: 'Naples is 1hr by ferry. The Margherita pizza here is the original and is transcendent.' },
    { name: 'Marina Grande', type: 'Fish on the Dock', price: '€25–40', rating: '4.4', area: 'Amalfi town', notes: 'On the water, excellent frittura di paranza (mixed fried seafood) and fresh mozzarella.' },
  ],
  milan: [
    { name: 'Luini', type: 'Panzerotti (street food)', price: '€3–6', rating: '4.6', area: 'Duomo', notes: 'Milan\'s beloved fried dough pockets with tomato and mozzarella. Queue around the corner but moves fast.' },
    { name: 'Trattoria del Nuovo Macello', type: 'Milanese Trattoria', price: '€25–40', rating: '4.6', area: 'Porta Vittoria', notes: 'Excellent risotto alla Milanese (saffron), cotoletta and braised ossobuco. Local crowd, book ahead.' },
    { name: 'Ratanà', type: 'Modern Milanese', price: '€35–55', rating: '4.7', area: 'Isola', notes: 'The city\'s best modern Milanese cooking. Seasonal, sourced locally. Book 2 weeks ahead.' },
    { name: 'Bar Basso', type: 'Negroni Sbagliato birthplace', price: '€10–15', rating: '4.3', area: 'Porta Venezia', notes: 'This is where the Negroni Sbagliato was invented in 1968. The giant Maxi Negroni is a ritual.' },
    { name: 'Marchesi 1824', type: 'Historic Café-Pastry', price: '€8–20', rating: '4.5', area: 'Brera', notes: 'Milan\'s most beautiful pasticceria. Pralines, croissants, panettone. Worth €18 for a coffee and cake.' },
  ],
  sicily: [
    { name: 'Antica Focacceria San Francesco', type: 'Street Food Institution', price: '€5–15', rating: '4.4', area: 'Palermo', notes: 'Since 1834. Pane ca\'meusa (spleen sandwich), arancine, panelle. The definitive Palermo street food experience.' },
    { name: 'Trattoria Ai Cascinari', type: 'Palermo Trattoria', price: '€15–30', rating: '4.7', area: 'Palermo', notes: 'Pasta alla Norma, caponata, fresh tuna. No-frills, all local. The Sicilian cooking you dream about.' },
    { name: 'Antica Dolceria Bonajuto', type: 'Modica Chocolate', price: '€5–20', rating: '4.7', area: 'Modica', notes: 'Since 1880. The only real Modica chocolate — cold-processed, grainy, extraordinary. Buy everything.' },
    { name: 'Caffè Sicilia', type: 'Historic Café', price: '€5–15', rating: '4.6', area: 'Noto', notes: 'Corrado Assenza\'s legendary café. The best granita in Sicily (try jasmine and almond). International acclaim.' },
    { name: 'Ristorante Il Barocco', type: 'Sicilian Fine Dining', price: '€35–60', rating: '4.6', area: 'Ragusa Ibla', notes: 'In a Baroque palazzo in Ragusa Ibla. Local sourcing, refined Sicilian cooking. Book ahead.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'Trenitalia / Italo Rail', cost: '€15–80/journey', notes: 'High-speed trains between Rome, Florence, Venice, Milan. Book 30+ days ahead for best prices.' },
    { name: 'Rome 48/72hr Tourist Card', cost: '€28/38', notes: 'Covers metro, buses and trams. Useful if staying in central Rome.' },
    { name: 'Venice vaporetto pass', cost: '€35/48hr, €45/72hr', notes: 'Essential — you\'ll be on the water buses constantly. Buy at the docks.' },
    { name: 'Campania Artecard', cost: '€32 (3-day)', notes: 'Covers Pompeii, National Museum Naples, and other Campania sites. Excellent value.' },
  ],
  apps: ['Trenitalia / Italo (train booking)', 'Google Maps (offline maps)', 'TheFork (restaurant reservations)', 'Moovit (local transport)', 'Duolingo Italian (before you go)', 'Musement (tours and skip-the-line tickets)'],
  phrases: [
    { en: 'Hello', jp: 'Ciao / Buongiorno', romaji: 'CHOW / bwon-JOR-no' },
    { en: 'Thank you', jp: 'Grazie', romaji: 'GRA-tsyeh' },
    { en: 'Excuse me', jp: 'Permesso / Scusi', romaji: 'pehr-MEH-so / SKOO-zee' },
    { en: 'The bill please', jp: 'Il conto, per favore', romaji: 'eel KON-to pehr fa-VOR-eh' },
    { en: 'Where is...?', jp: 'Dov\'è...?', romaji: 'do-VEH' },
    { en: 'A glass of wine', jp: 'Un bicchiere di vino', romaji: 'oon bee-KYEH-reh dee VEE-no' },
    { en: 'Delicious!', jp: 'Buonissimo!', romaji: 'bwon-EE-see-mo' },
    { en: 'I don\'t understand', jp: 'Non capisco', romaji: 'non ka-PEE-sko' },
  ],
  phrasesByCategory: [
    {
      category: 'Greetings & Basics',
      emoji: '👋',
      phrases: [
        { en: 'Hello (informal)', jp: 'Ciao', romaji: 'CHOW' },
        { en: 'Good morning', jp: 'Buongiorno', romaji: 'bwon-JOR-no' },
        { en: 'Good evening', jp: 'Buonasera', romaji: 'bwona-SEH-ra' },
        { en: 'Goodbye', jp: 'Arrivederci', romaji: 'ah-ree-veh-DEHR-chee' },
        { en: 'See you later', jp: 'A presto', romaji: 'a PRES-to' },
        { en: 'Thank you very much', jp: 'Grazie mille', romaji: 'GRA-tsyeh MEE-leh' },
        { en: 'You\'re welcome', jp: 'Prego', romaji: 'PREH-go' },
        { en: 'Sorry / Excuse me', jp: 'Scusi / Mi dispiace', romaji: 'SKOO-zee / mee dee-SPYA-cheh' },
        { en: 'I don\'t understand', jp: 'Non capisco', romaji: 'non ka-PEE-sko' },
        { en: 'Please', jp: 'Per favore', romaji: 'pehr fa-VOR-eh' },
        { en: 'Yes', jp: 'Sì', romaji: 'SEE' },
        { en: 'No', jp: 'No', romaji: 'no' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚉',
      phrases: [
        { en: 'Where is the station?', jp: 'Dov\'è la stazione?', romaji: 'do-VEH la sta-TSYOH-neh' },
        { en: 'Where is the toilet?', jp: 'Dov\'è il bagno?', romaji: 'do-VEH eel BA-nyo' },
        { en: 'How much is this?', jp: 'Quanto costa?', romaji: 'KWAN-to KOS-ta' },
        { en: 'I\'m lost', jp: 'Mi sono perso', romaji: 'mee SO-no PEHR-so' },
        { en: 'One ticket please', jp: 'Un biglietto, per favore', romaji: 'oon bee-LYEH-to pehr fa-VOR-eh' },
        { en: 'To the airport', jp: 'All\'aeroporto', romaji: 'al-la-eh-ro-POR-to' },
        { en: 'Is this seat free?', jp: 'È libero questo posto?', romaji: 'eh LEE-beh-ro KWES-to POS-to' },
        { en: 'Stop here please', jp: 'Fermi qui, per favore', romaji: 'FEHR-mee KWEE pehr fa-VOR-eh' },
      ],
    },
    {
      category: 'Food & Dining',
      emoji: '🍝',
      phrases: [
        { en: 'The bill please', jp: 'Il conto, per favore', romaji: 'eel KON-to pehr fa-VOR-eh' },
        { en: 'Delicious!', jp: 'Buonissimo!', romaji: 'bwon-EE-see-mo' },
        { en: 'English menu?', jp: 'Avete un menù in inglese?', romaji: 'a-VEH-teh oon meh-NOO een een-GLEH-zeh' },
        { en: 'Nut allergy', jp: 'Sono allergico alla frutta secca', romaji: 'SO-no al-LEHR-jee-ko AL-la FROO-ta SEK-ka' },
        { en: 'No meat please', jp: 'Senza carne, per favore', romaji: 'SEN-tsa KAR-neh pehr fa-VOR-eh' },
        { en: 'Water please', jp: 'Acqua, per favore', romaji: 'AK-kwa pehr fa-VOR-eh' },
        { en: 'One more please', jp: 'Un altro, per favore', romaji: 'oon AL-tro pehr fa-VOR-eh' },
        { en: 'A table for two', jp: 'Un tavolo per due', romaji: 'oon TA-vo-lo pehr DOO-eh' },
        { en: 'A glass of red wine', jp: 'Un bicchiere di vino rosso', romaji: 'oon bee-KYEH-reh dee VEE-no ROS-so' },
        { en: 'What do you recommend?', jp: 'Cosa consiglia?', romaji: 'KO-sa kon-SEE-lya' },
      ],
    },
    {
      category: 'Shopping',
      emoji: '🛍️',
      phrases: [
        { en: 'How much is this?', jp: 'Quanto costa questo?', romaji: 'KWAN-to KOS-ta KWES-to' },
        { en: 'Do you have a smaller size?', jp: 'Ce l\'avete in una taglia più piccola?', romaji: 'cheh la-VEH-teh een OO-na TA-lya pyoo PEE-ko-la' },
        { en: 'May I try this on?', jp: 'Posso provarlo?', romaji: 'POS-so pro-VAR-lo' },
        { en: 'I\'ll take it', jp: 'Lo prendo', romaji: 'lo PREN-do' },
        { en: 'Do you accept cards?', jp: 'Accettate carte di credito?', romaji: 'a-chet-TA-teh KAR-teh dee KREH-dee-to' },
        { en: 'Just looking, thanks', jp: 'Sto solo guardando, grazie', romaji: 'sto SO-lo gwar-DAN-do GRA-tsyeh' },
        { en: 'Tax refund', jp: 'Rimborso fiscale / Tax free', romaji: 'reem-BOR-so fee-SKA-leh' },
        { en: 'Do you ship internationally?', jp: 'Fate spedizioni internazionali?', romaji: 'FA-teh spe-dee-TSYO-nee een-tehr-na-tsyo-NA-lee' },
      ],
    },
    {
      category: 'Emergency',
      emoji: '🆘',
      phrases: [
        { en: 'Help!', jp: 'Aiuto!', romaji: 'a-YOO-to' },
        { en: 'Call an ambulance', jp: 'Chiamate un\'ambulanza', romaji: 'kya-MA-teh oon am-boo-LAN-tsa' },
        { en: 'Call the police', jp: 'Chiamate la polizia', romaji: 'kya-MA-teh la po-lee-TSEE-a' },
        { en: 'I need a doctor', jp: 'Ho bisogno di un medico', romaji: 'oh bee-ZO-nyo dee oon MEH-dee-ko' },
        { en: 'I\'ve lost my passport', jp: 'Ho perso il passaporto', romaji: 'oh PEHR-so eel pas-sa-POR-to' },
        { en: 'I feel sick', jp: 'Mi sento male', romaji: 'mee SEN-to MA-leh' },
        { en: 'Where is the hospital?', jp: 'Dov\'è l\'ospedale?', romaji: 'do-VEH los-peh-DA-leh' },
      ],
    },
  ],
}
