export const TRIP = {
  route: 'New York → New Orleans → Nashville → San Francisco → National Parks → Los Angeles',
}

export const CITIES = [
  {
    id: 'new-york',
    name: 'New York',
    emoji: '🗽',
    hotel: 'The Ned NoMad / 1 Hotel Brooklyn Bridge — Manhattan or Brooklyn',
    desc: 'The city that never sleeps — five boroughs, eight million people, the world\'s best museums, food from every culture on earth, and an energy that is genuinely unlike anywhere else.',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    color: '#1a4fa0',
    highlights: [
      'Central Park — 843 acres in the middle of Manhattan, essential morning run, Bethesda Fountain, Sheep Meadow',
      'The Metropolitan Museum of Art — one of the world\'s great museums, 2 million objects, entire day minimum (€25 suggested)',
      'High Line — the elevated park built on a disused freight railway, Hudson Yards to Chelsea (free)',
      'Brooklyn Bridge walk — 30-minute walk across the bridge, Manhattan skyline from DUMBO below is the shot',
      'MoMA — the modern art collection that defines modern art (€25)',
      'Smorgasburg — the weekend outdoor food market in Brooklyn/Williamsburg, the best street food in the city',
      'The Vessel & Hudson Yards — Thomas Heatherwick\'s honeycomb structure and the best new public space',
      'Greenwich Village & West Village — the most beautiful streets in Manhattan, independent restaurants and bars',
      'Chelsea Market — converted Nabisco factory, food vendors, the best lunch in Manhattan (€10–25)',
    ],
    tips: [
      'Get an OMNY card (tap-to-pay) for the subway — much easier than MetroCard, works on all subway and buses',
      'NYC is a walking city — Google Maps will route you through unexpected neighbourhoods that become highlights',
      'The bagel-and-lox at Russ & Daughters is non-negotiable — go at 7am on a Saturday',
      'Dinner reservations in NYC need to be made weeks ahead for serious restaurants — use Resy or OpenTable',
      'Tipping is not optional — 20% minimum at sit-down restaurants, $1–2 per drink at bars',
    ],
  },
  {
    id: 'new-orleans',
    name: 'New Orleans',
    emoji: '🎷',
    hotel: 'Hotel Monteleone / Ace Hotel New Orleans — French Quarter or Warehouse District',
    desc: 'The most unique city in America — a Spanish-French-Caribbean-African culture that created jazz, invented cocktails, and cooks the most distinctive food on the continent.',
    image: 'https://images.unsplash.com/photo-1568869924994-ae3ef4dbb64c?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'Frenchmen Street live music — the real New Orleans jazz scene, multiple clubs side by side, walk between them (free entry, buy drinks)',
      'French Quarter & Bourbon Street — the tourist heart, wrought-iron balconies, daiquiri shops, Jackson Square',
      'Commander\'s Palace — the legendary garden district restaurant, the best brunch in the South',
      'Café Du Monde — beignets and café au lait at the French Market since 1862, open 24 hours (€6)',
      'NOMA (New Orleans Museum of Art) — spectacular collection in City Park, beautiful sculpture garden (€15)',
      'Garden District walking tour — antebellum mansions, live oaks draped in Spanish moss, above the flood line',
      'Preservation Hall — the most famous jazz club in America, traditional jazz nightly (€20)',
      'Magazine Street shopping — 6 miles of independent boutiques, antique shops and galleries through Uptown',
    ],
    tips: [
      'New Orleans operates on its own time — dinner before 8pm is early, live music peaks at midnight, morning is quiet',
      'Carry cash — many of the best bars and food stalls are cash-only',
      'The city floods — check the season (hurricane season is June–November)',
      'Uber/Lyft are standard here — driving and parking in the French Quarter is not worth attempting',
      'Mardi Gras (February/March) is extraordinary but book 6+ months ahead and accept that the city is chaos',
    ],
  },
  {
    id: 'nashville',
    name: 'Nashville',
    emoji: '🎸',
    hotel: 'Graduate Nashville / The Joseph — SoBro or East Nashville',
    desc: 'Music City — the world capital of country music, but also a growing food destination with excellent hot chicken, barbecue, craft beer and an unexpected arts scene.',
    image: 'https://images.unsplash.com/photo-1545158535-c3f7168c28b6?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Broadway Honky-Tonks — the neon strip of country music bars, live music 10am–3am, free entry (just buy drinks)',
      'Country Music Hall of Fame — the definitive collection of country music history, extraordinary (€25)',
      'Ryman Auditorium — the Mother Church of Country Music, the most famous venue in American music, tours daily (€25)',
      'Prince\'s Hot Chicken — the original, the legendary, the brutally spicy. Hot chicken that Nashville invented (€12)',
      'The Gulch — Nashville\'s trendiest neighbourhood, street art, rooftop bars, farm-to-table restaurants',
      'East Nashville — the hipster counterpart to Broadway, independent restaurants, cocktail bars, vinyl shops',
      'Andrew Jackson\'s Hermitage — the 7th President\'s plantation house, a confronting but essential history (€20)',
      'Cheekwood Estate & Gardens — 55-acre botanical garden in a Georgian mansion (€20)',
    ],
    tips: [
      'Nashville hot chicken ranges from "Southern" to "Shut the Mouth" — start mild if you\'re unsure, it\'s genuinely hot',
      'The Broadway honky-tonks are free entry — tip the band, buy the drinks, stay for hours',
      'East Nashville is where locals actually eat — far less tourist pressure than downtown',
      'Rent a car for Nashville — the city sprawls and has limited public transport',
    ],
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    emoji: '🌉',
    hotel: 'The Clift Royal Sonesta / Hotel Zoe Fisherman\'s Wharf — Union Square or North Beach',
    desc: 'The most beautiful American city — a compact peninsula of Victorian hills, the Golden Gate, world-class museums, exceptional food and some of the finest restaurants in the world.',
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80',
    color: '#c0392b',
    highlights: [
      'Golden Gate Bridge — walk or cycle across from the Marin Headlands side for the best view (free to walk)',
      'Alcatraz — the island federal penitentiary in the Bay, fascinating audio tour (€43, book ahead)',
      'Ferry Building Farmers Market — the best food market in California, Saturday mornings (free)',
      'Mission District murals & taquerias — the finest tacos in California, Clarion Alley murals (free)',
      'SFMOMA — one of the finest modern art museums in the world, the Diane Arbus collection alone is worth it (€25)',
      'Lombard Street & the hills — the crookedest street, Victorian Painted Ladies, cable car rides ($8)',
      'Chinatown — the oldest in America, dim sum for breakfast at City View or Yank Sing (€20)',
      'Muir Woods — ancient coastal redwoods 30 minutes north, cathedral groves of 1,000-year-old trees (€15)',
    ],
    tips: [
      'The fog is real — June and July are often the foggiest months. September and October are the sunniest',
      'Public transit is excellent — BART, Muni and cable cars cover most of what you\'ll want to see',
      'SF restaurant scene is world-class — Benu, Quince, Atelier Crenn all hold Michelin stars, book months ahead',
      'Micro-climates are extreme — it can be 65°F in the Mission and 50°F at the beach simultaneously, layer up',
      'Renting a car and driving over the Golden Gate to Marin and Napa is the best day trip from the city',
    ],
  },
  {
    id: 'national-parks',
    name: 'National Parks',
    emoji: '🏔️',
    hotel: 'In-park lodges (book 6+ months ahead) / gateway town hotels',
    desc: 'The American West\'s national parks are humbling in scale — Yosemite\'s granite walls, Yellowstone\'s geysers, Zion\'s slot canyons, the Grand Canyon\'s impossible depth.',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    color: '#27ae60',
    highlights: [
      'Grand Canyon (South Rim) — 277 miles long, a mile deep, 6 million years in the making. Nothing prepares you (€35/vehicle)',
      'Yosemite Valley — El Capitan, Half Dome, Bridalveil Fall, Yosemite Falls in one valley. The great American landscape (€35/vehicle)',
      'Zion National Park (Utah) — The Narrows slot canyon hike (wading the Virgin River between 2,000ft walls) is the hike of a lifetime',
      'Yellowstone — the world\'s largest supervolcano, Old Faithful every 90 minutes, Grand Prismatic Spring, bison everywhere',
      'Bryce Canyon — the hoodoos, extraordinary orange spires at dawn, the night sky in Utah is extraordinary',
      'Arches National Park — 2,000+ natural stone arches, Delicate Arch at sunset is the symbol of the American West',
      'Joshua Tree — the surreal high desert where the Mojave meets the Colorado Desert, star-gazing and bouldering',
    ],
    tips: [
      'The America the Beautiful pass (€80) covers all national parks for 12 months — essential if visiting 3+',
      'Book in-park lodges (Yosemite Valley Lodge, Old Faithful Inn) 6–12 months in advance — they sell out completely',
      'Sunrise and sunset are the magic hours — the parks are crowded midday, peaceful at dawn',
      'A hire car is non-negotiable for national parks — public transport within parks is limited',
      'Yosemite requires timed entry reservations in summer (May–Sep) — book online the moment they release',
    ],
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    emoji: '🌴',
    hotel: 'Hotel Bel-Air / Chateau Marmont — West Hollywood or Santa Monica',
    desc: 'The city of perpetual sun — 75 miles of Pacific coastline, world-class museums, the greatest taco culture outside Mexico City, and the movie industry\'s century of mythology.',
    image: 'https://images.unsplash.com/photo-1580655653885-65763b2597d1?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Getty Center — the finest art collection on the West Coast in a stunning Richard Meier building with LA panoramas (free)',
      'Griffith Observatory — city panoramas, the Hollywood Sign hike trailhead, LA from above (free)',
      'Santa Monica & Venice Beach — the Pacific, the pier, Muscle Beach, the boardwalk, sunset over the ocean',
      'LACMA & La Brea Tar Pits — the city\'s great art museum next to Pleistocene fossils being excavated live (€25)',
      'Koreatown & K-BBQ — the finest Korean food outside Seoul, 24-hour barbecue joints, cheap and extraordinary',
      'Silver Lake & Los Feliz — the hipster neighbourhoods, independent coffee, vinyl, bookshops and great restaurants',
      'Nobu Malibu & PCH drive — Pacific Coast Highway north through Malibu, celebrity restaurants on the beach',
      'Hollywood Hills Golden Hour — hike Runyon Canyon or Laurel Canyon at sunset for the classic LA panorama',
    ],
    tips: [
      'LA requires a car — the city is 503 square miles, public transport is improving but still limited for visitors',
      'The traffic is real — check Waze before any drive, add 50% to any journey estimate during rush hour',
      'Taco trucks (loncheras) in East LA and the San Fernando Valley are the real deal — seek them out over restaurants',
      'The beach neighbourhoods (Santa Monica, Venice) feel completely different from Hollywood or downtown — explore all of them',
      'LA restaurant scene is exceptional — Jon & Vinny\'s, Bavel, Gjelina, Night + Market are all unmissable',
    ],
  },
]

export const RESTAURANTS = {
  'new-york': [
    { name: 'Russ & Daughters Café', type: 'Jewish Appetizing & Brunch', price: '$20–40', rating: '4.8', area: 'Lower East Side', notes: 'The greatest bagel-and-lox in the world. Also smoked fish, latkes and excellent egg creams. Get there before 8am on weekends.' },
    { name: 'Di Fara Pizza', type: 'NYC Slice Pizza', price: '$6–30', rating: '4.8', area: 'Midwood, Brooklyn', notes: 'Dom DeMarco\'s legendary pizzeria. Single slices cut with scissors. Worth the long line and the journey to Brooklyn.' },
    { name: 'Gramercy Tavern', type: 'American Fine Dining', price: '$80–150', rating: '4.8', area: 'Flatiron', notes: 'The most reliably great restaurant in New York. Seasonal American, the tavern room (no reservations) is excellent value.' },
    { name: 'Xi\'an Famous Foods', type: 'Xi\'an Street Food', price: '$10–18', rating: '4.7', area: 'Multiple locations', notes: 'Cumin lamb noodles and hand-ripped noodles from Xi\'an, China. Spicy, cheap and addictive. Multiple Manhattan locations.' },
    { name: 'J.G. Melon', type: 'Classic NYC Burger', price: '$25–40', rating: '4.6', area: 'Upper East Side', notes: 'The classic Upper East Side burger joint since 1972. The cheeseburger and cottage fries are as perfect as it gets.' },
  ],
  'new-orleans': [
    { name: 'Commander\'s Palace', type: 'Creole Fine Dining', price: '$60–120', rating: '4.9', area: 'Garden District', notes: 'The most important restaurant in American culinary history. Creole cooking at the highest level. Saturday jazz brunch is spectacular.' },
    { name: 'Dooky Chase\'s Restaurant', type: 'Creole Soul Food', price: '$25–50', rating: '4.7', area: 'Tremé', notes: 'Leah Chase\'s legendary restaurant, the culinary heart of the Civil Rights movement. Red beans and rice, fried chicken, gumbo z\'herbes.' },
    { name: 'Café Du Monde', type: 'Beignets & Café au Lait', price: '$6–12', rating: '4.6', area: 'French Quarter', notes: 'Three beignets and a café au lait at 2am after the music. The defining New Orleans experience. Open 24 hours since 1862.' },
    { name: 'Cochon Butcher', type: 'Louisiana Meat & Sandwiches', price: '$12–25', rating: '4.7', area: 'Warehouse District', notes: 'The best muffuletta in New Orleans and exceptional charcuterie. By the same team as the acclaimed Cochon restaurant.' },
    { name: 'Domilise\'s Po-Boy', type: 'Po-Boy Sandwiches', price: '$12–20', rating: '4.8', area: 'Uptown', notes: 'The definitive po-boy. Shrimp or roast beef, dressed. A tiny house in Uptown. Cash only, no frills, extraordinary sandwich.' },
  ],
  nashville: [
    { name: 'Prince\'s Hot Chicken Shack', type: 'Nashville Hot Chicken', price: '$10–18', rating: '4.7', area: 'Dickerson Road', notes: 'The original. Hot chicken served on white bread with pickles. Order Medium for your first time — it\'s genuinely spicy. No reservations, queue.' },
    { name: 'Husk Nashville', type: 'Southern Fine Dining', price: '$40–80', rating: '4.7', area: 'Rutledge Hill', notes: 'Sean Brock\'s celebration of Southern ingredients. Everything on the menu is grown or raised in the South. Exceptional.' },
    { name: 'Arnold\'s Country Kitchen', type: 'Southern Meat & Three', price: '$12–20', rating: '4.8', area: 'Wedgewood-Houston', notes: 'The definitive Nashville meat-and-three. Choose a meat, choose three vegetable sides. Cornbread. Nothing fancy, everything perfect.' },
    { name: 'Loveless Café', type: 'Southern Breakfast', price: '$15–30', rating: '4.7', area: 'Highway 100', notes: 'Nashville\'s most beloved breakfast institution. The biscuits are exceptional, the country ham is extraordinary. Worth the drive.' },
  ],
  'san-francisco': [
    { name: 'Benu', type: 'Modern California Tasting Menu', price: '$350–500', rating: '4.9', area: 'SoMa', notes: 'Chef Corey Lee\'s three-Michelin-star restaurant. The tasting menu is one of the most creative dining experiences in the world. Book months ahead.' },
    { name: 'Tartine Bakery', type: 'Artisan Bakery', price: '$5–15', rating: '4.8', area: 'Mission District', notes: 'The most influential bakery in America. The country loaf comes out at 5pm, fresh, and sells out in an hour. Queue for it.' },
    { name: 'Swan Oyster Depot', type: 'Seafood Counter', price: '$40–80', rating: '4.9', area: 'Polk Gulch', notes: 'Counter-only seafood institution since 1912. Dungeness crab, Hog Island oysters, clam chowder. 20-person queue, no reservations, cash only.' },
    { name: 'Zuni Café', type: 'California Cuisine', price: '$50–90', rating: '4.8', area: 'Hayes Valley', notes: 'The canonical California restaurant. The roast chicken for two is one of the great dishes in American food. Book a week ahead.' },
    { name: 'Mission taquerias', type: 'California Mission Burritos', price: '$10–18', rating: '4.7', area: 'Mission District', notes: 'El Farolito or La Taqueria (order their tacos, not burritos) — the Mission-style burrito was invented here. Greatest fast food on earth.' },
  ],
  'national-parks': [
    { name: 'The Ahwahnee Dining Room', type: 'Historic Lodge Dining', price: '$40–80', rating: '4.7', area: 'Yosemite Valley', notes: 'Dinner in the 1927 grand lodge dining room with Half Dome views. Formal dress code (jackets preferred). A once-in-a-lifetime setting.' },
    { name: 'Old Faithful Inn Dining Room', type: 'Historic Lodge', price: '$30–60', rating: '4.4', area: 'Yellowstone', notes: 'Dinner in the world\'s largest log structure, built in 1903. Frontier comfort food, bison burgers, and the geyser 300 metres away.' },
  ],
  'los-angeles': [
    { name: 'Mariscos Jalisco', type: 'Mexican Seafood Truck', price: '$8–20', rating: '4.8', area: 'East Los Angeles', notes: 'The legendary East LA taco truck. The dorado taco (fried fish taco in chipotle sauce) is one of the great bites in America. Cash only.' },
    { name: 'Gjelina', type: 'California Cuisine', price: '$30–60', rating: '4.7', area: 'Venice', notes: 'The quintessential Venice restaurant. Farm produce, wood-fired vegetables, great cocktails. Constantly full — book ahead or eat at the bar.' },
    { name: 'Night + Market Song', type: 'Thai', price: '$20–45', rating: '4.8', area: 'Silver Lake', notes: 'The best Thai food in America. Chef Kris Yenbamroong\'s fiery, funky northern Thai menu. Loud, packed and extraordinary.' },
    { name: 'Jon & Vinny\'s', type: 'Italian American', price: '$30–60', rating: '4.8', area: 'Fairfax', notes: 'The most popular restaurant in LA. Italian-American done perfectly — pasta, pizza, salumi. Book months ahead or join the walk-in line.' },
    { name: 'Bestia', type: 'Modern Italian', price: '$50–90', rating: '4.8', area: 'Arts District', notes: 'The restaurant that put the LA Arts District on the map. House-made salumi, pasta, wood-fired meats. Essential reservation, book far ahead.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'America the Beautiful Pass', cost: '$80', notes: 'Annual pass covering all national parks, federal recreational lands and wildlife refuges. Essential if visiting 3+ parks.' },
    { name: 'NYC OMNY / MetroCard', cost: '$33/week unlimited', notes: 'Subway, bus and Staten Island Ferry. Tap-to-pay with phone/card works everywhere now.' },
    { name: 'Amtrak Rail Pass', cost: '$350–700', notes: 'Coast Starlight (Seattle–LA), California Zephyr (Chicago–SF), Crescent (NYC–New Orleans) — long-haul trains are scenic if slow.' },
    { name: 'Hire Car (West)', cost: '$50–100/day', notes: 'Non-negotiable for national parks and LA. Book in advance. One-way rentals are common and relatively affordable in the US.' },
  ],
  apps: ['Google Maps (excellent offline, best for walking)', 'Waze (driving, real-time traffic)', 'Resy / OpenTable (restaurant reservations)', 'Uber / Lyft (rideshare everywhere)', 'Recreation.gov (park permits and campsite booking)', 'GasBuddy (finding cheapest fuel)'],
  phrases: [
    { en: 'Check, please', jp: 'Check, please / Can we get the bill?', romaji: 'Standard everywhere' },
    { en: 'To go / Takeout', jp: 'To go', romaji: 'Standard everywhere' },
    { en: 'On the side', jp: 'Dressing on the side', romaji: 'They will understand' },
    { en: 'How\'s it going?', jp: 'How are you? / How\'s it going?', romaji: 'The standard greeting' },
    { en: 'Awesome / Great', jp: 'Awesome! / Sounds great!', romaji: 'Universal positive response' },
    { en: 'Can I get...?', jp: 'Can I get a... / I\'ll have a...', romaji: 'Standard ordering phrasing' },
    { en: 'To tip', jp: '20% is the standard — 18% minimum', romaji: 'Non-optional in restaurants' },
  ],
  phrasesByCategory: [
    {
      category: 'Dining & Tipping',
      emoji: '🍔',
      phrases: [
        { en: 'Check please', jp: 'Check, please', romaji: 'Standard phrase to ask for the bill' },
        { en: 'Can I get...', jp: 'Can I get a / I\'ll have a...', romaji: 'Standard way to order' },
        { en: 'To go / Takeout', jp: 'To go', romaji: 'Ask for food to take away' },
        { en: 'Dressing on the side', jp: 'Dressing on the side please', romaji: 'Very common US preference' },
        { en: 'How would you like that?', jp: 'How would you like your steak?', romaji: 'Rare / Medium / Well done' },
        { en: '20% tip', jp: '20% of pre-tax total', romaji: 'Non-optional, 18% minimum' },
        { en: 'Cash or card?', jp: 'Do you take cards?', romaji: 'Most places accept cards everywhere' },
        { en: 'Refill', jp: 'Can I get a refill?', romaji: 'Free refills on soft drinks are universal' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚗',
      phrases: [
        { en: 'Gas station', jp: 'Gas station / filling station', romaji: 'Not "petrol station"' },
        { en: 'Freeway / Highway', jp: 'Freeway / Interstate / Highway', romaji: 'Not "motorway"' },
        { en: 'Parking lot', jp: 'Parking lot / garage', romaji: 'Not "car park"' },
        { en: 'Roundabout', jp: 'Traffic circle / Rotary', romaji: 'Not common, yield to those inside' },
        { en: 'Crosswalk', jp: 'Crosswalk', romaji: 'Not "zebra crossing". Cars usually stop.' },
        { en: 'Subway / Metro', jp: 'Subway (NYC) / Metro (DC, LA)', romaji: 'Name varies by city' },
        { en: 'Rideshare', jp: 'Uber / Lyft', romaji: 'Standard in all major cities' },
      ],
    },
    {
      category: 'Shopping',
      emoji: '🛍️',
      phrases: [
        { en: 'Sales tax', jp: 'Tax not included in displayed price', romaji: '6–10% added at checkout, varies by state' },
        { en: 'Just browsing', jp: 'Just looking / just browsing', romaji: 'Response to "can I help you?"' },
        { en: 'Do you have this in...?', jp: 'Do you have this in a different size/colour?', romaji: 'Standard' },
        { en: 'Fitting room', jp: 'Fitting room / dressing room', romaji: 'Not "changing room"' },
        { en: 'Receipt', jp: 'Receipt', romaji: 'Often asked: "do you need a receipt?"' },
      ],
    },
    {
      category: 'Emergencies',
      emoji: '🆘',
      phrases: [
        { en: 'Emergency services', jp: '911', romaji: 'Police, Fire, Ambulance — all on 911' },
        { en: 'I need a doctor', jp: 'I need to see a doctor / I need medical help', romaji: 'US healthcare requires insurance — keep your EHIC/travel insurance card' },
        { en: 'Urgent care', jp: 'Urgent care clinic', romaji: 'Walk-in clinic, faster and cheaper than ER for non-life-threatening issues' },
        { en: 'My insurance details', jp: 'Insurance card', romaji: 'Keep travel insurance details on your phone' },
        { en: 'Lost property', jp: 'Lost and found', romaji: 'Standard term for lost property office' },
      ],
    },
  ],
}
