export const TRIP = {
  route: 'Istanbul → Cappadocia → Ephesus & İzmir → Pamukkale → Antalya & Lycian Coast',
}

export const CITIES = [
  {
    id: 'istanbul',
    name: 'Istanbul',
    emoji: '🕌',
    hotel: 'Pera Palace / Soho House Istanbul — Beyoğlu or Sultanahmet',
    desc: 'The city that straddles two continents — Byzantine churches turned Ottoman mosques, a labyrinthine bazaar, and the Bosphorus dividing Europe from Asia.',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80',
    color: '#c0392b',
    highlights: [
      'Hagia Sophia — 1,500-year-old basilica turned mosque, the greatest building in the world (free to enter)',
      'Topkapı Palace — the nerve centre of the Ottoman Empire, Treasury and Harem unmissable (€15)',
      'Grand Bazaar — 4,000 shops, one of the world\'s oldest and largest markets (free to enter)',
      'Spice Bazaar (Mısır Çarşısı) — aromatic warren of spices, dried fruit, Turkish delight and saffron',
      'Blue Mosque (Sultan Ahmed) — six minarets, extraordinary blue İznik tile interior (free, timed entry)',
      'Bosphorus cruise — the essential Istanbul experience, Europe on one shore, Asia on the other',
      'Chora Church (Kariye) — the finest Byzantine mosaics and frescoes in existence (€5)',
      'Beyoğlu & İstiklal Street — the modern city, bars, restaurants, art galleries and crowds',
      'Balık-ekmek (fish sandwich) at Eminönü — eat it on the Galata Bridge like a local (€2)',
    ],
    tips: [
      'Get an İstanbulkart travel card — works on metro, tram, ferry and bus, far cheaper than single tickets',
      'The Grand Bazaar is overwhelming — go with a list, ignore hard-sell carpet shops, haggle everywhere else',
      'Cross to the Asian side (Kadıköy) for lunch — better food, far fewer tourists, authentic neighbourhood feel',
      'Carry cash — many small restaurants, simitçi and market stalls don\'t accept cards',
      'The Museum Pass Istanbul (€30) covers Topkapı, Archaeology Museum, Turkish & Islamic Arts — worth it',
    ],
  },
  {
    id: 'cappadocia',
    name: 'Cappadocia',
    emoji: '🎈',
    hotel: 'Argos in Cappadocia / Museum Hotel — Uçhisar or Göreme cave hotel',
    desc: 'A volcanic moonscape of fairy chimneys, underground cities and cave-cut churches — made magical by hundreds of hot air balloons at sunrise.',
    image: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Hot air balloon flight at sunrise — the Cappadocia experience, 1 hour over the valleys (€150–250)',
      'Göreme Open Air Museum — UNESCO cave churches with Byzantine frescoes dating from the 10th century (€15)',
      'Rose Valley & Red Valley hike — the best walking in Cappadocia, fairy chimneys and cave dwellings (free)',
      'Derinkuyu Underground City — 18 levels deep, carved by early Christians, extraordinary engineering (€10)',
      'Uçhisar Castle — the highest point in Cappadocia, panoramic views of the valleys at sunset (€5)',
      'Avanos pottery — master potters using Kızılırmak river clay by hand, as they have for 5,000 years',
      'Ihlara Valley — 14km gorge walk with cave churches, the Melendiz river below (€3)',
      'Kaymakli Underground City — alternative to Derinkuyu, slightly less crowded (€10)',
    ],
    tips: [
      'Book the balloon flight at least 2 weeks ahead in high season — slots fill fast and weather cancels often',
      'Stay in a cave hotel — it\'s not a gimmick, they\'re naturally cool in summer and warm in winter',
      'Rent a scooter or ATV to explore the valleys independently — far better than tours (€25–40/day)',
      'The valleys look completely different at different times of day — Rose Valley glows at sunset, go twice',
      'Fly Cappadocia, don\'t bus — the overnight bus from Istanbul is 11 hours, flights are 90 minutes and cheap',
    ],
  },
  {
    id: 'ephesus',
    name: 'Ephesus & İzmir',
    emoji: '🏛️',
    hotel: 'Mövenpick Hotel Izmir / Kordon waterfront district',
    desc: 'The best-preserved ancient city in the eastern Mediterranean — marble streets where Mark Antony and Cleopatra once walked, with Turkey\'s most beautiful coastal city nearby.',
    image: 'https://images.unsplash.com/photo-1589561253898-768105ca91a8?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'Ephesus Archaeological Site — the Library of Celsus, the Great Theatre (25,000 seats), the marble Sacred Way (€20)',
      'House of the Virgin Mary — hilltop chapel where Mary is said to have lived her final years (€15)',
      'Ephesus Museum in Selçuk — extraordinary statues of Artemis, terrace house frescoes (€15)',
      'İzmir Kordon promenade — Turkey\'s finest seaside boulevard, morning coffee and evening fish restaurants',
      'Kemeraltı Bazaar (İzmir) — the best bazaar experience outside Istanbul, less touristic and more authentic',
      'Şirince village — hilltop wine village above Selçuk, local fruit wines, old Greek stone houses',
      'İzmir Archaeological Museum — Hellenistic and Roman sculpture of exceptional quality (€5)',
      'Birgi Ottoman village — a perfectly preserved 18th century Ottoman town, largely unknown to tourists',
    ],
    tips: [
      'Visit Ephesus at opening (8am) or late afternoon — cruise ships unload from 10am–3pm making it unbearable',
      'The Terrace Houses at Ephesus cost extra (€15) but are the most spectacular part — don\'t skip them',
      'İzmir is one of Turkey\'s most secular and social cities — coffee culture, craft beer, excellent food scene',
      'Selçuk (the town for Ephesus) is walkable and full of good restaurants — stay here rather than İzmir if time is tight',
    ],
  },
  {
    id: 'pamukkale',
    name: 'Pamukkale',
    emoji: '♨️',
    hotel: 'Doga Thermal Health & Spa / Karahayit village hotels',
    desc: 'A cliff of brilliant white calcium terraces cascading with thermal pools, topped by the ruins of ancient Hierapolis — one of Turkey\'s most surreal landscapes.',
    image: 'https://images.unsplash.com/photo-1527853787696-f7be74f2e39a?w=800&q=80',
    color: '#2980b9',
    highlights: [
      'Cotton Castle terraces — the calcium carbonate pools, shoes-off wading on the white cliff (€15)',
      'Hierapolis ancient city — built by the Romans over the thermal springs, colonnaded street and necropolis',
      'Antique Pool (Cleopatra\'s Pool) — swim in an ancient Roman pool with submerged Roman columns (€25)',
      'Hierapolis Archaeological Museum — extraordinary Roman sculpture in the restored Baths complex (included with entry)',
      'Laodikeia ancient city — lesser-visited Roman city 6km away, recently excavated (€5)',
      'Karahayit Red Springs — the thermal pools that run red from iron-rich minerals, 5km from Pamukkale',
      'Afyon detour — the nearby city famous for cream (kaymak), Turkish delight and opium poppies',
    ],
    tips: [
      'The pools are best in the morning before tour buses arrive — check in the previous afternoon too',
      'The white terraces are fragile — only walk in designated areas, no shoes (bring water shoes)',
      'Stay overnight to see the terraces at sunset and have them nearly to yourself in the morning',
      'The thermal hotels in Karahayit are genuinely therapeutic — book one with a proper pool',
    ],
  },
  {
    id: 'antalya',
    name: 'Antalya & Lycian Coast',
    emoji: '🌊',
    hotel: 'Marmara Antalya / Kalkan boutique hotels for the coast',
    desc: 'Turkey\'s turquoise coast — Roman harbours, spectacular mountain gorges, Lycian rock tombs cut into cliffsides, and some of the clearest water in the Mediterranean.',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
    color: '#27ae60',
    highlights: [
      'Antalya Old Town (Kaleiçi) — Roman harbour, Hadrian\'s Gate, Ottoman houses turned boutique hotels',
      'Düden Waterfalls — waterfalls plunging directly into the Mediterranean (lower falls, free)',
      'Aspendos Theatre — the best-preserved Roman theatre in the world, still used for opera (€8)',
      'Perge ancient city — massive Roman city with colonnaded street, baths and stadium (€10)',
      'Ölüdeniz Blue Lagoon — the most photographed beach in Turkey, paragliding capital (day trip from coast)',
      'Kaş & Kalkan — the most stylish villages on the Turquoise Coast, yachts, boutique shopping',
      'Kekova underwater ruins — snorkelling over a sunken Roman city in crystal-clear water (boat tour €35)',
      'Saklikent Gorge — 18km narrow gorge, wading through icy meltwater between thousand-foot walls (€5)',
    ],
    tips: [
      'Hire a car for the Lycian Coast — public transport is slow and infrequent between the villages',
      'The Lycian Way hiking trail runs 540km along the coast — even 2–3 days of sections are spectacular',
      'Boat trips from Kaş or Kalkan to the sunken city of Kekova are one of Turkey\'s great experiences',
      'July–August is very hot (40°C+) — May/June and September/October are the best months for the coast',
    ],
  },
  {
    id: 'trabzon',
    name: 'Trabzon & Black Sea',
    emoji: '🌿',
    hotel: 'Zorlu Grand Hotel Trabzon / Uzungöl village lodges',
    desc: 'The wild, lush Black Sea coast — Byzantine monasteries clinging to cliffsides, alpine meadows, hazelnut orchards and a food culture entirely unlike the rest of Turkey.',
    image: 'https://images.unsplash.com/photo-1589555720536-4e17c6aebfe5?w=800&q=80',
    color: '#27ae60',
    highlights: [
      'Sümela Monastery — a 4th century Byzantine monastery carved into a vertical cliff face, 1,200m up (€15)',
      'Uzungöl Lake — an alpine lake village in the tea and hazelnut highlands above Trabzon (day trip)',
      'Trabzon Bazaar — the most authentic market in the Black Sea region, local cheeses, anchovies, corn bread',
      'Atatürk Köşkü — the presidential villa where Atatürk stayed, set in lush park gardens (€3)',
      'Zigana Pass — the mountain crossing into the highlands, dramatic highland scenery year-round',
      'Rize tea terraces — Turkey produces 75% of its own tea here, the rolling green hills are extraordinary',
      'Ayasofya Mosque (Trabzon) — 13th century Byzantine church, fine frescoes inside (free)',
    ],
    tips: [
      'Trabzon\'s signature dish is kuymak — a rich Black Sea fondue made with cornmeal and butter',
      'Fly into Trabzon — the coastal road from Ankara or Istanbul is scenic but very slow',
      'Sümela Monastery has limited daily visitor numbers — book online in advance in summer',
      'The Black Sea region is green and misty, not the Mediterranean — bring a layer even in summer',
    ],
  },
]

export const RESTAURANTS = {
  istanbul: [
    { name: 'Karaköy Lokantası', type: 'Traditional Turkish', price: '₺200–400', rating: '4.7', area: 'Karaköy', notes: 'The finest traditional lokanta in Istanbul. Daily dishes of slow-cooked vegetables, lamb stews, stuffed aubergines. Queue at lunch.' },
    { name: 'Çiya Sofrası', type: 'Anatolian Regional Cooking', price: '₺150–300', rating: '4.8', area: 'Kadıköy (Asian side)', notes: 'Chef Musa Dağdeviren\'s legendary restaurant. Regional dishes from across Anatolia that no one else serves. Cross the Bosphorus for this.' },
    { name: 'Mikla', type: 'Modern Turkish Fine Dining', price: '₺600–1200', rating: '4.6', area: 'Beyoğlu', notes: 'Rooftop restaurant with Bosphorus views. Chef Mehmet Gürs re-imagines Anatolian food with precision. Book 2+ weeks ahead.' },
    { name: 'Kaşıbeyaz', type: 'Bosphorus Fish Restaurant', price: '₺300–600', rating: '4.5', area: 'Bebek, Bosphorus', notes: 'Fish restaurant on the Bosphorus shore. The best lakerda, grilled sea bass and raki to watch the tankers pass.' },
    { name: 'Simit Sarayı', type: 'Turkish Breakfast & Simit', price: '₺30–80', rating: '4.2', area: 'Multiple locations', notes: 'The place for a classic Turkish breakfast — simit (sesame bread ring), beyaz peynir, olives, tea. Very cheap, everywhere.' },
  ],
  cappadocia: [
    { name: 'Seten Restaurant', type: 'Cappadocian & Anatolian', price: '₺200–450', rating: '4.7', area: 'Uçhisar', notes: 'The best dining in Cappadocia. Exceptional testi kebab (sealed clay pot), local wines and a terrace with valley views.' },
    { name: 'Topdeck Cave Restaurant', type: 'Cave Dining', price: '₺150–350', rating: '4.6', area: 'Göreme', notes: 'An actual carved cave restaurant. Local manti (Turkish dumplings), gözleme and Cappadocian wine. Atmospheric at night.' },
    { name: 'Ziggy\'s Restaurant', type: 'Modern Anatolian', price: '₺250–500', rating: '4.5', area: 'Urgup', notes: 'One of the most creative restaurants in the region. Anatolian ingredients with a contemporary approach, excellent wine list.' },
  ],
  ephesus: [
    { name: 'Ejder Restaurant', type: 'Aegean Meyhane', price: '₺150–350', rating: '4.7', area: 'Selçuk', notes: 'A proper meyhane (Turkish taverna) in Selçuk. Cold meze, grilled octopus, local wine. The place to eat before or after Ephesus.' },
    { name: 'Kordon Balık Pişiricisi', type: 'Fresh Fish', price: '₺200–400', rating: '4.5', area: 'İzmir Kordon', notes: 'Waterfront fish on the Kordon. The best fresh catch in İzmir — order whatever they landed that morning.' },
    { name: 'Kemeraltı Köftecisi', type: 'Köfte & Local Lunch', price: '₺80–150', rating: '4.6', area: 'İzmir Kemeraltı', notes: 'Hidden in the bazaar quarter. The köfte here are perfectly spiced, eaten with piyaz (white bean salad). Cash only.' },
  ],
  pamukkale: [
    { name: 'Mustafa Restaurant', type: 'Traditional Turkish', price: '₺100–200', rating: '4.4', area: 'Pamukkale village', notes: 'The most reliable in the village. Good gözleme, pide and grilled meats. Ask for the local yoghurt with wild honey.' },
  ],
  antalya: [
    { name: 'Vanilla Restaurant', type: 'Modern Mediterranean', price: '₺200–450', rating: '4.6', area: 'Kaleiçi', notes: 'The best modern cooking in Antalya\'s old town. Mediterranean seafood with Turkish touches. Beautiful courtyard setting.' },
    { name: 'Balıkçı Sabahattin', type: 'Traditional Fish', price: '₺150–350', rating: '4.7', area: 'Antalya Old Town', notes: 'In a converted Ottoman house. Fresh fish, cold meze and raki. One of the great traditional fish restaurants on the coast.' },
    { name: 'Köşk Restaurant', type: 'Ottoman Cuisine', price: '₺150–300', rating: '4.5', area: 'Kalkan', notes: 'Kalkan rooftop with sea views. Excellent slow-cooked lamb, fresh salads and cold Efes beer on the Turquoise Coast.' },
  ],
  trabzon: [
    { name: 'Cemilusta Restaurant', type: 'Black Sea Cuisine', price: '₺100–250', rating: '4.6', area: 'Trabzon', notes: 'The go-to for Black Sea cooking. Hamsi (anchovy) every way, kuymak (cornmeal fondue), corn bread and tea. A Trabzon institution.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'Museum Pass Turkey', cost: '€55', notes: 'Covers 300+ museums and archaeological sites including Topkapı, Ephesus and Hierapolis. Valid 15 days.' },
    { name: 'İstanbulkart', cost: '₺100 deposit', notes: 'Rechargeable transit card for metro, tram, ferry and bus in Istanbul. Buy at any metro station.' },
    { name: 'Turkish Airlines Domestic', cost: '₺500–1500', notes: 'Turkey is big — fly between cities. Istanbul to Cappadocia (Nevşehir/Kayseri) is 90 min. Book in advance.' },
    { name: 'Balloon Flight Cappadocia', cost: '€150–250', notes: 'Book directly with Butterfly Balloons or Royal Balloon. Avoid third-party resellers. 1 hour, sunrise.' },
  ],
  apps: ['Google Maps (Turkey offline is excellent)', 'BiTaksi (Turkish Uber equivalent)', 'YemekSepeti (food delivery)', 'Obilet (bus and domestic train tickets)', 'Currency converter (TRY fluctuates rapidly)'],
  phrases: [
    { en: 'Hello', jp: 'Merhaba', romaji: 'mer-HA-ba' },
    { en: 'Thank you', jp: 'Teşekkür ederim', romaji: 'te-shek-KUR eh-deh-RIM' },
    { en: 'Excuse me', jp: 'Pardon / Afedersiniz', romaji: 'par-DON / ah-feh-der-SEE-neez' },
    { en: 'The bill please', jp: 'Hesap, lütfen', romaji: 'heh-SAP, lut-FEN' },
    { en: 'Where is...?', jp: '... nerede?', romaji: '... neh-REH-deh' },
    { en: 'How much?', jp: 'Ne kadar?', romaji: 'neh KA-dar' },
    { en: 'Delicious!', jp: 'Çok lezzetli!', romaji: 'chok lez-ZET-lee' },
    { en: 'Cheers!', jp: 'Şerefe!', romaji: 'sheh-REH-feh' },
  ],
  phrasesByCategory: [
    {
      category: 'Greetings & Basics',
      emoji: '👋',
      phrases: [
        { en: 'Hello', jp: 'Merhaba', romaji: 'mer-HA-ba' },
        { en: 'Good morning', jp: 'Günaydın', romaji: 'gun-ay-DUN' },
        { en: 'Good evening', jp: 'İyi akşamlar', romaji: 'ee-YEE ak-SHAM-lar' },
        { en: 'Goodbye', jp: 'Hoşça kal / Güle güle', romaji: 'hosh-CHA kal / gu-LEH gu-LEH' },
        { en: 'Thank you', jp: 'Teşekkür ederim', romaji: 'te-shek-KUR eh-deh-RIM' },
        { en: 'Thank you (informal)', jp: 'Sağ ol', romaji: 'SAH ol' },
        { en: 'You\'re welcome', jp: 'Rica ederim', romaji: 'REE-ja eh-deh-RIM' },
        { en: 'Sorry / Excuse me', jp: 'Özür dilerim / Affedersiniz', romaji: 'oh-ZUR dee-leh-RIM / af-feh-der-SEE-neez' },
        { en: 'Yes / No', jp: 'Evet / Hayır', romaji: 'eh-VET / ha-YUR' },
        { en: 'I don\'t understand', jp: 'Anlamadım', romaji: 'an-la-ma-DUM' },
        { en: 'Do you speak English?', jp: 'İngilizce biliyor musunuz?', romaji: 'in-gee-LEEZ-jeh bee-lee-YOR moo-soo-NOOZ' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚌',
      phrases: [
        { en: 'Where is...?', jp: '... nerede?', romaji: '... neh-REH-deh' },
        { en: 'How much is this?', jp: 'Bu ne kadar?', romaji: 'boo neh KA-dar' },
        { en: 'One ticket please', jp: 'Bir bilet, lütfen', romaji: 'BEER bee-LET, lut-FEN' },
        { en: 'Where is the toilet?', jp: 'Tuvalet nerede?', romaji: 'too-VA-let neh-REH-deh' },
        { en: 'Stop here please', jp: 'Burada dur, lütfen', romaji: 'boo-RA-da DOOR, lut-FEN' },
        { en: 'The airport', jp: 'Havalimanı', romaji: 'ha-va-lee-ma-NUH' },
        { en: 'Left / Right', jp: 'Sol / Sağ', romaji: 'SOL / SAH' },
      ],
    },
    {
      category: 'Food & Dining',
      emoji: '🍢',
      phrases: [
        { en: 'The bill please', jp: 'Hesap, lütfen', romaji: 'heh-SAP, lut-FEN' },
        { en: 'Delicious!', jp: 'Çok lezzetli!', romaji: 'chok lez-ZET-lee' },
        { en: 'Cheers!', jp: 'Şerefe!', romaji: 'sheh-REH-feh' },
        { en: 'Water please', jp: 'Su, lütfen', romaji: 'SOO, lut-FEN' },
        { en: 'No meat please', jp: 'Etsiz, lütfen', romaji: 'et-SEEZ, lut-FEN' },
        { en: 'A table for two', jp: 'İki kişilik masa', romaji: 'ee-KEE kee-SHEE-leek MA-sa' },
        { en: 'Do you have a menu?', jp: 'Menünüz var mı?', romaji: 'meh-nu-nuz VAR muh' },
        { en: 'What do you recommend?', jp: 'Ne tavsiye edersiniz?', romaji: 'neh tav-see-YEH eh-der-SEE-neez' },
      ],
    },
    {
      category: 'Shopping',
      emoji: '🛍️',
      phrases: [
        { en: 'How much is this?', jp: 'Bu kaç lira?', romaji: 'boo KACH lee-RA' },
        { en: 'Too expensive', jp: 'Çok pahalı', romaji: 'chok pa-ha-LUH' },
        { en: 'Can you lower the price?', jp: 'İndirim yapabilir misiniz?', romaji: 'in-dee-REEM ya-pa-bee-LEER mee-see-NEEZ' },
        { en: 'I\'ll take it', jp: 'Alıyorum', romaji: 'a-LUH-yo-room' },
        { en: 'Just looking, thanks', jp: 'Sadece bakıyorum', romaji: 'sa-deh-JEH ba-KUH-yo-room' },
        { en: 'Do you accept cards?', jp: 'Kredi kartı kabul ediyor musunuz?', romaji: 'kreh-DEE kar-TUH ka-BOOL eh-dee-YOR moo-soo-NOOZ' },
      ],
    },
    {
      category: 'Emergency',
      emoji: '🆘',
      phrases: [
        { en: 'Help!', jp: 'İmdat!', romaji: 'im-DAT' },
        { en: 'Call an ambulance', jp: 'Ambulans çağırın', romaji: 'am-boo-LANS cha-UH-run' },
        { en: 'Call the police', jp: 'Polisi çağırın', romaji: 'po-LEE-see cha-UH-run' },
        { en: 'I need a doctor', jp: 'Doktora ihtiyacım var', romaji: 'dok-TO-ra ih-tee-ya-JUM var' },
        { en: 'I\'ve lost my passport', jp: 'Pasaportumu kaybettim', romaji: 'pa-sa-por-TOO-moo kai-BET-teem' },
        { en: 'Where is the hospital?', jp: 'Hastane nerede?', romaji: 'has-TA-neh neh-REH-deh' },
      ],
    },
  ],
}
