export const TRIP = {
  route: 'Marrakech → Fez → Chefchaouen → Essaouira → Merzouga (Sahara)',
}

export const CITIES = [
  {
    id: 'marrakech',
    name: 'Marrakech',
    emoji: '🌹',
    hotel: 'La Mamounia / Riad Yasmine — medina riad or Palmeraie resort',
    desc: 'The Red City — a medina of pink-ochre walls, labyrinthine souks, Djemaa el-Fna\'s nightly circus, and palatial riads hidden behind unmarked doorways.',
    image: 'https://images.unsplash.com/photo-1489493585363-d69421e0edd3?w=800&q=80',
    color: '#c0392b',
    highlights: [
      'Djemaa el-Fna — the extraordinary main square, snake charmers and storytellers by day, food stalls by night (free)',
      'Koutoubia Mosque — the 12th century minaret that set the template for all minarets that followed (exterior only)',
      'Bahia Palace — a 19th century vizier\'s palace of incredible tilework and carved cedar ceilings (€4)',
      'Saadian Tombs — the royal necropolis sealed for 200 years, rediscovered in 1917, extraordinary mosaic (€3)',
      'Majorelle Garden — the electric-blue garden created by Yves Saint Laurent, now home to the Berber Museum (€20)',
      'Souks of the medina — the world\'s finest craft market: leather, spices, lanterns, babouche slippers, textiles',
      'Medersa Ben Youssef — a 16th century Quranic school, the most beautiful Islamic architecture in Morocco (€5)',
      'Hammam el-Basha — an authentic local hammam in the medina, the full scrub and steam ritual (€15–30)',
    ],
    tips: [
      'Stay in a riad — they look like blank walls from outside, inside is paradise: courtyard, pool, rooftop terrace',
      'The souks are designed to disorient — bring a compass or trust GPS. Getting lost is half the fun',
      'Official guides (€20/half day) are worth it for the first visit — they explain context and stop persistent hawkers',
      'Djemaa el-Fna food stalls in the evening are a spectacle but pick busy stalls (fresh turn-over) and agree price first',
      'Carry small change for every interaction — tipping is the social fabric of Marrakech',
    ],
  },
  {
    id: 'fez',
    name: 'Fez',
    emoji: '🏰',
    hotel: 'Riad Fès / Palais Faraj — old medina riad',
    desc: 'The world\'s largest living medieval city — a UNESCO labyrinth of 9,000 streets, the world\'s oldest university, and the extraordinary Chouara tanneries.',
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'Chouara Tanneries — the medieval leather works, honeycombed dye pits of colour, best viewed from leather shop terraces (free with purchase)',
      'Bou Inania Medersa — 14th century Quranic school, the finest example of Marinid architecture (€4)',
      'Al-Qarawiyyin University & Mosque — founded in 859 AD, the oldest continuously operating university in the world (exterior)',
      'Fès el-Bali medina — 9,500 streets, 2 miles of covered market, 300 mosques inside the walls (free, get lost)',
      'Fondouks (caravanserais) — the medieval merchant hostels turned workshops, artisans still at work inside',
      'Mellah (Jewish Quarter) — the old Jewish quarter with its distinctive covered balconies and the beautiful Ibn Danan Synagogue',
      'Merenid Tombs hilltop — 14th century royal tombs above the city, the best panoramic view of Fez at sunset (free)',
      'Dar Batha Museum — Moroccan craft collections in a 19th century palace (€3)',
    ],
    tips: [
      'Fez medina is bigger and more disorienting than Marrakech — hire a guide for day one (€25)',
      'The tanneries smell intensely — leather shops give you mint to hold to your nose while you look',
      'The medina gates (Bab Bou Jeloud) is the natural starting point for any exploration',
      'Fez is more conservative than Marrakech — dress modestly in the medina, especially near mosques',
      'The new city (Ville Nouvelle) has the best cafés and restaurants for evenings outside the medina',
    ],
  },
  {
    id: 'chefchaouen',
    name: 'Chefchaouen',
    emoji: '💙',
    hotel: 'Hotel Lina Ryad & Spa / medina riad',
    desc: 'The Blue Pearl — a mountain town where every street, wall and staircase is painted in shades of indigo and cerulean, founded by Moorish refugees from Andalusia.',
    image: 'https://images.unsplash.com/photo-1548265083-b15a0dc8c7b6?w=800&q=80',
    color: '#2980b9',
    highlights: [
      'The medina — walk every single street, every alley is more beautiful than the last, purely for wandering (free)',
      'Place Uta el-Hammam — the main square, the old kasbah, cafés and the town\'s social centre',
      'Kasbah Museum — the central fortress turned museum, rooftop views over the blue city (€2)',
      'Ras el-Maa waterfall — the natural spring that feeds the city, locals do laundry here, extraordinary scene',
      'Spanish Mosque hike — 30-minute climb above the city for sunset panoramas over the blue rooftops (free)',
      'Rif Mountain walks — the surrounding cedar forests and Rif mountain trails are spectacular',
      'Artisan shopping — handwoven rugs, djellabas, goat leather goods at prices far lower than Marrakech',
    ],
    tips: [
      'Stay at least two nights — Chefchaouen deserves a slow wander, not a rushed day trip from Fez',
      'The blue is most vivid in the morning light before 9am — bring a camera and wake up early',
      'Chefchaouen is small and very walkable — you don\'t need a guide here',
      'The surrounding Rif mountains are known for cannabis cultivation — tourists are sometimes approached, politely decline',
      'Kefta tagine and goat\'s cheese are the local specialities — eat them here',
    ],
  },
  {
    id: 'essaouira',
    name: 'Essaouira',
    emoji: '🌊',
    hotel: 'L\'Heure Bleue Palais / Riad Mimouna — medina or rampart-view',
    desc: 'The Windy City — a blue-and-white fortified Atlantic port beloved by Jimi Hendrix, Orson Welles, and the world\'s wind and kite surfers.',
    image: 'https://images.unsplash.com/photo-1539020140153-e479b8e2c9f8?w=800&q=80',
    color: '#2980b9',
    highlights: [
      'Ramparts & Scala de la Ville — the Portuguese sea bastions with cannons pointing at the Atlantic (free)',
      'Medina of Essaouira — UNESCO whitewashed labyrinth, far quieter and less pressurised than Marrakech',
      'Port de Pêche — the working fishing harbour, blue boats, fresh catches, seagulls and salt air',
      'Gnaoua World Music Festival — if timing allows, one of Africa\'s great music festivals (June, free)',
      'Thuya wood workshops — Essaouira\'s craftsmen work the fragrant local thuya root into extraordinary marquetry',
      'Beach & windsurfing — 10km of Atlantic beach, ranked among the world\'s top windsurfing and kitesurfing spots',
      'Fish grills at the port — choose your fish from the stall, they grill it to order (€8–15, cash only)',
    ],
    tips: [
      'The Alizée wind is constant and strong — bring a layer even in summer',
      'Essaouira is far more relaxed than Marrakech — far less hustling, people leave you alone',
      'Hire a bicycle to explore the beach and dunes south of town (€8/day)',
      'Argan oil is the local product — buy it direct from a women\'s cooperative for authenticity and fair price',
    ],
  },
  {
    id: 'merzouga',
    name: 'Merzouga & Sahara',
    emoji: '🐪',
    hotel: 'Kasbah Tombouctou / Luxury desert camp — Erg Chebbi dunes',
    desc: 'The Erg Chebbi — Morocco\'s great sand sea, 25km of dunes rising 160m above the Sahara floor, turning blood orange at sunset and gold at sunrise.',
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Erg Chebbi dunes at sunrise — climb the main dune for the sunrise over an infinite sea of sand (free)',
      'Camel trek into the desert — the essential experience, 1–2 hour trek to a camp among the dunes (€30–50)',
      'Overnight desert camp — sleeping under the Saharan stars, traditional music around the campfire',
      'Merzouga town — the Berber village at the edge of the dunes, 4WD tours, fossil shops',
      'Fossil Valley — 350-million-year-old marine fossils in the rocks around Merzouga (day tour)',
      'Dayet Srij Lake — flamingos and migratory birds in the shallow salt lake next to the dunes (seasonal)',
      'Gnaoua musicians — Merzouga has a small community of traditional Gnaoua musicians who perform locally',
    ],
    tips: [
      'The luxury desert camps are genuinely special — book a permanent tented camp with en-suite bathroom (€150–300/night)',
      'March–May and October–November are ideal — summer temperatures exceed 45°C',
      'The drive from Fez through the Atlas Mountains (Midelt, Ziz Valley) is as spectacular as the dunes',
      'Bring a headtorch, lip balm and face scarf — the sand gets everywhere and nights are cold even in spring',
      'Do NOT let anyone guide you to a "better" camp than your booking — this is the most common scam',
    ],
  },
  {
    id: 'casablanca',
    name: 'Casablanca',
    emoji: '🕌',
    hotel: 'Four Seasons Casablanca / Kenzi Tower — Corniche or city centre',
    desc: 'Morocco\'s largest city and economic capital — a modern Art Déco city with the world\'s third-largest mosque, a vibrant food scene and an energetic port.',
    image: 'https://images.unsplash.com/photo-1541484778-a94c07f56d86?w=800&q=80',
    color: '#27ae60',
    highlights: [
      'Hassan II Mosque — the world\'s third-largest mosque, built partly over the Atlantic, guided tours non-Muslims (€15)',
      'Art Déco architecture — the finest collection of 1930s French Art Déco buildings in the world, walking tour (free)',
      'La Corniche — the seaside boulevard, beach clubs, seafood restaurants and evening promenade',
      'Central Market (Marché Central) — the freshest fish in Morocco, buy what you want and get it cooked next door',
      'Rick\'s Café — the famous Casablanca-inspired bar and restaurant, cocktails and live piano (expensive but fun)',
      'Quartier des Habous (New Medina) — a beautiful 1930s French-built medina, authentic crafts without tourist pressure',
      'Villa des Arts — contemporary Moroccan art in a stunning 1934 building (€3)',
    ],
    tips: [
      'Casablanca is primarily a business city — most tourists pass through rather than stay, but it rewards exploration',
      'The Hassan II Mosque tour is one of the few mosques in Morocco open to non-Muslims — don\'t miss it',
      'The best seafood in Morocco is in Casablanca\'s port restaurants — order the freshest catch, simply grilled',
      'Casa is the transport hub — easy train connections to Marrakech (3h) and Fez (4h)',
    ],
  },
]

export const RESTAURANTS = {
  marrakech: [
    { name: 'Le Jardin', type: 'Moroccan & Mediterranean', price: 'MAD 150–300', rating: '4.6', area: 'Mouassine, Medina', notes: 'Garden restaurant inside a riad courtyard. Fresh salads, briouats, vegetable tagines. The prettiest setting in the medina for lunch.' },
    { name: 'Nomad', type: 'Modern Moroccan', price: 'MAD 200–400', rating: '4.7', area: 'Rahba Lakdima', notes: 'Rooftop with medina views. Contemporary takes on Moroccan classics — lamb pastilla, chargrilled merguez. The best modern cooking in Marrakech.' },
    { name: 'Café des Épices', type: 'Moroccan Café & Lunch', price: 'MAD 80–200', rating: '4.5', area: 'Place Rahba Kedima', notes: 'Three-storey medina rooftop overlooking the spice square. Harira, briouats, fresh juices and mint tea. Perfect lunch stop.' },
    { name: 'La Maison Arabe', type: 'Classic Moroccan Fine Dining', price: 'MAD 400–700', rating: '4.8', area: 'Bab Doukkala', notes: 'The most celebrated traditional Moroccan restaurant. Bastilla, pigeon pastilla, lamb mechoui. Riad setting. Book ahead.' },
    { name: 'Djemaa el-Fna Food Stalls', type: 'Street Food', price: 'MAD 40–100', rating: '4.3', area: 'Djemaa el-Fna', notes: 'The nightly market is a spectacle. Snail soup, harira, skewers, merguez, sheep\'s heads. Negotiate price first, stick to busy stalls.' },
  ],
  fez: [
    { name: 'Restaurant Nur', type: 'Modern Moroccan Fine Dining', price: 'MAD 350–600', rating: '4.8', area: 'Fès el-Bali', notes: 'The most exciting restaurant in Morocco. Chef Najat Kaanache cooks hyper-seasonal Moroccan food at the highest level. Book 3+ weeks ahead.' },
    { name: 'Riad Rcif Restaurant', type: 'Traditional Moroccan', price: 'MAD 150–300', rating: '4.5', area: 'Rcif, Medina', notes: 'Riad terrace restaurant with medina views. Reliable tagines, bastilla and couscous in a beautiful setting.' },
    { name: 'L\'Ambre', type: 'Moroccan & French', price: 'MAD 200–400', rating: '4.6', area: 'Ville Nouvelle', notes: 'The best restaurant in Fez\'s new city. Fusion of Moroccan and French technique. Excellent wine list for Morocco.' },
  ],
  chefchaouen: [
    { name: 'Bab Ssour', type: 'Moroccan Terrace', price: 'MAD 80–180', rating: '4.5', area: 'Medina', notes: 'Blue terrace with medina views. Simple but excellent kefta tagine, harira, mint tea. The best spot to watch the city from.' },
    { name: 'Café Clock', type: 'Modern Moroccan', price: 'MAD 100–200', rating: '4.4', area: 'Place Uta el-Hammam', notes: 'Camel burger, msemen pancakes and fresh juices. The gathering point for travellers. Good music programme.' },
  ],
  essaouira: [
    { name: 'Port fish grills', type: 'Fresh Grilled Fish', price: 'MAD 60–120', rating: '4.7', area: 'Port de Pêche', notes: 'The best seafood experience in Morocco. Choose from the fresh catch, name your fish, watch it grill. €8–12, cash only, incredible.' },
    { name: 'La Table Madada', type: 'Modern Moroccan', price: 'MAD 200–400', rating: '4.6', area: 'Medina', notes: 'The most refined cooking in Essaouira. Chermoula-marinated fish, argan oil dishes, good wines. Book ahead.' },
    { name: 'Chez Sam', type: 'Traditional Fish Restaurant', price: 'MAD 150–300', rating: '4.5', area: 'Port entrance', notes: 'A Essaouira institution in a blue wooden building by the port. Simple fresh fish, lobster, prawns. Always busy.' },
  ],
  merzouga: [
    { name: 'Kasbah Tombouctou Restaurant', type: 'Moroccan Kasbah Dining', price: 'MAD 200–350', rating: '4.5', area: 'Merzouga', notes: 'The best food in the dunes area. Berber tagines, kefta, pastilla. Eat on the terrace watching the Erg Chebbi turn gold.' },
  ],
  casablanca: [
    { name: 'Le Cabestan', type: 'Mediterranean & Seafood', price: 'MAD 300–600', rating: '4.7', area: 'La Corniche', notes: 'Seafront terrace with Atlantic views. The best fish restaurant in Casablanca. Fresh lobster, sea bass, excellent wine list.' },
    { name: 'La Sqala', type: 'Traditional Moroccan', price: 'MAD 150–300', rating: '4.6', area: 'City centre ramparts', notes: 'Inside the old rampart walls. Garden setting with rose bushes. Traditional couscous, pastilla, tajine at excellent quality.' },
    { name: 'Restaurant du Port de Pêche', type: 'Port Seafood', price: 'MAD 150–350', rating: '4.6', area: 'Old Port', notes: 'Right on the fishing port. The freshest fish in the city — brought in that morning, grilled to order. Very local crowd.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'Morocco Rail Pass', cost: 'MAD 350–600', notes: 'ONCF national train covers Casablanca, Marrakech, Fez, Rabat, Tangier. Comfortable and punctual.' },
    { name: 'Supratours Bus', cost: 'MAD 70–200', notes: 'CTM and Supratours connect cities not served by rail (Essaouira, Merzouga, Chefchaouen). Book ahead.' },
    { name: 'Desert Camp (Merzouga)', cost: 'MAD 600–2000/night', notes: 'Luxury permanent camps include dinner, breakfast, camel trek. Les Portes du Désert and Kasbah Tombouctou are reliable.' },
  ],
  apps: ['Google Maps (Morocco offline works well)', 'inDrive (better than Petit Taxi for non-Arabic speakers)', 'Booking.com (for riads)', 'Google Translate (Arabic + French mode)', 'XE Currency (MAD/EUR fluctuates)'],
  phrases: [
    { en: 'Hello (Arabic)', jp: 'As-salamu alaykum / Merhba', romaji: 'as-SA-la-moo a-LAY-kum / MER-hba' },
    { en: 'Thank you', jp: 'Shukran / Baraka Allahu fik', romaji: 'SHOOK-ran / BA-ra-ka al-LAH-hoo fik' },
    { en: 'How much?', jp: 'Bshhal?', romaji: 'b-SHAL' },
    { en: 'Too expensive', jp: 'Ghali bezzaf', romaji: 'GHA-lee bez-ZAF' },
    { en: 'The bill please', jp: 'L\'addition, s\'il vous plaît (French)', romaji: 'la-dee-SYON seel voo PLEH' },
    { en: 'Delicious!', jp: 'Bnin bezzaf!', romaji: 'b-NEEN bez-ZAF' },
    { en: 'No thank you', jp: 'La, shukran', romaji: 'LA, SHOOK-ran' },
    { en: 'God willing (used constantly)', jp: 'Inshallah', romaji: 'IN-sha-LAH' },
  ],
  phrasesByCategory: [
    {
      category: 'Greetings & Basics',
      emoji: '👋',
      phrases: [
        { en: 'Hello / Welcome', jp: 'Merhba / Ahlan', romaji: 'MER-hba / ah-LAN' },
        { en: 'Peace be upon you', jp: 'As-salamu alaykum', romaji: 'as-SA-la-moo a-LAY-kum' },
        { en: 'And upon you peace', jp: 'Wa alaykum as-salam', romaji: 'wa a-LAY-kum as-sa-LAM' },
        { en: 'Thank you', jp: 'Shukran', romaji: 'SHOOK-ran' },
        { en: 'Thank you very much', jp: 'Shukran bezzaf', romaji: 'SHOOK-ran bez-ZAF' },
        { en: 'You\'re welcome', jp: 'La shukran ala wajib', romaji: 'la SHOOK-ran a-la wa-JIB' },
        { en: 'Sorry / Excuse me', jp: 'Smeh liya', romaji: 'SMEH lee-ya' },
        { en: 'Yes / No', jp: 'Iyeh / La', romaji: 'EE-yeh / LA' },
        { en: 'God willing', jp: 'Inshallah', romaji: 'IN-sha-LAH' },
        { en: 'Thanks be to God', jp: 'Alhamdulillah', romaji: 'al-ham-doo-LIL-la' },
        { en: 'I don\'t understand', jp: 'Ma fahemtsh', romaji: 'ma fa-HEM-tsh' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚕',
      phrases: [
        { en: 'How much to...?', jp: 'Bshhal l...?', romaji: 'b-SHAL l...' },
        { en: 'Stop here', jp: 'Weqef hna', romaji: 'WEH-qef HNA' },
        { en: 'Where is...?', jp: 'Fin kayn...?', romaji: 'FIN kayn' },
        { en: 'The medina', jp: 'L\'medina', romaji: 'l-meh-DEE-na' },
        { en: 'The station', jp: 'La gare', romaji: 'la GAR' },
        { en: 'Turn left / right', jp: 'Lisr / Limen', romaji: 'li-SR / li-MEN' },
        { en: 'By taxi', jp: 'B\'taxi', romaji: 'b-TAK-see' },
      ],
    },
    {
      category: 'Food & Dining',
      emoji: '🍋',
      phrases: [
        { en: 'The bill please', jp: 'L\'addition, s\'il vous plaît', romaji: 'la-dee-SYON seel voo PLEH' },
        { en: 'Delicious!', jp: 'Bnin bezzaf!', romaji: 'b-NEEN bez-ZAF' },
        { en: 'A glass of mint tea', jp: 'Kas d\'atay', romaji: 'KAS d-ah-TAY' },
        { en: 'Water please', jp: 'L\'ma afak', romaji: 'l-MA a-FAK' },
        { en: 'No spice please', jp: 'Bla nhar afak', romaji: 'bla n-HAR a-FAK' },
        { en: 'I am vegetarian', jp: 'Ana nabati', romaji: 'a-NA na-BA-tee' },
        { en: 'Cheers!', jp: 'Bisaha!', romaji: 'bi-SA-ha' },
      ],
    },
    {
      category: 'Shopping & Bargaining',
      emoji: '🛍️',
      phrases: [
        { en: 'How much is this?', jp: 'Bshhal had?', romaji: 'b-SHAL HAD' },
        { en: 'Too expensive', jp: 'Ghali bezzaf', romaji: 'GHA-lee bez-ZAF' },
        { en: 'Lower the price', jp: 'Nqqes chwiya', romaji: 'n-QES CHWEE-ya' },
        { en: 'Final price?', jp: 'Akhir thaman?', romaji: 'A-kheer tha-MAN' },
        { en: 'I\'ll take it', jp: 'Ghadi nakhdu', romaji: 'GHA-dee na-KHD-oo' },
        { en: 'Just looking', jp: 'Ghi katshuf', romaji: 'ghi kat-SHUF' },
        { en: 'No thank you', jp: 'La, shukran', romaji: 'LA, SHOOK-ran' },
      ],
    },
    {
      category: 'Emergency',
      emoji: '🆘',
      phrases: [
        { en: 'Help!', jp: 'Awenni!', romaji: 'a-WEN-nee' },
        { en: 'Call the police', jp: 'Ayyet l\'police', romaji: 'a-YET l-po-LEES' },
        { en: 'I need a doctor', jp: 'Khassni tbib', romaji: 'KHAS-nee t-BEEB' },
        { en: 'Where is the hospital?', jp: 'Fin kayn l\'hôpital?', romaji: 'FIN kayn l-oh-PEE-tal' },
        { en: 'I\'ve lost my passport', jp: 'Ḍya menni l\'passeport', romaji: 'DYAH men-NEE l-pass-PORT' },
        { en: 'Thief!', jp: 'Shoufar!', romaji: 'SHOO-far' },
      ],
    },
  ],
}
