export const TRIP = {
  route: 'Bangkok → Ayutthaya → Chiang Mai → Pai → Phuket → Koh Samui',
}

export const CITIES = [
  {
    id: 'bangkok',
    name: 'Bangkok',
    emoji: '🛕',
    hotel: 'Silom / Sathorn or Sukhumvit (BTS access essential)',
    desc: 'Chaotic, electrifying mega-city where golden temples rise above neon-lit street food markets and rooftop bars.',
    image: 'https://images.unsplash.com/photo-1563492065-efd9d3a19ed5?w=800&q=80',
    color: '#c49a00',
    highlights: [
      'Wat Phra Kaew (Temple of the Emerald Buddha) — Thailand\'s most sacred temple, inside the Grand Palace complex',
      'Wat Pho — reclining Buddha (46m long), birthplace of traditional Thai massage',
      'Wat Arun (Temple of Dawn) — riverside pagoda with mosaic of Chinese porcelain, climb to the top',
      'Chatuchak Weekend Market — 8,000 stalls, 200,000 visitors, one of the world\'s great markets',
      'Khao San Road — Bangkok\'s backpacker hub, full moon party culture, surprisingly fun for an evening',
      'Chinatown (Yaowarat) — night street food along Yaowarat Road, best after 7pm',
      'Floating markets (Amphawa or Damnoen Saduak) — canal boat markets, best at dawn',
      'Rooftop bars — Vertigo at Banyan Tree, Sky Bar from The Hangover, Octave all worth the dress code',
    ],
    tips: [
      'BTS Skytrain and MRT Metro make the city navigable — get a Rabbit Card for BTS',
      'Tuk-tuks are fun but always negotiate the price before getting in — apps (Grab) are far less stress',
      'Dress conservatively for temples — shoulders and knees must be covered; sarongs available to borrow',
      'Bangkok street food safety: busy stalls with high turnover are the safest bet. Avoid sitting in direct sun.',
    ],
  },
  {
    id: 'chiangmai',
    name: 'Chiang Mai',
    emoji: '🐘',
    hotel: 'Old City or Nimman (Nimmanhaemin Road area)',
    desc: 'Northern cultural capital — moated old city, 300+ temples, the best Thai cooking classes, and ethical elephant sanctuaries.',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
    color: '#2d6a4f',
    highlights: [
      'Doi Suthep — golden temple above the city at 1,080m, panoramic views, 306 naga-lined steps',
      'Elephant Nature Park — the original ethical elephant sanctuary by Lek Chailert, half or full day',
      'Sunday Walking Street (Wualai) — best market in northern Thailand, handmade crafts, street food',
      'Nimman Road — the hip neighbourhood, indie cafés, concept stores, excellent coffee scene',
      'Doi Inthanon National Park — Thailand\'s highest peak (2,565m), waterfalls, hilltribe villages',
      'Chiang Rai day trip — White Temple (Wat Rong Khun), Blue Temple, Golden Triangle',
      'Thai cooking classes — many half-day options including market visit; Zabb E Lee is well regarded',
      'Night Bazaar — nightly market off Chang Klan Road, handicrafts, silver jewellery, hill tribe textiles',
    ],
    tips: [
      'Hire a scooter or use red songthaew shared taxis — tuk-tuks in Chiang Mai often push gem shops',
      'Elephant sanctuaries: avoid any place offering elephant riding — Elephant Nature Park and BLES are ethical',
      'Northern Thai cuisine is distinct: khao soi (coconut curry noodle soup) is the must-order dish',
      'Loy Krathong / Yi Peng lantern festival (November) is extraordinary — plan around it if possible',
    ],
  },
  {
    id: 'phuket',
    name: 'Phuket',
    emoji: '🌴',
    hotel: 'Kata Noi or Kamala for calm; Patong if you want nightlife',
    desc: 'Thailand\'s largest island — dramatic limestone karst coastline, emerald Andaman waters, and the gateway to Phang Nga Bay.',
    image: 'https://images.unsplash.com/photo-1547721064-da6cfb341d50?w=800&q=80',
    color: '#2874a6',
    highlights: [
      'Phang Nga Bay — James Bond Island, sea caves and karst formations, best by kayak at dawn',
      'Phi Phi Islands — day trip by speedboat, Maya Bay (where The Beach was filmed), snorkelling',
      'Old Phuket Town — Sino-Portuguese shophouses, weekend market, excellent café scene',
      'Kata Noi Beach — quieter than Patong, coral reef close to shore, beautiful sunset position',
      'Big Buddha — 45m white marble Buddha on the hilltop, free entry, visible from across the island',
      'Khao Sok National Park — ancient rainforest, limestone mountains, river safari, overwater bungalows',
      'Rawai seafood pier — local fishing village, buy fresh seafood to cook at your guesthouse',
      'Promthep Cape — southernmost point, spectacular 360° sunset over the Andaman Sea',
    ],
    tips: [
      'Hire a scooter — Phuket is large and taxis are expensive. International licence required.',
      'Best beaches: Kata Noi > Kamala > Naiharn. Patong beach is crowded and overrated.',
      'Rainy season May–October — seas can be rough on west coast. East coast (Koh Samui) has opposite seasons.',
      'Avoid Full Moon Party Koh Phangan unless that\'s your scene — ferries in peak season are chaotic',
    ],
  },
  {
    id: 'kohsamui',
    name: 'Koh Samui',
    emoji: '🌺',
    hotel: 'Chaweng for buzz; Bophut (Fisherman\'s Village) for character',
    desc: 'Coconut palm island in the Gulf of Thailand — diverse beaches, luxury resorts, and a surprisingly charming Fisherman\'s Village.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Ang Thong Marine National Park — day trip by boat, 42 islands, emerald lagoon, sea cave, snorkelling',
      'Bophut Fisherman\'s Village — Friday night market, rustic wooden shophouses, best sunset dining',
      'Nathon (west coast) — local town away from tourists, market, ferries, authentic cafés',
      'Na Muang Waterfall — two-tiered inland waterfall, elephant ride option (check ethics first)',
      'Big Buddha Temple (Wat Phra Yai) — 12m golden Buddha on a small island causeway north of Chaweng',
      'Koh Tan and Koh Matsum — small islands off the south coast, pristine snorkelling, few visitors',
      'Chaweng Night Market — lively local food market behind the main strip, far better than tourist restaurants',
      'Koh Tao day trip — arguably Thailand\'s best diving and snorkelling, 1.5h by ferry',
    ],
    tips: [
      'Rainy season in the Gulf is October–December — opposite to Phuket. Best weather December–April.',
      'Bophut Fisherman\'s Village Friday Walking Street is worth timing your visit around',
      'Taxis on Samui have fixed high prices — negotiate, or rent a scooter for half the cost',
      'Ko Tao is a budget divers\' paradise — Open Water certification is cheapest in Thailand here',
    ],
  },
  {
    id: 'pai',
    name: 'Pai',
    emoji: '🌿',
    hotel: 'Walking Street area or a riverside bungalow outside town',
    desc: 'Mountain valley retreat in northern Thailand — waterfalls, hot springs, rice fields, and a backpacker village with genuine charm.',
    image: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'Pai Canyon (Kong Lan) — narrow clay ridgelines above a forested gorge, spectacular at sunset',
      'Mo Paeng Waterfall — 3-tiered waterfall with natural swimming pools and rope swings, 8km from town',
      'Tha Pai Hot Springs — riverside natural hot springs, scenic rural setting',
      'Yun Lai Viewpoint — sunrise above the sea of mist in the valley, arrive before 7am',
      'Pai Walking Street — nightly market along the main street, local food, handmade goods',
      'Mae Yen Waterfall (trekking) — 8km hike through jungle, worth hiring a local guide',
      'Santichon Chinese Village — Yunnan Chinese community in the hills, distinctive red buildings',
      'White Buddha (Wat Phra That Mae Yen) — hilltop temple with valley panorama, climb 353 steps',
    ],
    tips: [
      'Pai is 3 hours from Chiang Mai on 762 bends of mountain road — take morning minibus or rent a scooter',
      'Two days minimum — it\'s a place to slow down, not rush through',
      'Evenings are cool in the mountains — bring a light layer even in the hot season',
      'Budget-friendly: guesthouses, street food, and everything in Pai is very affordable',
    ],
  },
  {
    id: 'ayutthaya',
    name: 'Ayutthaya',
    emoji: '🏛️',
    hotel: 'Day trip from Bangkok (80 minutes by train) or stay one night',
    desc: 'Ancient capital of the Thai kingdom — Buddha heads entwined in Bodhi tree roots, colossal ruined chedis, and UNESCO heritage at every turn.',
    image: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80',
    color: '#8b4513',
    highlights: [
      'Wat Mahathat — the iconic Buddha head nestled in tree roots (please don\'t pose level with the face)',
      'Wat Phra Si Sanphet — former royal temple with three restored chedis, once housed a 16m standing Buddha',
      'Wat Chaiwatthanaram — riverside temple, eight prangs, dramatic sunset reflections in the water',
      'Wat Ratchaburana — intact prang with crypt underground, gold artefacts found here are in Bangkok museum',
      'Ayutthaya Historical Park — UNESCO site, best explored by bicycle hired in town (฿50/day)',
      'Chao Phraam Night Market — riverside market with boat noodles, grilled river prawns, and sticky rice',
      'Bang Pa-In Royal Palace — summer palace with mix of Thai, Chinese, and Victorian architecture',
      'Elephant kraal (Wat Yai Chai Mongkhon) — 700-year-old royal elephant stable, giant Buddha images',
    ],
    tips: [
      'Train from Bangkok\'s Hua Lamphong or Bangsue Grand Station — buy tickets at the station for same day',
      'Bicycle is the best way to see Ayutthaya — the historical park is spread across a river island',
      'Go early: temples open from 8am, temperatures are brutal by midday (heat + zero shade)',
      'Dress code strictly enforced — shoulders, chest, and knees covered at all temple sites',
    ],
  },
]

export const RESTAURANTS = {
  bangkok: [
    { name: 'Jay Fai', type: 'Thai Street Food', price: '฿700–1,500', rating: '4.7', area: 'Banglamphu', notes: 'One Michelin star street food. Crab omelette and drunken noodles. Queue from 5am or book online.' },
    { name: 'Bo.lan', type: 'Fine Thai', price: '฿2,500–3,500', rating: '4.8', area: 'Ekamai', notes: 'Thailand\'s most acclaimed fine dining restaurant. Organic, royal Thai cuisine. Book well ahead.' },
    { name: 'Gaggan Anand', type: 'Progressive Indian', price: '฿7,000+', rating: '4.9', area: 'Wireless Road', notes: 'Asia\'s best restaurant 2024. Emoji menu. 25-course progressive Indian. Booking opens 3 months ahead.' },
    { name: 'Yaowarat Chinatown (night)', type: 'Street Food', price: '฿100–300', rating: '4.7', area: 'Chinatown', notes: 'The definitive Bangkok evening. Pad see ew, pad Thai, mango sticky rice, fresh coconut. After 7pm.' },
    { name: 'Paste', type: 'Royal Thai', price: '฿1,500–2,500', rating: '4.7', area: 'Gaysorn Village', notes: 'Elegant royal Thai cooking. The best khao chae (cold jasmine rice) in Bangkok. Also in Samui.' },
  ],
  chiangmai: [
    { name: 'Khao Soi Khun Yai', type: 'Northern Thai', price: '฿60–100', rating: '4.7', area: 'Nimman', notes: 'Best khao soi in Chiang Mai — the definitive northern Thai coconut curry noodle soup. Cash only.' },
    { name: 'Huen Phen', type: 'Traditional Northern Thai', price: '฿150–300', rating: '4.6', area: 'Old City', notes: 'Set in an antique-filled old wooden house. Gaeng hang lay (Burmese pork curry) and sai oua sausage.' },
    { name: 'Blackitch Artisan Kitchen', type: 'Thai Tasting Menu', price: '฿1,800–2,500', rating: '4.8', area: 'Nimman', notes: 'Creative northern Thai tasting menu. Chef Chatree Ratchananon\'s personal expression. 8–10 courses.' },
    { name: 'Zabb E Lee', type: 'Isaan Street Food', price: '฿100–200', rating: '4.5', area: 'Nimman', notes: 'Exceptional northeastern Thai (Isaan) food. Som tam, larb, grilled chicken. Bright and no frills.' },
    { name: 'Pun Pun Organic', type: 'Vegetarian Thai', price: '฿80–150', rating: '4.4', area: 'Wat Suan Dok', notes: 'Organic vegetarian Thai inside temple grounds. Proceeds fund agricultural projects. Simple and excellent.' },
  ],
  phuket: [
    { name: 'Suay Restaurant', type: 'Modern Thai', price: '฿600–1,200', rating: '4.7', area: 'Old Town', notes: 'Refined Thai dishes using local Andaman ingredients. Best fine dining in Phuket Town. Book ahead.' },
    { name: 'Roti Talay', type: 'Muslim Street Food', price: '฿60–120', rating: '4.5', area: 'Rawai', notes: 'The best roti with curries and massaman in Phuket. Breakfast or lunch only, closes early.' },
    { name: 'Khua Kling Pak Sod', type: 'Southern Thai', price: '฿200–500', rating: '4.7', area: 'Phuket Town', notes: 'Fiercely spiced southern Thai cooking. Khua kling (dry-fried minced meat), mango salad. Not for spice wimps.' },
    { name: 'Seafood at Rawai Pier', type: 'Grilled Seafood', price: '฿300–700', rating: '4.5', area: 'Rawai', notes: 'Buy fresh from the fishing boats, take it 50m to the restaurants to grill. The most local experience in Phuket.' },
  ],
  kohsamui: [
    { name: 'The Fisherman\'s Village restaurants', type: 'Thai / Seafood', price: '฿300–800', rating: '4.5', area: 'Bophut', notes: 'Multiple excellent restaurants in the wooden shophouses. Shack Bar for sunset cocktails beforehand.' },
    { name: 'Pad Thai Shop (Nathon Market)', type: 'Street Food', price: '฿60–100', rating: '4.6', area: 'Nathon', notes: 'The best pad Thai on the island, made by a grandmother at the local market. No name, just go at lunch.' },
    { name: 'Dining on the Rocks', type: 'Fine Dining', price: '฿2,000–4,000', rating: '4.7', area: 'Chaweng Noi', notes: '6 Senses resort restaurant on a clifftop above the sea. Spectacular setting for a special evening.' },
    { name: 'Larder', type: 'International / Brunch', price: '฿300–600', rating: '4.5', area: 'Bophut', notes: 'Best brunch café on the island. Organic ingredients, excellent coffee, shakshuka and smash avocado.' },
  ],
  pai: [
    { name: 'Nong Beer', type: 'Local Thai', price: '฿60–120', rating: '4.5', area: 'Walking Street', notes: 'The most beloved local restaurant in Pai. Generous portions, warm family service, excellent stir fries.' },
    { name: 'Amido Thai Vegan', type: 'Vegan Thai', price: '฿80–150', rating: '4.4', area: 'Walking Street', notes: 'Surprisingly excellent vegan Thai food. Green curry, pad see ew, tom kha — all plant-based.' },
    { name: 'Na\'s Kitchen', type: 'Breakfast / Café', price: '฿80–180', rating: '4.5', area: 'Town centre', notes: 'The best morning café in Pai. Pancakes, fresh fruit, strong Thai coffee, tranquil garden setting.' },
  ],
  ayutthaya: [
    { name: 'Baan Kun Pra Restaurant', type: 'Thai / Riverside', price: '฿200–500', rating: '4.4', area: 'Riverside', notes: 'Riverside deck in a converted old house. Thai standards with views over the Chao Phraya. Lunch only.' },
    { name: 'Roti Sai Mai', type: 'Street Food / Dessert', price: '฿30–60', rating: '4.6', area: 'Town market', notes: 'Ayutthaya\'s iconic sweet — cotton candy wrapped in thin roti crepes. Every local eats it here.' },
    { name: 'Night Market (Chao Phraam)', type: 'Night Market', price: '฿60–200', rating: '4.3', area: 'Riverside', notes: 'The best reason to stay overnight. Boat noodles, river prawns, grilled corn, fresh juices at dusk.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'Rabbit Card (Bangkok BTS)', cost: 'Load as needed', notes: 'Works on all BTS Skytrain lines. Buy at any BTS station — essential for navigating Bangkok.' },
    { name: 'Grab App', cost: 'Per ride', notes: 'South-East Asia\'s Uber. Essential for Bangkok, Chiang Mai, and Phuket. Always cheaper than street taxis.' },
    { name: 'AirAsia / Nok Air domestic flights', cost: '฿500–2,000', notes: 'Bangkok–Chiang Mai and Bangkok–Phuket are 1h each. Book ahead for cheap fares.' },
    { name: 'Seatran / Lomprayah ferries', cost: '฿200–400', notes: 'High-speed ferries between Gulf islands (Koh Samui, Koh Tao, Koh Phangan). Book online.' },
  ],
  apps: ['Grab (taxis + food delivery)', 'Google Maps (offline)', 'Google Translate (camera mode for Thai script)', 'Klook (tours and activities)', 'Agoda (hotels)', 'XE Currency'],
  phrases: [],
  phrasesByCategory: [
    {
      category: 'Greetings & Basics',
      emoji: '👋',
      phrases: [
        { en: 'Hello (polite, male speaker)', jp: 'สวัสดีครับ', romaji: 'Sa-wat-dee kráp' },
        { en: 'Hello (polite, female speaker)', jp: 'สวัสดีค่ะ', romaji: 'Sa-wat-dee kâ' },
        { en: 'Thank you (male speaker)', jp: 'ขอบคุณครับ', romaji: 'Khòp-khun kráp' },
        { en: 'Thank you (female speaker)', jp: 'ขอบคุณค่ะ', romaji: 'Khòp-khun kâ' },
        { en: 'Yes', jp: 'ใช่', romaji: 'Châi' },
        { en: 'No', jp: 'ไม่ใช่', romaji: 'Mâi châi' },
        { en: 'Sorry / Excuse me', jp: 'ขอโทษ', romaji: 'Khǒ thôht' },
        { en: 'Never mind / No problem', jp: 'ไม่เป็นไร', romaji: 'Mâi pen rai' },
        { en: 'I don\'t understand', jp: 'ไม่เข้าใจ', romaji: 'Mâi khâo jai' },
        { en: 'Goodbye', jp: 'ลาก่อน', romaji: 'Laa gòn' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚉',
      phrases: [
        { en: 'Where is...?', jp: '...อยู่ที่ไหน', romaji: '...yùu thîi nǎi?' },
        { en: 'How much?', jp: 'เท่าไหร่', romaji: 'Thâo rài?' },
        { en: 'Too expensive', jp: 'แพงเกินไป', romaji: 'Phaeng goen pai' },
        { en: 'Can you lower the price?', jp: 'ลดราคาได้ไหม', romaji: 'Lót raa-khaa dâi mǎi?' },
        { en: 'Take me here please', jp: 'พาไปที่นี่ด้วย', romaji: 'Phaa pai thîi nîi dûay' },
        { en: 'Stop here', jp: 'จอดตรงนี้', romaji: 'Jòt trong nîi' },
        { en: 'Left', jp: 'ซ้าย', romaji: 'Sáai' },
        { en: 'Right', jp: 'ขวา', romaji: 'Khwǎa' },
      ],
    },
    {
      category: 'Food & Dining',
      emoji: '🍜',
      phrases: [
        { en: 'Delicious!', jp: 'อร่อย', romaji: 'A-ròi!' },
        { en: 'Very spicy', jp: 'เผ็ดมาก', romaji: 'Phèt mâak' },
        { en: 'Not spicy please', jp: 'ไม่เอาเผ็ด', romaji: 'Mâi ao phèt' },
        { en: 'A little spicy', jp: 'เผ็ดนิดหน่อย', romaji: 'Phèt nít nòi' },
        { en: 'The bill please', jp: 'เก็บเงินด้วย', romaji: 'Kèp ngoen dûay' },
        { en: 'I am vegetarian', jp: 'ฉันทานมังสวิรัติ', romaji: 'Chǎn thaan mang-sa-wi-rát' },
        { en: 'No meat', jp: 'ไม่ใส่เนื้อ', romaji: 'Mâi sài néua' },
        { en: 'Water please', jp: 'ขอน้ำด้วย', romaji: 'Khǒ náam dûay' },
        { en: 'One more please', jp: 'ขออีกอัน', romaji: 'Khǒ ìik an' },
        { en: 'What do you recommend?', jp: 'แนะนำอะไร', romaji: 'Náe-nam a-rai?' },
      ],
    },
    {
      category: 'Shopping',
      emoji: '🛍️',
      phrases: [
        { en: 'How much is this?', jp: 'อันนี้เท่าไหร่', romaji: 'An níi thâo rài?' },
        { en: 'Can you reduce the price?', jp: 'ลดได้ไหม', romaji: 'Lót dâi mǎi?' },
        { en: 'Too expensive', jp: 'แพงไป', romaji: 'Phaeng pai' },
        { en: 'I\'ll take it', jp: 'เอาอันนี้', romaji: 'Ao an níi' },
        { en: 'Do you have another colour?', jp: 'มีสีอื่นไหม', romaji: 'Mii sǐi ùen mǎi?' },
        { en: 'Just looking', jp: 'แค่ดูเฉยๆ', romaji: 'Khâe duu chǒei chǒei' },
        { en: 'Do you accept cards?', jp: 'รับบัตรเครดิตไหม', romaji: 'Ráp bàt khré-dit mǎi?' },
        { en: 'Do you have a bag?', jp: 'มีถุงไหม', romaji: 'Mii thǔng mǎi?' },
      ],
    },
    {
      category: 'Emergency',
      emoji: '🆘',
      phrases: [
        { en: 'Help!', jp: 'ช่วยด้วย!', romaji: 'Chûay dûay!' },
        { en: 'Call the police', jp: 'เรียกตำรวจด้วย', romaji: 'Rîak tam-rùat dûay' },
        { en: 'Call an ambulance', jp: 'เรียกรถพยาบาล', romaji: 'Rîak rót pha-yaa-baan' },
        { en: 'I need a doctor', jp: 'ต้องการหมอ', romaji: 'Tông-kaan mǒo' },
        { en: 'I\'ve lost my passport', jp: 'หนังสือเดินทางหาย', romaji: 'Nǎng-sǔe dern-thaang hǎai' },
        { en: 'Where is the hospital?', jp: 'โรงพยาบาลอยู่ที่ไหน', romaji: 'Rohng pha-yaa-baan yùu thîi nǎi?' },
        { en: 'I feel sick', jp: 'ฉันไม่สบาย', romaji: 'Chǎn mâi sa-baai' },
      ],
    },
  ],
}
