export const TRIP = {
  route: 'Athens → Santorini → Mykonos → Crete → Rhodes → Thessaloniki',
}

export const CITIES = [
  {
    id: 'athens',
    name: 'Athens',
    emoji: '🏛️',
    hotel: 'Hotel Grande Bretagne / Monastiraki neighbourhood',
    desc: 'The cradle of Western civilisation — ancient ruins rising above a chaotic, vibrant modern city.',
    image: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80',
    color: '#1e78b4',
    highlights: [
      'Acropolis & Parthenon — the most important ancient site in the Western world (€20, free Sundays Nov–Mar)',
      'Acropolis Museum — spectacular home for the Parthenon sculptures (€15)',
      'Ancient Agora — the marketplace where Socrates taught, Stoa of Attalos (€10)',
      'National Archaeological Museum — finest collection of ancient Greek art in existence (€12)',
      'Monastiraki Flea Market — Athens\' famous Sunday market, antiques, music, bargains',
      'Plaka & Anafiotika — the old neighbourhoods at the foot of the Acropolis',
      'Ermou Street & Syntagma — changing of the guard at the Parliament (every hour)',
      'Cape Sounion day trip — Poseidon\'s clifftop temple with sunset views over the Aegean (€10)',
    ],
    tips: [
      'Buy the combined Acropolis ticket (€30) — covers 7 sites including Ancient Agora and Roman Agora',
      'Visit the Acropolis at 8am when it opens — by 10am in summer it\'s packed and blisteringly hot',
      'Athens is NOT an early city — restaurants fill up from 9:30pm, bars from midnight',
      'Piraeus port is 45min from city centre on Metro Line 1 — allow extra time for ferry departures',
    ],
  },
  {
    id: 'santorini',
    name: 'Santorini',
    emoji: '🌅',
    hotel: 'Mystique / Canaves Oia Suites — Oia, Caldera-view',
    desc: 'The most spectacular view in the Mediterranean — blue domes, white houses, and a volcanic caldera sunset.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    color: '#1e78b4',
    highlights: [
      'Oia sunset — the world\'s most famous sunset, crowds gather 30min early (free, just find a spot)',
      'Caldera boat trip — volcanic hot springs, Red Beach, White Beach, cave snorkelling',
      'Akrotiri Archaeological Site — the Bronze Age city buried by Santorini\'s volcanic eruption (€12)',
      'Oia village walk — blue domes, art galleries, jewellery workshops',
      'Fira town — the main town, cliff-edge restaurants, cable car down to the port (€6)',
      'Amoudi Bay — eat at the waterline tavernas below Oia, swim off the rocks',
      'Santorini wine tasting — Assyrtiko white wine is extraordinary, grown in volcanic ash soils',
      'Black sand beaches — Perissa and Perivolos, long and dramatic',
    ],
    tips: [
      'Oia sunset crowds are intense — book a caldera-view dinner to watch in comfort',
      'Rent an ATV (€25/day) — the only practical way to explore the island independently',
      'Oia to Fira hike (10km) — spectacular 3–4 hour coastal walk, bring water and start early',
      'Book restaurants with caldera views weeks ahead — the best spots fill up entirely',
    ],
  },
  {
    id: 'mykonos',
    name: 'Mykonos',
    emoji: '🏖️',
    hotel: 'Myconian Ambassador / Mykonos Town (Chora)',
    desc: 'The glamorous island — iconic windmills, Little Venice, world-class clubs and beautiful beaches.',
    image: 'https://images.unsplash.com/photo-1601581987809-a874a81309c9?w=800&q=80',
    color: '#27ae60',
    highlights: [
      'Chora (Mykonos Town) — the maze of white alleyways, boutiques and cafés',
      'Iconic windmills — the seven hillside windmills, Mykonos\'s most photographed image',
      'Little Venice — bars and restaurants hanging over the sea, Aegean views',
      'Delos day trip — uninhabited sacred island, UNESCO, ancient ruins (€12 + ferry €20)',
      'Paradise Beach and Super Paradise — legendary beach clubs, DJ sets from noon',
      'Ornos Beach — more relaxed family beach, crystal water, tavernas',
      'Ano Mera village — traditional village inland, away from the tourist scene',
      'Sunset at Little Venice — cocktails at Caprice or Galleraki, waves below',
    ],
    tips: [
      'Mykonos is genuinely expensive — budget €15 for a cocktail, €50+ for beach club entry',
      'High season (July–August) is overwhelming — May/June and September are much better',
      'The old port area has the best value fish tavernas hidden in the back streets',
      'Delos is unmissable and very few people visit — go on a quiet day',
    ],
  },
  {
    id: 'crete',
    name: 'Crete',
    emoji: '🫒',
    hotel: 'Domes Noruz Chania / Old Harbour Chania',
    desc: 'Greece\'s largest island — Minoan ruins, Venetian harbours, spectacular gorges and the richest local food culture.',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Knossos Palace — Bronze Age Minoan palace, Europe\'s oldest civilisation, 3,500 years old (€15)',
      'Gorge of Samariá — 16km gorge hike through White Mountains to the Libyan Sea (€5, 5–6 hours)',
      'Chania Old Town — Venetian lighthouse, covered market, old harbour restaurants and coffee',
      'Elafonisi Beach — pink-tinged lagoon beach in the far west, extraordinary colour',
      'Heraklion Archaeological Museum — the Minoan world in one extraordinary collection (€15)',
      'Rethymno Old Town — Venetian fortress, Ottoman fountain, excellent tavernas and mezze',
      'Sfakia region — the wild south coast, traditional mountain villages, boat-only beaches',
      'Cretan food tour — dakos, kalitsounia, slow-cooked lamb (antikristo), raki tastings',
    ],
    tips: [
      'Crete needs a hire car — it\'s 260km long and the best spots are inaccessible by bus',
      'The Samariá Gorge is one-way — take the boat back from Agia Roumeli to Sfakia',
      'Cretan olive oil is the finest in the world — buy it at the source from village shops',
      'Visit Knossos in the early morning before tour groups arrive (opens 8am)',
    ],
  },
  {
    id: 'rhodes',
    name: 'Rhodes',
    emoji: '🏰',
    hotel: 'Rodos Park Suites / Old Town medieval streets',
    desc: 'The best-preserved medieval city in Europe inside one of the ancient world\'s great wonders.',
    image: 'https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=800&q=80',
    color: '#c0392b',
    highlights: [
      'Old Town Rhodes — UNESCO walled medieval city, Knights of St. John, 4km of walls (free to walk)',
      'Palace of the Grand Masters — Byzantine-turned-Crusader-fortress, extraordinary floors (€8)',
      'Street of the Knights (Ippoton) — the world\'s best preserved medieval street, 14th century',
      'Lindos Acropolis — clifftop Doric temple above a traditional white village (€12)',
      'Anthony Quinn Bay — beautiful cove where the film Guns of Navarone was shot',
      'Faliraki Beach — long sandy beach, water sports, reliable sun',
      'Kameiros ancient city — atmospheric ruins in a hillside setting (€8)',
      'Valley of the Butterflies — seasonal butterfly reserve, thousands of Jersey Tiger moths (€5)',
    ],
    tips: [
      'The Old Town is worth staying inside the walls — medieval atmosphere is extraordinary at night',
      'Lindos is a must but go before 10am or after 4pm to avoid cruise ship passengers',
      'Rhodes town has excellent restaurants along the old harbour — Niki\'s and Marco Polo taverna',
      'The island has its own wine — try Cair wines, particularly the CAIR sparkling',
    ],
  },
  {
    id: 'thessaloniki',
    name: 'Thessaloniki',
    emoji: '🏟️',
    hotel: 'Electra Palace Thessaloniki / City Centre',
    desc: 'Greece\'s second city and greatest food city — Byzantine churches, Roman ruins and the best food scene in the country.',
    image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'White Tower — the 15th century Ottoman landmark and symbol of the city (€4)',
      'Archaeological Museum of Thessaloniki — Alexander the Great\'s Macedonian treasures (€8)',
      'Rotunda — Roman mausoleum turned church turned mosque, 4th century circular perfection (€4)',
      'Byzantine walls walk — 3km of intact Byzantine fortifications with sea views',
      'Ano Poli (Upper Town) — Ottoman wooden houses, quiet streets, panoramas over the city',
      'Kapani Market & Modiano Market — the city\'s living food markets, extraordinary fresh produce',
      'Ladadika district — the bar and restaurant quarter, the best nightlife in Greece outside Athens',
      'Bougatsa at Bantis — the city\'s signature custard pastry, best in the world',
    ],
    tips: [
      'Thessaloniki is Greece\'s food capital — locals will tell you Athens can\'t cook',
      'The seafront promenade (Nea Paralia) is the city\'s living room — walk it at sunset',
      'Tsipouradika restaurants are the local institution — ouzo-equivalent spirit with small mezze plates',
      'Day trip to Vergina — Philip II of Macedon\'s royal tombs and one of the greatest museum finds ever (€12)',
    ],
  },
]

export const RESTAURANTS = {
  athens: [
    { name: 'Thanasis', type: 'Souvlaki & Kebabs', price: '€8–15', rating: '4.4', area: 'Monastiraki', notes: 'The classic Athens souvlaki institution. Standing room only. The lamb kebab is the order.' },
    { name: 'Diporto Agoras', type: 'Old Athens Taverna', price: '€10–20', rating: '4.6', area: 'Psiri', notes: 'No menu, no sign, no card payments. Daily dishes only. One of the most authentic lunches in Athens.' },
    { name: 'Strofi', type: 'Traditional Greek', price: '€25–45', rating: '4.5', area: 'Makrygianni', notes: 'Rooftop terrace with Parthenon views. The moussaka and slow-cooked lamb here are excellent.' },
    { name: 'Kostas Souvlaki', type: 'Street Souvlaki', price: '€3–6', rating: '4.8', area: 'Syntagma', notes: 'A tiny hole-in-the-wall, queue down the street. The best pork souvlaki pita in Athens. €3.50.' },
    { name: 'Nolan', type: 'Modern Greek-Asian', price: '€35–60', rating: '4.7', area: 'Koukaki', notes: 'Athens\' most creative restaurant — Greek ingredients, Japanese technique. Book 2+ weeks ahead.' },
  ],
  santorini: [
    { name: 'Metaxy Mas', type: 'Traditional Greek', price: '€20–35', rating: '4.8', area: 'Exo Gonia', notes: 'The island\'s best taverna — off the tourist route, local clientele, extraordinary mezze. Book ahead.' },
    { name: 'To Psaraki', type: 'Fresh Seafood', price: '€25–45', rating: '4.6', area: 'Vlychada', notes: 'Working fishing harbour setting. The catch of the day, grilled octopus and local wine.' },
    { name: 'Selene', type: 'Modern Santorinian', price: '€50–90', rating: '4.7', area: 'Pyrgos', notes: 'The island\'s finest restaurant. Menu built around local Santorinian produce — fava, capers, Assyrtiko.' },
    { name: 'Ammoudi Fish Tavern', type: 'Harbourside Seafood', price: '€25–40', rating: '4.6', area: 'Amoudi Bay (below Oia)', notes: 'Right on the water below Oia. Grilled lobster and sea urchin. Swim, then eat, then swim again.' },
    { name: 'Argo Restaurant', type: 'Caldera View Dining', price: '€30–50', rating: '4.5', area: 'Fira', notes: 'Caldera-edge restaurant in Fira. Greek classics with the view. Pre-book a terrace table for sunset.' },
  ],
  mykonos: [
    { name: 'Kiki\'s Tavern', type: 'Greek Taverna', price: '€20–35', rating: '4.8', area: 'Agios Sostis Beach', notes: 'No phone, no reservations, cash only. Queue from noon. Pork chops, Greek salad, carafes of wine. Legendary.' },
    { name: 'Niko\'s Taverna', type: 'Traditional Seafood', price: '€20–35', rating: '4.5', area: 'Chora', notes: 'The old town\'s most reliable taverna since 1967. Good value, excellent grilled fish, local crowd.' },
    { name: 'Joanna\'s Nikos Place', type: 'Greek Home Cooking', price: '€15–25', rating: '4.6', area: 'Chora', notes: 'Family-run since 1968. Moussaka, stuffed tomatoes, daily specials. The real Mykonos behind the glamour.' },
    { name: 'Scorpios', type: 'Beach Club Dining', price: '€40–80', rating: '4.5', area: 'Paraga Beach', notes: 'Mykonos\' most famous beach club. Mediterranean food, sunset DJ sets, reservation essential.' },
    { name: 'Sea Satin Market', type: 'Seafood Below Windmills', price: '€30–55', rating: '4.4', area: 'Below Windmills, Chora', notes: 'Set right below the famous windmills. Whole grilled fish and seafood, tables on the rocks.' },
  ],
  crete: [
    { name: 'Thalassa', type: 'Seafront Fish Taverna', price: '€20–40', rating: '4.7', area: 'Chania Old Harbour', notes: 'The best seafood on Chania harbour. Fresh sea bream, octopus, fish soup. Terrace tables fill fast.' },
    { name: 'Pallas', type: 'Traditional Cretan', price: '€15–30', rating: '4.6', area: 'Rethymno', notes: 'Slow-cooked Cretan lamb, dakos salad, kalitsounia pastries. A Rethymno institution. Very popular with locals.' },
    { name: 'Meze Meze', type: 'Mezze & Wine', price: '€20–35', rating: '4.5', area: 'Heraklion', notes: 'The best mezze spread in Heraklion. Order everything — boureki, staka, fresh mizithra. Excellent local wines.' },
    { name: 'Kritamon', type: 'Modern Cretan', price: '€30–50', rating: '4.7', area: 'Chania', notes: 'Chef Nikos Sarantopoulos\'s creative take on Cretan ingredients. Beautiful dishes, great tasting menu.' },
    { name: 'To Pigadi', type: 'Mountain Taverna', price: '€15–25', rating: '4.6', area: 'Sfakia', notes: 'In the remote south, mountain lamb antikristo (spit-roasted), local wine, sea views. Worth the drive.' },
  ],
  rhodes: [
    { name: 'Marco Polo Café', type: 'Medieval Taverna', price: '€20–40', rating: '4.7', area: 'Old Town', notes: 'In a converted 15th century Ottoman mansion inside the old town. Romantic and genuinely excellent Greek food.' },
    { name: 'Niki\'s Taverna', type: 'Old Town Classic', price: '€15–30', rating: '4.5', area: 'Old Town', notes: 'Old town favourite since 1960. Grilled fish, mezze, outdoor tables on a medieval street. The institution.' },
    { name: 'Mavrikos', type: 'Fine Seafood', price: '€35–65', rating: '4.8', area: 'Lindos', notes: 'The finest restaurant in Lindos. Family-run since 1933. Seafood excellence with Lindos Acropolis above.' },
    { name: 'Alexis 4 Seasons', city: 'Rhodes', area: 'Old Town', rating: '4.6', reviews: '3400', type: 'Premium Seafood', notes: 'Rhodes\' most celebrated seafood restaurant. On the old town harbour. Excellent wine cellar and service.' },
    { name: 'Steno', type: 'Local Mezze', price: '€10–20', rating: '4.5', area: 'New Town', notes: 'Where locals eat. Tsipouradiko style — ouzo/tsipouro and free-flowing mezze plates. Cash only.' },
  ],
  thessaloniki: [
    { name: 'Bantis Bougatsa', type: 'Bougatsa (Pastry)', price: '€3–5', rating: '4.9', area: 'City Centre', notes: 'The city\'s most famous bougatsa. Hot custard pastry, dusted with icing sugar and cinnamon. Breakfast essential.' },
    { name: 'Myrsini', type: 'Tsipouradiko', price: '€10–20', rating: '4.7', area: 'Ladadika', notes: 'Order a tsipouro (spirit), get mezze automatically. Octopus, fried cheese, tarama. This is how Thessaloniki eats.' },
    { name: 'Extravaganza', type: 'Modern Greek', price: '€25–45', rating: '4.6', area: 'Nea Paralia', notes: 'Seafront modern Greek with beautiful presentation. Excellent for a proper dinner with wine.' },
    { name: 'Ouzeri Melathron', type: 'Traditional Ouzeri', price: '€15–30', rating: '4.5', area: 'Modiano Market', notes: 'Inside the old Modiano market. Classic mezze — feta saganaki, grilled octopus, eggplant salad.' },
    { name: 'Ergon Agora', type: 'Gourmet Deli & Restaurant', price: '€20–35', rating: '4.6', area: 'City Centre', notes: 'Greek gourmet chain but excellent. Deli downstairs for buying, restaurant upstairs for eating. Great for a lunch.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'Athens Metro Day Pass', cost: '€4.50', notes: 'Covers metro, bus and tram for 24 hours. Buy at any metro station.' },
    { name: 'Athens Combined Acropolis Ticket', cost: '€30', notes: 'Covers Acropolis, Ancient Agora, Roman Agora, Kerameikos, Hadrian\'s Library and 2 more sites. Valid 5 days.' },
    { name: 'Greek Ferry (Blue Star / Hellenic Seaways)', cost: '€35–80 per journey', notes: 'Book in advance in peak season (July–August). Athens Piraeus to Santorini ~8 hours.' },
    { name: 'Santorini ATV Rental', cost: '€20–30/day', notes: 'The only practical way to explore Santorini. No driving licence needed for 50cc. Wear sunscreen.' },
  ],
  apps: ['Ferries.gr (Greek ferry booking)', 'Google Maps (offline maps per island)', 'Skyscanner (island hopping flights)', 'Booking.com (last-minute island rooms)', 'e-EFKA (Greece health card registration)', 'Rome2rio (how to get anywhere in Greece)'],
  phrases: [
    { en: 'Hello', jp: 'Γεια σου / Γεια σας', romaji: 'YAH-soo / YAH-sas' },
    { en: 'Thank you', jp: 'Ευχαριστώ', romaji: 'ef-ha-ree-STOH' },
    { en: 'Excuse me', jp: 'Συγνώμη', romaji: 'seeg-NOH-mee' },
    { en: 'The bill please', jp: 'Τον λογαριασμό, παρακαλώ', romaji: 'ton lo-ga-ria-SMOH pa-ra-ka-LOH' },
    { en: 'Where is...?', jp: 'Πού είναι...;', romaji: 'POO EE-neh' },
    { en: 'A glass of wine', jp: 'Ένα ποτήρι κρασί', romaji: 'EH-na po-TEE-ree kra-SEE' },
    { en: 'Delicious!', jp: 'Νόστιμο!', romaji: 'NOSS-tee-mo' },
    { en: 'I don\'t understand', jp: 'Δεν καταλαβαίνω', romaji: 'then ka-ta-la-VEH-no' },
  ],
  phrasesByCategory: [
    {
      category: 'Greetings & Basics',
      emoji: '👋',
      phrases: [
        { en: 'Hello (informal)', jp: 'Γεια σου', romaji: 'YAH-soo' },
        { en: 'Hello (formal / plural)', jp: 'Γεια σας', romaji: 'YAH-sas' },
        { en: 'Good morning', jp: 'Καλημέρα', romaji: 'ka-lee-MEH-ra' },
        { en: 'Good evening', jp: 'Καλησπέρα', romaji: 'ka-lee-SPEH-ra' },
        { en: 'Goodbye', jp: 'Αντίο', romaji: 'an-DEE-oh' },
        { en: 'Thank you', jp: 'Ευχαριστώ', romaji: 'ef-ha-ree-STOH' },
        { en: 'Thank you very much', jp: 'Ευχαριστώ πολύ', romaji: 'ef-ha-ree-STOH po-LEE' },
        { en: 'You\'re welcome', jp: 'Παρακαλώ', romaji: 'pa-ra-ka-LOH' },
        { en: 'Sorry / Excuse me', jp: 'Συγνώμη', romaji: 'seeg-NOH-mee' },
        { en: 'I don\'t understand', jp: 'Δεν καταλαβαίνω', romaji: 'then ka-ta-la-VEH-no' },
        { en: 'Yes', jp: 'Ναι', romaji: 'NEH' },
        { en: 'No', jp: 'Όχι', romaji: 'OH-hee' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚉',
      phrases: [
        { en: 'Where is the station?', jp: 'Πού είναι ο σταθμός;', romaji: 'POO EE-neh oh sta-THMOHS' },
        { en: 'Where is the toilet?', jp: 'Πού είναι η τουαλέτα;', romaji: 'POO EE-neh ee too-a-LEH-ta' },
        { en: 'How much is this?', jp: 'Πόσο κοστίζει;', romaji: 'POH-so kos-TEE-zee' },
        { en: 'I\'m lost', jp: 'Έχω χαθεί', romaji: 'EH-ho ha-THEE' },
        { en: 'One ticket please', jp: 'Ένα εισιτήριο, παρακαλώ', romaji: 'EH-na ee-see-TEE-ree-oh pa-ra-ka-LOH' },
        { en: 'To the port', jp: 'Στο λιμάνι', romaji: 'sto lee-MA-nee' },
        { en: 'Is this seat free?', jp: 'Είναι ελεύθερη αυτή η θέση;', romaji: 'EE-neh eh-LEF-the-ree af-TEE ee THEH-see' },
        { en: 'Stop here please', jp: 'Σταματήστε εδώ, παρακαλώ', romaji: 'sta-ma-TEES-teh eh-THOH pa-ra-ka-LOH' },
      ],
    },
    {
      category: 'Food & Dining',
      emoji: '🐙',
      phrases: [
        { en: 'The bill please', jp: 'Τον λογαριασμό, παρακαλώ', romaji: 'ton lo-ga-ria-SMOH pa-ra-ka-LOH' },
        { en: 'Delicious!', jp: 'Νόστιμο!', romaji: 'NOSS-tee-mo' },
        { en: 'English menu?', jp: 'Έχετε μενού στα αγγλικά;', romaji: 'EH-he-teh meh-NOO sta ang-lee-KA' },
        { en: 'Nut allergy', jp: 'Έχω αλλεργία στους ξηρούς καρπούς', romaji: 'EH-ho a-lehr-YEE-a stoos xee-ROOS kar-POOS' },
        { en: 'No meat please', jp: 'Χωρίς κρέας, παρακαλώ', romaji: 'ho-REES KREH-as pa-ra-ka-LOH' },
        { en: 'Water please', jp: 'Νερό, παρακαλώ', romaji: 'neh-ROH pa-ra-ka-LOH' },
        { en: 'One more please', jp: 'Άλλο ένα, παρακαλώ', romaji: 'A-lo EH-na pa-ra-ka-LOH' },
        { en: 'A table for two', jp: 'Ένα τραπέζι για δύο', romaji: 'EH-na tra-PEH-zee ya THEE-oh' },
        { en: 'A glass of ouzo', jp: 'Ένα ούζο', romaji: 'EH-na OO-zo' },
        { en: 'Cheers!', jp: 'Στην υγειά σας!', romaji: 'steen ee-YA sas' },
      ],
    },
    {
      category: 'Shopping',
      emoji: '🛍️',
      phrases: [
        { en: 'How much is this?', jp: 'Πόσο κοστίζει αυτό;', romaji: 'POH-so kos-TEE-zee af-TOH' },
        { en: 'Do you have a smaller size?', jp: 'Έχετε μικρότερο μέγεθος;', romaji: 'EH-he-teh mee-KROH-teh-ro MEH-yeh-thos' },
        { en: 'May I try this on?', jp: 'Μπορώ να το δοκιμάσω;', romaji: 'bo-ROH na to do-kee-MA-so' },
        { en: 'I\'ll take it', jp: 'Θα το πάρω', romaji: 'tha to PAH-ro' },
        { en: 'Do you accept cards?', jp: 'Δέχεστε κάρτες;', romaji: 'THEH-hes-teh KAR-tes' },
        { en: 'Just looking, thanks', jp: 'Απλώς κοιτάω, ευχαριστώ', romaji: 'ap-LOHS kee-TA-oh ef-ha-ree-STOH' },
        { en: 'Can you lower the price?', jp: 'Μπορείτε να κατεβάσετε την τιμή;', romaji: 'bo-REE-teh na ka-te-VA-se-teh teen tee-MEE' },
        { en: 'Do you ship internationally?', jp: 'Στέλνετε διεθνώς;', romaji: 'STEL-neh-teh thee-eth-NOHS' },
      ],
    },
    {
      category: 'Emergency',
      emoji: '🆘',
      phrases: [
        { en: 'Help!', jp: 'Βοήθεια!', romaji: 'vo-EE-thee-a' },
        { en: 'Call an ambulance', jp: 'Καλέστε ασθενοφόρο', romaji: 'ka-LES-teh as-the-no-FOH-ro' },
        { en: 'Call the police', jp: 'Καλέστε την αστυνομία', romaji: 'ka-LES-teh teen as-tee-no-MEE-a' },
        { en: 'I need a doctor', jp: 'Χρειάζομαι γιατρό', romaji: 'hree-A-zo-meh ya-TROH' },
        { en: 'I\'ve lost my passport', jp: 'Έχασα το διαβατήριό μου', romaji: 'EH-ha-sa to thee-a-va-TEE-ree-oh moo' },
        { en: 'I feel sick', jp: 'Αισθάνομαι άρρωστος', romaji: 'ees-THA-no-meh A-ros-tos' },
        { en: 'Where is the hospital?', jp: 'Πού είναι το νοσοκομείο;', romaji: 'POO EE-neh to no-so-ko-MEE-oh' },
      ],
    },
  ],
}
