export const TRIP = {
  route: 'Barcelona → Valencia → Madrid → Seville → Granada → San Sebastián',
}

export const CITIES = [
  {
    id: 'barcelona',
    name: 'Barcelona',
    emoji: '🦜',
    hotel: 'Hotel Arts Barcelona / El Born area',
    desc: 'Gaudí\'s extraordinary city by the sea — architecture, beaches and world-class food.',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80',
    color: '#c0392b',
    highlights: [
      'Sagrada Família — Gaudí\'s unfinished masterpiece (€26–36, book weeks ahead)',
      'Park Güell — mosaic terraces and dragon staircase (€10, timed entry)',
      'Gothic Quarter — 2,000 years of history in a labyrinthine medieval neighbourhood',
      'La Boqueria Market — Las Ramblas covered market, jamón and fresh juice',
      'Palau de la Música Catalana — UNESCO concert hall, stunning stained glass',
      'Casa Batlló and Casa Milà (La Pedrera) — Gaudí\'s residential masterpieces',
      'Barceloneta Beach — city beach with great chiringuitos (beach bars)',
      'El Born neighbourhood — boutiques, vermouth bars and the Picasso Museum (€14)',
    ],
    tips: [
      'Book Sagrada Família weeks in advance — it sells out entirely',
      'Las Ramblas is tourist-heavy; head one block either side for real Barcelona',
      'Lunch 2–4pm, dinner after 9pm — eating at "normal" hours marks you as a tourist',
      'Metro T-Casual card (10 trips, €12.15) covers everything including airport',
    ],
  },
  {
    id: 'madrid',
    name: 'Madrid',
    emoji: '🎨',
    hotel: 'Hotel Vincci Centrum / Barrio de las Letras',
    desc: 'Spain\'s grand capital — art museums, tapas culture, and a nightlife scene that starts at midnight.',
    image: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'Museo del Prado — Goya, Velázquez, El Greco. Europe\'s finest Old Masters collection (€15, free evenings)',
      'Museo Reina Sofía — Picasso\'s Guernica plus Dalí and Miró (€12, free Saturdays after 1:30pm)',
      'Retiro Park — 350 acres of green space, Crystal Palace, boating lake',
      'Mercado de San Miguel — glass and iron gourmet market, best tapas crawl starter',
      'Royal Palace (Palacio Real) — 3,418 rooms, Europe\'s largest royal palace (€14)',
      'Malasaña & Chueca neighbourhoods — Madrid\'s creative and LGBTQ+ heart',
      'Puerta del Sol and Gran Vía — the beating commercial centre',
      'El Rastro flea market — Sunday morning street market (Sundays only)',
    ],
    tips: [
      'El Rastro is Sundays only — plan your Sunday around it',
      'Prado free entry Mondays 6–8pm and Sundays 5–7pm',
      'Madrid nightlife truly begins at 1–2am — pace yourself',
      'The Paseo del Arte ticket covers Prado + Reina Sofía + Thyssen at reduced rate',
    ],
  },
  {
    id: 'seville',
    name: 'Seville',
    emoji: '💃',
    hotel: 'EME Catedral Hotel / Santa Cruz neighbourhood',
    desc: 'The soul of Andalusia — flamenco, orange trees, Moorish palaces and scorching summer heat.',
    image: 'https://images.unsplash.com/photo-1551867633-194e4b0d4b83?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Real Alcázar — spectacular Mudejar royal palace, UNESCO, still used by Spanish royals (€14.50)',
      'Seville Cathedral & Giralda Tower — world\'s largest Gothic cathedral (€10, tower included)',
      'Barrio Santa Cruz — the old Jewish quarter, orange-tree courtyards and hidden plazas',
      'Triana — the flamenco and ceramics neighbourhood across the Guadalquivir river',
      'La Macarena neighbourhood — authentic Seville, basilica, markets, tapas bars',
      'Plaza de España — jaw-dropping semi-circular 1929 World Expo pavilion',
      'Authentic tablao flamenco show — La Casa del Flamenco (Barrio Santa Cruz, book ahead)',
      'Mercado de la Encarnación (Las Setas) — modern market under a giant mushroom structure',
    ],
    tips: [
      'Avoid July–August — Seville regularly hits 45°C. April–May and October are perfect',
      'Real Alcázar tickets sell out — book online the day before minimum',
      'Tapas culture here means free tapas with every drink ordered (traditional bars)',
      'Flamenco is serious art here — avoid tourist shows, seek authentic tablaos',
    ],
  },
  {
    id: 'granada',
    name: 'Granada',
    emoji: '🏰',
    hotel: 'Parador de Granada / Albaicín neighbourhood',
    desc: 'The Alhambra, Sacromonte caves, and the best free tapas culture in Spain.',
    image: 'https://images.unsplash.com/photo-1529460600437-66236dc066f9?w=800&q=80',
    color: '#d4558f',
    highlights: [
      'Alhambra Palace & Generalife Gardens — UNESCO, the pinnacle of Moorish architecture (€19, must book 2+ weeks ahead)',
      'Albaicín — UNESCO whitewashed Moorish quarter, hilltop viewpoints (miradors)',
      'Mirador de San Nicolás — legendary sunset viewpoint facing the Alhambra',
      'Sacromonte caves — flamenco in genuine cave venues, gitano culture',
      'Granada Cathedral & Royal Chapel — Fernando and Isabel buried here (€5)',
      'Bañuelo Arab Baths — 11th century hammam, best preserved in Spain (€5)',
      'Free tapas with every drink — Granada\'s famous tradition, plates get bigger each round',
      'Capilla Real — Isabelle of Castile\'s mausoleum and treasure collection',
    ],
    tips: [
      'Alhambra MUST be booked weeks in advance — it sells out entirely. Book at alhambra.org',
      'Nasrid Palaces (the highlight) have a specific timed entry — don\'t be late',
      'Granada tapas are free and substantial — budget €2/drink and eat for free all night',
      'Stay in Albaicín for atmosphere, though streets are steep and cobbled',
    ],
  },
  {
    id: 'san-sebastian',
    name: 'San Sebastián',
    emoji: '🐚',
    hotel: 'Hotel de Londres y de Inglaterra / Parte Vieja',
    desc: 'The culinary capital of Europe — more Michelin stars per capita than anywhere on earth.',
    image: 'https://images.unsplash.com/photo-1509233725247-49e657c54213?w=800&q=80',
    color: '#27ae60',
    highlights: [
      'Pintxos bars of Parte Vieja — the Old Town is one giant tapas bar, €2–3 per pintxo',
      'La Concha Beach — one of Europe\'s most beautiful city beaches, stunning bay',
      'Mercado de la Bretxa — covered market, fresh seafood and local produce',
      'Mount Igueldo — funicular to panoramic viewpoint over the bay',
      'Gros neighbourhood — surfer beach, more local pintxos bars, less touristy',
      'Aquarium — marine life and Basque maritime history, great rainy day option (€13)',
      'Arzak, Mugaritz, Akelarre — world-class restaurants if splurging (book months ahead)',
      'Cider houses (sagardotegi) — seasonal January–April, gorge on cod omelette and txuleta',
    ],
    tips: [
      'Pintxos etiquette: go at 7–9pm (aperitivo hour), stand at the bar, order txakoli wine',
      'The best pintxos bars: Bar Sport, La Cuchara de San Telmo, Bar Txepetxa (anchovies)',
      'Renfe train from Madrid (5h) or Barcelona (5h30) — far better than flying',
      'Learn a few Euskara (Basque) words — locals appreciate it enormously',
    ],
  },
  {
    id: 'valencia',
    name: 'Valencia',
    emoji: '🥘',
    hotel: 'SH Valencia Palace / Russafa neighbourhood',
    desc: 'Birthplace of paella, futuristic arts district, and a relaxed coastal charm.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    color: '#f39c12',
    highlights: [
      'City of Arts & Sciences — Santiago Calatrava\'s futuristic complex: Oceanogràfic (€32), Hemisfèric, Museu de les Ciències',
      'La Lonja de la Seda — 15th century Gothic silk exchange, UNESCO (€2)',
      'Mercado Central — one of Europe\'s largest covered markets, stunning modernist building (free)',
      'Original paella lunch in Albufera — the rice paddies that spawned the dish (book in advance)',
      'Barrio del Carmen — medieval streets, street art, bars and antique shops',
      'Valencia Cathedral — claimed to house the Holy Grail (€8)',
      'Malvarrosa Beach — city beach, seafront restaurants with arròs a banda',
      'Russafa neighbourhood — Valencia\'s hipster quarter, vintage shops and excellent coffee',
    ],
    tips: [
      'Order paella only at lunch — locals never eat it for dinner',
      'Genuine paella has chicken, rabbit and broad beans — seafood paella is a tourist adaptation',
      'Las Fallas festival (March 15–19) is spectacular but hotels book up a year ahead',
      'Hire a bike — Valencia is flat and has 150km of cycle lanes',
    ],
  },
]

export const RESTAURANTS = {
  barcelona: [
    { name: 'Bar del Pla', type: 'Catalan Tapas', price: '€15–25', rating: '4.5', area: 'El Born', notes: 'Patatas bravas and croquetas that define the genre. Book ahead.' },
    { name: 'El Xampanyet', type: 'Tapas & Cava', price: '€10–20', rating: '4.6', area: 'El Born', notes: 'House cava and anchovies. 1929 tavern. Cash only, cash worth it.' },
    { name: 'Bodega Sepúlveda', type: 'Traditional Tapas', price: '€10–20', rating: '4.4', area: 'Eixample', notes: 'Old-school, no-frills, incredible jamón and vermouth.' },
    { name: 'Parking Pizza', type: 'Neapolitan Pizza', price: '€15–25', rating: '4.6', area: 'Eixample', notes: 'Best pizza in Barcelona. Queue forms — arrive at opening.' },
    { name: 'Bar Calders', type: 'Vermutería', price: '€5–15', rating: '4.4', area: 'Sant Antoni', notes: 'The city\'s best Sunday vermouth spot. Teeming with locals.' },
  ],
  madrid: [
    { name: 'El Brillante', type: 'Bocadillo de calamares', price: '€5–10', rating: '4.3', area: 'Atocha', notes: 'Madrid\'s legendary calamari sandwich. Classic, greasy, essential.' },
    { name: 'Casa Dani', type: 'Spanish Traditional', price: '€15–25', rating: '4.5', area: 'Mercado de la Paz', notes: 'Best tortilla española in the city. Queue outside the market.' },
    { name: 'La Casa del Abuelo', type: 'Gambas al ajillo', price: '€15–25', rating: '4.4', area: 'Centro', notes: 'Since 1906. Garlic prawns and house sweet wine — the original.' },
    { name: 'DiverXO', type: 'Avant-garde Spanish', price: '€300+', rating: '4.9', area: 'Chamartín', notes: '3 Michelin stars. Daviz Muñoz\'s theatrical tasting menu. Book months ahead.' },
    { name: 'El Anciano Rey de los Vinos', type: 'Traditional Taberna', price: '€10–20', rating: '4.3', area: 'Opera', notes: 'Since 1909. Wine and vermouth in a proper old Madrid bar.' },
  ],
  seville: [
    { name: 'Bar El Comercio', type: 'Traditional Tapas', price: '€10–20', rating: '4.5', area: 'Centro', notes: 'Tiny, standing room only, unmissable. Montaditos and fino sherry.' },
    { name: 'La Azotea', type: 'Modern Andalusian', price: '€20–35', rating: '4.6', area: 'Centro', notes: 'Creative pintxos and modern Sevillian cooking. Book ahead.' },
    { name: 'Bodega Santa Cruz', type: 'Traditional Tapas', price: '€5–15', rating: '4.4', area: 'Santa Cruz', notes: 'The quintessential Seville tapas bar. Stand outside, chalk order on bar.' },
    { name: 'El Rinconcillo', type: 'Historic Taberna', price: '€10–25', rating: '4.3', area: 'Macarena', notes: 'Oldest bar in Seville (1670). Azulejos tiles, sherry casks, incredible atmosphere.' },
    { name: 'Eslava', type: 'Creative Tapas', price: '€15–25', rating: '4.7', area: 'Macarena', notes: 'Multiple Seville tapas award winner. Arrive at 8pm sharp or queue.' },
  ],
  granada: [
    { name: 'Bar Los Diamantes', type: 'Free Tapas', price: '€2–3/drink', rating: '4.5', area: 'Centro', notes: 'Granada\'s institution. Order a drink, get a substantial free tapa. Seafood focus.' },
    { name: 'Bodegas Castañeda', type: 'Historic Bodega', price: '€5–15', rating: '4.4', area: 'Centro', notes: 'Wine barrels line the walls. Free tapas, local wine, chaotic and perfect.' },
    { name: 'El Bar de Eric', type: 'Modern Tapas', price: '€10–20', rating: '4.6', area: 'Realejo', notes: 'Chef-driven creative tapas. Small plates with Alhambra views from terrace.' },
    { name: 'Restaurante Ruta del Azafrán', type: 'Modern Andalusian', price: '€20–35', rating: '4.5', area: 'Albaicín', notes: 'In the Albaicín with views of the Alhambra. Moorish-influenced cuisine.' },
    { name: 'La Cueva de 1900', type: 'Traditional Cave Restaurant', price: '€15–25', rating: '4.3', area: 'Sacromonte', notes: 'Literally in a cave. Hearty Andalusian stews and grilled meats.' },
  ],
  'san-sebastian': [
    { name: 'Bar Txepetxa', type: 'Anchovies (Pintxos)', price: '€2–3/pintxo', rating: '4.7', area: 'Parte Vieja', notes: 'The city\'s best anchovies. 15 anchovy pintxos, nothing else. Tiny and perfect.' },
    { name: 'La Cuchara de San Telmo', type: 'Creative Pintxos', price: '€3–5/pintxo', rating: '4.8', area: 'Parte Vieja', notes: 'Cooked to order pintxos. Foie, bacalao, wagyu. The bar that changed pintxos.' },
    { name: 'Bar Sport', type: 'Classic Pintxos', price: '€2–3/pintxo', rating: '4.5', area: 'Parte Vieja', notes: 'Standing room, elbow to elbow, incredible txakoli and counter-top pintxos.' },
    { name: 'Arzak', type: '3-Michelin Star Basque', price: '€250+', rating: '5.0', area: 'Alto de Miracruz', notes: 'Juan Mari and Elena Arzak. Legendary. Book 3–6 months ahead. Life-changing.' },
    { name: 'Gandarias', type: 'Traditional Basque', price: '€20–35', rating: '4.6', area: 'Parte Vieja', notes: 'Txuleta (beef rib) and bacalao pil pil in a classic Basque setting.' },
  ],
  valencia: [
    { name: 'La Pepica', type: 'Paella (Original)', price: '€20–40', rating: '4.4', area: 'Malvarrosa', notes: 'Hemingway\'s paella restaurant. On the seafront since 1898. Order ahead.' },
    { name: 'Restaurante Levante', type: 'Traditional Paella', price: '€15–30', rating: '4.5', area: 'Albufera', notes: 'In the Albufera rice paddies. Where paella was invented. Traditional recipe.' },
    { name: 'Bar Pilar', type: 'Clóchinas & Beer', price: '€10–20', rating: '4.5', area: 'Carmen', notes: 'Valencia\'s tiny mussels (clóchinas) with cold Estrella Damm. Only open in season.' },
    { name: 'Mercado Central stalls', type: 'Market Food', price: '€5–15', rating: '4.6', area: 'Centro', notes: 'Fresh horchata, fartons, jamón, cheese. The best morning in Valencia.' },
    { name: 'Restaurante Rausell', type: 'Traditional Rice', price: '€20–35', rating: '4.4', area: 'Russafa', notes: 'Excellent arròs a banda and fideuà. Family run, old-school, reliable.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'Tarjeta Multi (Madrid)', cost: '€12.20 (Zone A, 10 trips)', notes: 'Covers metro, bus and suburban trains within Zone A (city centre)' },
    { name: 'T-Casual (Barcelona)', cost: '€12.15 (10 trips)', notes: 'Valid on metro, bus, tram and FGC. Can be shared between people.' },
    { name: 'Renfe Interrail / AVLO', cost: '€15–80/journey', notes: 'High-speed AVE trains between cities. Book ahead for big discounts.' },
    { name: 'Granada City Card', cost: '€29', notes: 'Covers main monuments including Alhambra (but book Alhambra separately ahead)' },
  ],
  apps: ['Google Maps (offline maps for each city)', 'Renfe & Iryo (train booking)', 'Cabify (reliable Spanish Uber alternative)', 'TheFork / ElTenedor (restaurant reservations)', 'Alhambra.org (essential — book your slot)'],
  phrases: [
    { en: 'Hello', jp: 'Hola', romaji: 'OH-la' },
    { en: 'Thank you', jp: 'Gracias', romaji: 'GRA-thee-as' },
    { en: 'Excuse me', jp: 'Perdona / Perdone', romaji: 'pehr-DOH-na' },
    { en: 'The bill please', jp: 'La cuenta, por favor', romaji: 'la KWEN-ta por fa-VOR' },
    { en: 'Where is...?', jp: '¿Dónde está...?', romaji: 'DON-deh es-TA' },
    { en: 'Two beers please', jp: 'Dos cervezas, por favor', romaji: 'dos tser-VEH-thas por fa-VOR' },
    { en: 'Delicious!', jp: '¡Qué rico!', romaji: 'keh REE-ko' },
    { en: 'I don\'t understand', jp: 'No entiendo', romaji: 'no en-TYEN-do' },
  ],
  phrasesByCategory: [
    {
      category: 'Greetings & Basics',
      emoji: '👋',
      phrases: [
        { en: 'Hello', jp: 'Hola', romaji: 'OH-la' },
        { en: 'Good morning', jp: 'Buenos días', romaji: 'BWEH-nos DEE-as' },
        { en: 'Good evening', jp: 'Buenas noches', romaji: 'BWEH-nas NO-ches' },
        { en: 'Goodbye', jp: 'Adiós', romaji: 'a-DYOS' },
        { en: 'See you later', jp: 'Hasta luego', romaji: 'AS-ta LWEH-go' },
        { en: 'Thank you very much', jp: 'Muchas gracias', romaji: 'MOO-chas GRA-thee-as' },
        { en: 'You\'re welcome', jp: 'De nada', romaji: 'deh NA-da' },
        { en: 'Sorry / Excuse me', jp: 'Perdona / Perdone', romaji: 'pehr-DOH-na' },
        { en: 'I don\'t understand', jp: 'No entiendo', romaji: 'no en-TYEN-do' },
        { en: 'Please', jp: 'Por favor', romaji: 'por fa-VOR' },
        { en: 'Yes', jp: 'Sí', romaji: 'SEE' },
        { en: 'No', jp: 'No', romaji: 'no' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚉',
      phrases: [
        { en: 'Where is the station?', jp: '¿Dónde está la estación?', romaji: 'DON-deh es-TA la es-ta-THYON' },
        { en: 'Where is the toilet?', jp: '¿Dónde están los baños?', romaji: 'DON-deh es-TAN los BA-nyos' },
        { en: 'How much is this?', jp: '¿Cuánto cuesta?', romaji: 'KWAN-to KWES-ta' },
        { en: 'I\'m lost', jp: 'Me he perdido', romaji: 'meh eh pehr-DEE-do' },
        { en: 'One ticket please', jp: 'Un billete, por favor', romaji: 'oon bee-YEH-teh por fa-VOR' },
        { en: 'To the airport', jp: 'Al aeropuerto', romaji: 'al a-eh-ro-PWEHR-to' },
        { en: 'Is this seat free?', jp: '¿Está libre este asiento?', romaji: 'es-TA LEE-breh ES-teh a-SYEN-to' },
        { en: 'Stop here please', jp: 'Para aquí, por favor', romaji: 'PA-ra a-KEE por fa-VOR' },
      ],
    },
    {
      category: 'Food & Dining',
      emoji: '🍷',
      phrases: [
        { en: 'The bill please', jp: 'La cuenta, por favor', romaji: 'la KWEN-ta por fa-VOR' },
        { en: 'Delicious!', jp: '¡Qué rico!', romaji: 'keh REE-ko' },
        { en: 'English menu?', jp: '¿Tienen menú en inglés?', romaji: 'TYEN-en meh-NOO en een-GLES' },
        { en: 'Nut allergy', jp: 'Soy alérgico a los frutos secos', romaji: 'soy a-LEHR-hi-ko a los FROO-tos SEH-kos' },
        { en: 'No meat please', jp: 'Sin carne, por favor', romaji: 'seen KAR-neh por fa-VOR' },
        { en: 'Water please', jp: 'Agua, por favor', romaji: 'A-gwa por fa-VOR' },
        { en: 'One more please', jp: 'Otro más, por favor', romaji: 'O-tro MAS por fa-VOR' },
        { en: 'A table for two', jp: 'Una mesa para dos', romaji: 'OO-na MEH-sa PA-ra dos' },
        { en: 'A glass of red wine', jp: 'Un vaso de vino tinto', romaji: 'oon VA-so deh VEE-no TEEN-to' },
        { en: 'Two beers please', jp: 'Dos cervezas, por favor', romaji: 'dos tser-VEH-thas por fa-VOR' },
      ],
    },
    {
      category: 'Shopping',
      emoji: '🛍️',
      phrases: [
        { en: 'How much is this?', jp: '¿Cuánto cuesta esto?', romaji: 'KWAN-to KWES-ta ES-to' },
        { en: 'Do you have a smaller size?', jp: '¿Tiene una talla más pequeña?', romaji: 'TYEN-eh OO-na TA-ya mas peh-KEH-nya' },
        { en: 'May I try this on?', jp: '¿Puedo probármelo?', romaji: 'PWEH-do pro-BAR-meh-lo' },
        { en: 'I\'ll take it', jp: 'Me lo llevo', romaji: 'meh lo YEH-vo' },
        { en: 'Do you accept cards?', jp: '¿Aceptan tarjeta?', romaji: 'a-THEP-tan tar-HEH-ta' },
        { en: 'Just looking, thanks', jp: 'Solo estoy mirando, gracias', romaji: 'SO-lo es-TOY mee-RAN-do GRA-thee-as' },
        { en: 'Do you have another colour?', jp: '¿Lo tienen en otro color?', romaji: 'lo TYEN-en en O-tro ko-LOR' },
        { en: 'Is there a discount?', jp: '¿Hay algún descuento?', romaji: 'ay al-GOON des-KWEN-to' },
      ],
    },
    {
      category: 'Emergency',
      emoji: '🆘',
      phrases: [
        { en: 'Help!', jp: '¡Socorro! / ¡Ayuda!', romaji: 'so-KO-ro / a-YOO-da' },
        { en: 'Call an ambulance', jp: 'Llame a una ambulancia', romaji: 'YA-meh a OO-na am-boo-LAN-thya' },
        { en: 'Call the police', jp: 'Llame a la policía', romaji: 'YA-meh a la po-lee-THEE-a' },
        { en: 'I need a doctor', jp: 'Necesito un médico', romaji: 'neh-theh-SEE-to oon MEH-dee-ko' },
        { en: 'I\'ve lost my passport', jp: 'He perdido mi pasaporte', romaji: 'eh pehr-DEE-do mee pa-sa-POR-teh' },
        { en: 'I feel sick', jp: 'Me encuentro mal', romaji: 'meh en-KWEN-tro MAL' },
        { en: 'Where is the hospital?', jp: '¿Dónde está el hospital?', romaji: 'DON-deh es-TA el os-pee-TAL' },
      ],
    },
  ],
}
