export const TRIP = {
  route: 'Lisbon → Sintra → Douro Valley → Porto → Algarve → Madeira',
}

export const CITIES = [
  {
    id: 'lisbon',
    name: 'Lisbon',
    emoji: '🎶',
    hotel: 'Alfama, Mouraria, or Príncipe Real',
    desc: 'Seven-hilled Atlantic capital of fado, azulejo tiles, custard tarts, and the world\'s most charming trams.',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    color: '#2874a6',
    highlights: [
      'Alfama neighbourhood — medieval Moorish quarter, fado taverns, São Jorge Castle',
      'Belém Tower and Jerónimos Monastery — twin UNESCO Manueline landmarks',
      'Pastéis de Belém — the original pastel de nata, recipe secret since 1837',
      'LX Factory — Sunday market in a repurposed riverside factory complex',
      'Miradouro da Graça — best city viewpoint, sunset with locals and wine',
      'Time Out Market — best food hall in Europe, sample 40+ restaurants in one space',
      'National Azulejo Museum — 600 years of Portuguese tile art in a converted convent',
      'Tram 28 — historic yellow tram through Alfama (crowded but iconic)',
    ],
    tips: [
      'Lisbon Card (24/48/72h) covers all public transport including trams plus 30+ museum entries',
      'Fado: Casa de Linhares and Tasca do Chico are the most authentic. Book ahead.',
      'Pastel de nata: Belém is worth the trip, but Manteigaria in Chiado is the city\'s best kept secret',
      'Hills and cobblestones are relentless — wear comfortable shoes and take the funiculars (eléctricos)',
    ],
  },
  {
    id: 'porto',
    name: 'Porto',
    emoji: '🍷',
    hotel: 'Ribeira or Bonfim',
    desc: 'Granite city on the Douro — dramatic bridges, baroque churches, port wine lodges across the river, and a fierce local pride.',
    image: 'https://images.unsplash.com/photo-1548521927-c58ed53e4b18?w=800&q=80',
    color: '#8e44ad',
    highlights: [
      'Ribeira waterfront — UNESCO-listed medieval riverside quarter under the Dom Luís I bridge',
      'Port wine lodges in Vila Nova de Gaia — Taylor Fladgate, Graham\'s, and Ramos Pinto for tastings',
      'Livraria Lello — one of the world\'s most beautiful bookshops, Art Nouveau staircase (€5 entry)',
      'Palácio da Bolsa — 19th-century stock exchange with Arabian Room (€10 guided tours)',
      'São Bento train station — 20,000 azulejo tiles depicting Portuguese history',
      'Igreja do Carmo — stunning baroque exterior covered in blue and white azulejos',
      'Foz do Douro — where the river meets the Atlantic, seafood restaurants and sunsets',
      'Serralves Museum — contemporary art in a stunning Art Deco villa with gardens (€20)',
    ],
    tips: [
      'Always cross the Dom Luís I bridge on the upper level — the view is extraordinary',
      'Port wine: book a lodge tour in advance. Taylor Fladgate has the best terrace view over the river.',
      'Francesinha is Porto\'s cult sandwich — meat, cured meats, melted cheese, spicy beer sauce. Café Santiago is the institution.',
      'Porto is hilly and largely walkable — Andante card covers metro and bus if legs give out',
    ],
  },
  {
    id: 'algarve',
    name: 'Algarve',
    emoji: '🌊',
    hotel: 'Lagos or Sagres for character; Albufeira for convenience',
    desc: '300 days of sunshine, dramatic golden limestone cliffs, hidden sea caves, and the freshest grilled fish in Europe.',
    image: 'https://images.unsplash.com/photo-1562176546-9b4fae4b5ef2?w=800&q=80',
    color: '#e07b39',
    highlights: [
      'Ponta da Piedade — the most dramatic sea stack and cave formations in Europe, best by kayak',
      'Benagil Sea Cave — Europe\'s most beautiful sea cave, only accessible by boat or strong swimmer',
      'Sagres Fortress — Europe\'s most south-westerly point, Wind Rose, wild Atlantic cliffs',
      'Silves Castle — best-preserved Moorish castle in the Algarve, stunning terracotta ramparts',
      'Ria Formosa Natural Park — lagoon ecosystem, flamingos, clam farmers, Tavira Island ferry',
      'Ferragudo and Carvoeiro — quieter alternatives to overcrowded Lagos with great local restaurants',
      'Albufeira Old Town — medieval street grid, evening market, free from the resort development',
      'Via Algarviana — long-distance hiking trail across the interior hinterland',
    ],
    tips: [
      'Car hire is essential — the Algarve coast is 200km and buses are infrequent',
      'Cataplana (seafood stew in copper pot) is the regional speciality — at least one per trip',
      'Boat trips to sea caves book out early in summer — reserve the morning before or online',
      'East Algarve (Tavira, Olhão) is far less touristy and more authentically Portuguese',
    ],
  },
  {
    id: 'sintra',
    name: 'Sintra',
    emoji: '🏰',
    hotel: 'Day trip from Lisbon (40 min by train) or stay overnight for empty mornings',
    desc: 'A fairy-tale UNESCO landscape of Romantic palaces, Moorish ruins, and dense forest-covered hills above the Atlantic.',
    image: 'https://images.unsplash.com/photo-1570139135759-66e6e7ccfcb4?w=800&q=80',
    color: '#d4a017',
    highlights: [
      'Pena Palace — outrageously colourful 19th-century Romantic palace on a forested peak',
      'Moorish Castle — ruined hilltop fortress with panoramic views over the Serra de Sintra',
      'Quinta da Regaleira — eccentric estate with initiation wells and underground tunnels',
      'Palácio Nacional de Sintra — medieval royal palace with twin conical chimneys in the town centre',
      'Monserrate Palace — spectacular Moorish-Gothic-Indian hybrid palace and botanical gardens',
      'Cabo da Roca — westernmost point of continental Europe, lighthouse, raw Atlantic cliffs',
      'Colares wine village — tiny coastal appellation producing unique wines from ancient ungrafted vines',
      'Praia das Maçãs — Atlantic surfing beach at the end of an old tram line through the forest',
    ],
    tips: [
      'Arrive before 9am or stay overnight — Pena Palace gets 3 million visitors per year',
      'Sintra Hills Circuit bus (435 + 434) connects main palaces — buy a day ticket',
      'Travesseiros (puff pastries) and queijadas (cheese tarts) from Casa Piriquita since 1862',
      'Sintra Palace is in the town centre and often overlooked — extraordinary Moorish tile interior',
    ],
  },
  {
    id: 'douro',
    name: 'Douro Valley',
    emoji: '🍇',
    hotel: 'Quintas (wine estate guesthouses) along the river',
    desc: 'UNESCO-listed terraced vineyards dropping to the Douro river — the birthplace of Port wine and one of Europe\'s great slow-travel experiences.',
    image: 'https://images.unsplash.com/photo-1523428461295-92770e70d7ae?w=800&q=80',
    color: '#6e2c00',
    highlights: [
      'Quinta da Crasto — spectacular terrace views, excellent red wines, free tasting with tours',
      'Pinhão train station — azulejo-covered walls depicting Douro harvest scenes',
      'Boat cruise from Pinhão — the definitive way to see the terraced valley at river level',
      'Miradouro de São Leonardo de Galafura — highest viewpoint over the Douro river bends',
      'Quinta do Crasto, Ramos Pinto, Quinta do Seixo — wineries open for visits and tastings',
      'Régua wine museum — excellent introduction to Port wine history and viticulture',
      'Casal de Loivos — hilltop village with the most dramatic Douro panorama in the valley',
      'Harvest festival (September) — grape treading by foot is still done at some traditional quintas',
    ],
    tips: [
      'Train from Porto to Pinhão (2.5h) follows the river and is one of Portugal\'s great rail journeys',
      'Car gives flexibility for the hillside wineries — many quintas require 4km of dirt road',
      'Book quinta accommodation 2–3 months ahead for summer and harvest season',
      'Dry reds from the Douro are outstanding alongside the Port — try Niepoort Redoma and Quinta do Crasto Reserva',
    ],
  },
  {
    id: 'madeira',
    name: 'Madeira',
    emoji: '🌺',
    hotel: 'Funchal\'s Zona Velha (Old Town) or hillside in Monte',
    desc: 'Volcanic Atlantic island of levada walks, sub-tropical gardens, toboggan rides, and the wine that kept the British Empire going.',
    image: 'https://images.unsplash.com/photo-1513895518469-6f2fe5e7ee7e?w=800&q=80',
    color: '#2d6a4f',
    highlights: [
      'Levada walks — 2,500km of historic irrigation channels through forest and cliffs',
      'Monte toboggan — wicker sledge rides down the hillside to Funchal (since 1850)',
      'Jardim Botânico — spectacular gardens above Funchal with views to the sea',
      'Cabo Girão — one of Europe\'s highest sea cliffs (580m), glass floor viewpoint',
      'Mercado dos Lavradores — Funchal\'s covered market with tropical fruits and dried fish',
      'Pico Ruivo — summit hike (1,861m) through cloud forest, above the clouds at sunrise',
      'Reid\'s Palace afternoon tea — Madeira\'s legendary grand hotel since 1891',
      'Blandy\'s Wine Lodge — Madeira wine tasting in a 200-year-old lodge in Funchal',
    ],
    tips: [
      'Hire a car — the island\'s mountain road system is extraordinary and levadas are spread across the island',
      'Espetada (beef skewer grilled over bay laurel wood) and espada (black scabbardfish) are the local specialities',
      'Madeira wine styles: Sercial (dry) to Malmsey (sweet) — each works with different food',
      'Weather changes fast — layers always, and check levada conditions before committing to long walks',
    ],
  },
]

export const RESTAURANTS = {
  lisbon: [
    { name: 'Tasca do Chico', type: 'Fado & Traditional', price: '€30–50', rating: '4.8', area: 'Mouraria', notes: 'The most authentic fado house in Lisbon. Small, intimate, booking essential. Closed Sunday.' },
    { name: 'Time Out Market', type: 'Food Hall', price: '€15–30', rating: '4.6', area: 'Cais do Sodré', notes: 'Best chefs in Lisbon under one roof. Alexandre Silva, Henrique Sá Pessoa pop-ups. Excellent for groups.' },
    { name: 'Belcanto', type: 'Modern Portuguese', price: '€150+', rating: '4.9', area: 'Chiado', notes: 'José Avillez\'s two Michelin star flagship. The pinnacle of modern Portuguese cuisine. Book months ahead.' },
    { name: 'Solar dos Presuntos', type: 'Classic Portuguese', price: '€35–55', rating: '4.5', area: 'Avenida da Liberdade', notes: 'Beloved institution for traditional Portuguese. Excellent bacalhau and roast suckling pig.' },
    { name: 'Pastéis de Belém', type: 'Pastelaria', price: '€2–5', rating: '4.7', area: 'Belém', notes: 'The original pastel de nata. Recipe unchanged since 1837. Always warm, always with cinnamon and icing sugar.' },
  ],
  porto: [
    { name: 'Café Santiago', type: 'Francesinha', price: '€10–18', rating: '4.5', area: 'Bolhão', notes: 'The institution for Porto\'s cult sandwich. Cash only, queue at lunch. Unmissable cultural experience.' },
    { name: 'DOP', type: 'Modern Portuguese', price: '€60–90', rating: '4.7', area: 'Ribeira', notes: 'Rui Paula\'s elegant riverside restaurant. The best modern Portuguese cooking in Porto.' },
    { name: 'Pedro Lemos', type: 'Gastronomic', price: '€100–140', rating: '4.8', area: 'Foz', notes: 'One Michelin star. Tasting menu showcasing Douro and Atlantic produce with extraordinary technique.' },
    { name: 'Taberna dos Mercadores', type: 'Traditional', price: '€20–35', rating: '4.6', area: 'Ribeira', notes: 'Tiny, no-frills, superb. Bacalhau à Gomes de Sá, tripas à moda do Porto, all the classics.' },
    { name: 'Taylor\'s Port Lodge', type: 'Wine Tasting', price: '€15–25', rating: '4.8', area: 'Vila Nova de Gaia', notes: 'Best terraced restaurant view of Porto over a glass of Tawny. Book the terrace for sunset.' },
  ],
  algarve: [
    { name: 'Restaurante Henrique Leis', type: 'Gastronomic', price: '€80–120', rating: '4.7', area: 'Almancil', notes: 'Swiss-born chef, one Michelin star. Refined European cuisine using Algarvian produce. Book ahead.' },
    { name: 'Tasca do Celso', type: 'Traditional Algarvian', price: '€20–35', rating: '4.6', area: 'Lagos', notes: 'The most authentic local restaurant in Lagos. Cataplana de marisco for two is the order.' },
    { name: 'Marisqueira Rui', type: 'Seafood', price: '€30–50', rating: '4.5', area: 'Silves', notes: 'Legendary riverside seafood restaurant. Grilled fish and shellfish platters. Busy — reserve.' },
    { name: 'Restaurante Fortaleza do Guincho', type: 'Grand Gastronomy', price: '€100+', rating: '4.7', area: 'Cascais', notes: 'One Michelin star in a clifftop fortress. Atlantic panorama. Exceptional Portuguese-French cuisine.' },
  ],
  sintra: [
    { name: 'Casa Piriquita', type: 'Pastelaria', price: '€5–10', rating: '4.6', area: 'Sintra town', notes: 'Since 1862. Travesseiros (almond cream puff pastry) and queijadas (fresh cheese tarts) are the icons.' },
    { name: 'Restaurante Tágide', type: 'Modern Portuguese', price: '€50–80', rating: '4.5', area: 'Sintra town', notes: 'The best full meal in Sintra. Elegant dining with views over the palace chimneys.' },
    { name: 'Saudade', type: 'Traditional', price: '€20–35', rating: '4.4', area: 'Sintra town', notes: 'Reliable, good value. Honest Portuguese cooking in the town centre.' },
  ],
  douro: [
    { name: 'DOC Restaurant', type: 'Contemporary Portuguese', price: '€50–80', rating: '4.7', area: 'Folgosa', notes: 'Rui Paula\'s Douro flagship. Floating deck over the river. Booking essential. Stunning setting.' },
    { name: 'Quinta do Crasto Restaurant', type: 'Wine Estate Dining', price: '€40–65', rating: '4.6', area: 'Gouvinhas', notes: 'Lunch only at the quinta. Petiscos on the terrace paired with their wines. Book through the estate.' },
    { name: 'Castas e Pratos', type: 'Regional / Wine Bar', price: '€20–35', rating: '4.5', area: 'Régua', notes: 'Great selection of Douro wines by the glass with regional sharing plates. Relaxed atmosphere.' },
  ],
  madeira: [
    { name: 'William (Reid\'s Palace)', type: 'Grand Gastronomy', price: '€120+', rating: '4.8', area: 'Funchal', notes: 'One Michelin star. Most elegant dining room in Madeira. Afternoon tea also unmissable (€65).' },
    { name: 'Armazém do Sal', type: 'Modern Portuguese', price: '€45–70', rating: '4.6', area: 'Funchal Old Town', notes: 'Beautifully converted salt warehouse. Creative Madeiran cuisine with excellent wine selection.' },
    { name: 'O Celeiro', type: 'Traditional Madeiran', price: '€20–35', rating: '4.4', area: 'Funchal', notes: 'Classic espada com banana (black scabbardfish with banana) and espetada. Authentic and cheerful.' },
    { name: 'Mercado dos Lavradores', type: 'Market / Street Food', price: '€5–15', rating: '4.5', area: 'Funchal', notes: 'Poncha (local aguardente cocktail), exotic fruits, dried figs and almonds. Morning market essential.' },
  ],
}

export const ITINERARY = []

export const PRACTICAL = {
  passes: [
    { name: 'Lisboa Card', cost: '€22 (24h) / €38 (48h) / €47 (72h)', notes: 'All Lisbon public transport (including trams and funiculars) plus 30+ museums free or discounted' },
    { name: 'Andante Card (Porto)', cost: 'Load as needed', notes: 'Covers Porto metro, bus, and tram network. Zone Z2 covers centre and Vila Nova de Gaia.' },
    { name: 'Porto Card', cost: '€15 (2 days)', notes: 'Unlimited public transport and discounts at port wine lodges, museums and boat tours' },
    { name: 'TAP Air Portugal', cost: 'Varies', notes: 'National carrier connects Lisbon–Porto–Faro–Funchal. Check Azores Airlines for Madeira alternatives.' },
  ],
  apps: ['Google Maps (offline)', 'CP (train tickets)', 'Rede Expressos (bus)', 'Google Translate', 'Zomato (restaurants)', 'XE Currency'],
  phrases: [],
  phrasesByCategory: [
    {
      category: 'Greetings & Basics',
      emoji: '👋',
      phrases: [
        { en: 'Hello', jp: 'Olá', romaji: 'Oh-lah' },
        { en: 'Good morning', jp: 'Bom dia', romaji: 'Bohn dee-ah' },
        { en: 'Good afternoon', jp: 'Boa tarde', romaji: 'Boh-ah tar-deh' },
        { en: 'Good evening', jp: 'Boa noite', romaji: 'Boh-ah noy-teh' },
        { en: 'Goodbye', jp: 'Adeus', romaji: 'Ah-day-oosh' },
        { en: 'Please', jp: 'Por favor', romaji: 'Por fah-vor' },
        { en: 'Thank you', jp: 'Obrigado (m) / Obrigada (f)', romaji: 'Oh-bree-gah-doo / Oh-bree-gah-dah' },
        { en: 'Yes', jp: 'Sim', romaji: 'Seem' },
        { en: 'No', jp: 'Não', romaji: 'Nowng' },
        { en: 'Excuse me', jp: 'Com licença', romaji: 'Kohn lee-sen-sah' },
      ],
    },
    {
      category: 'Getting Around',
      emoji: '🚉',
      phrases: [
        { en: 'Where is...?', jp: 'Onde fica...?', romaji: 'On-deh fee-kah...?' },
        { en: 'The station', jp: 'A estação', romaji: 'Ah esh-tah-sowng' },
        { en: 'A ticket to...', jp: 'Um bilhete para...', romaji: 'Oong bee-yeh-teh pah-rah...' },
        { en: 'How much does it cost?', jp: 'Quanto custa?', romaji: 'Kwahn-too koosh-tah?' },
        { en: 'To the left', jp: 'À esquerda', romaji: 'Ah esh-kehr-dah' },
        { en: 'To the right', jp: 'À direita', romaji: 'Ah dee-ray-tah' },
        { en: 'Straight ahead', jp: 'Em frente', romaji: 'Em fren-teh' },
        { en: 'I am lost', jp: 'Estou perdido(a)', romaji: 'Esh-toh pehr-dee-doo' },
      ],
    },
    {
      category: 'Food & Dining',
      emoji: '🐟',
      phrases: [
        { en: 'A table for two please', jp: 'Uma mesa para dois, por favor', romaji: 'Ooh-mah may-zah pah-rah doysh, por fah-vor' },
        { en: 'The menu please', jp: 'A ementa, por favor', romaji: 'Ah ee-men-tah, por fah-vor' },
        { en: 'The bill please', jp: 'A conta, por favor', romaji: 'Ah kon-tah, por fah-vor' },
        { en: 'Delicious!', jp: 'Delicioso!', romaji: 'Deh-lee-syoh-zoo!' },
        { en: 'Do you have vegetarian options?', jp: 'Tem opções vegetarianas?', romaji: 'Teng op-sowng-sh veh-zheh-tah-ree-ah-nahsh?' },
        { en: 'Water please', jp: 'Água, por favor', romaji: 'Ah-gwah, por fah-vor' },
        { en: 'A glass of wine', jp: 'Um copo de vinho', romaji: 'Oong koh-poo deh vee-nyoo' },
        { en: 'What do you recommend?', jp: 'O que recomenda?', romaji: 'Oo keh reh-koh-men-dah?' },
      ],
    },
    {
      category: 'Shopping',
      emoji: '🛍️',
      phrases: [
        { en: 'How much is this?', jp: 'Quanto custa isto?', romaji: 'Kwahn-too koosh-tah ish-too?' },
        { en: 'Can I try this on?', jp: 'Posso experimentar?', romaji: 'Poh-soo esh-peh-ree-men-tar?' },
        { en: 'Do you have a smaller size?', jp: 'Tem um tamanho mais pequeno?', romaji: 'Teng oong tah-mah-nyoo my-sh peh-keh-noo?' },
        { en: 'I\'ll take it', jp: 'Fico com este', romaji: 'Fee-koo kohn esh-teh' },
        { en: 'Do you accept cards?', jp: 'Aceitam cartão?', romaji: 'Ah-say-tang kar-towng?' },
        { en: 'Just looking, thanks', jp: 'Só a ver, obrigado', romaji: 'Soh ah vehr, oh-bree-gah-doo' },
        { en: 'Tax refund please', jp: 'Reembolso fiscal, por favor', romaji: 'Heh-em-bohl-soo fis-kal, por fah-vor' },
        { en: 'Do you have a bag?', jp: 'Tem um saco?', romaji: 'Teng oong sah-koo?' },
      ],
    },
    {
      category: 'Emergency',
      emoji: '🆘',
      phrases: [
        { en: 'Help!', jp: 'Socorro!', romaji: 'Soh-koh-hoo!' },
        { en: 'Call the police', jp: 'Chame a polícia', romaji: 'Shah-meh ah poh-lee-syah' },
        { en: 'Call an ambulance', jp: 'Chame uma ambulância', romaji: 'Shah-meh ooh-mah am-boo-lahn-syah' },
        { en: 'I need a doctor', jp: 'Preciso de um médico', romaji: 'Preh-see-zoo deh oong meh-dee-koo' },
        { en: 'I\'ve lost my passport', jp: 'Perdi o meu passaporte', romaji: 'Pehr-dee oo may-oo pah-sah-por-teh' },
        { en: 'Where is the hospital?', jp: 'Onde fica o hospital?', romaji: 'On-deh fee-kah oo osh-pee-tal?' },
        { en: 'I feel sick', jp: 'Sinto-me mal', romaji: 'Seen-too-meh mal' },
      ],
    },
  ],
}
